START TRANSACTION;

-- if this script hangs, we should flush all tables
-- FLUSH TABLES;

-- needed if local_infile is disabled, need root privileges
-- SET GLOBAL local_infile = 'ON';

SET autocommit = 0;

-- recreate tables
DROP TABLE IF EXISTS participant_data_stage;
DROP TABLE IF EXISTS participant_data;
DROP TABLE IF EXISTS participant;

CREATE TABLE IF NOT EXISTS `participant` (
    `id`            INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `sex`           ENUM('female', 'male'),
    `ancestry`      ENUM('white', 'black', 'hispanic', 'asian', 'pacific_islander', 'american_indian')
);

CREATE TABLE IF NOT EXISTS `participant_data` (
    `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `phenotype_id` INTEGER NOT NULL,
    `participant_id` INTEGER,
    `value` DOUBLE,
    `age` INTEGER,
    FOREIGN KEY (phenotype_id) REFERENCES phenotype(id),
    FOREIGN KEY (participant_id) REFERENCES participant(id)
);

CREATE TABLE `participant_data_stage` (
    `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
    `plco_id` TEXT,
    `chf_cat` DOUBLE,
    `ischemicheart_cat` DOUBLE,
    `depression_cat` DOUBLE,
    `diabetes_cat` DOUBLE,
    `ra_oa_cat` DOUBLE,
    `chronickidney_cat` DOUBLE,
    `copd_cat` DOUBLE,
    `atrial_fib_cat` DOUBLE,
    `alzh_cat` DOUBLE,
    `alzh_demen_cat` DOUBLE,
    `any_use` DOUBLE,
    `part_d_mosx` DOUBLE,
    `chronic` DOUBLE,
    `mos` DOUBLE,
    `j_adeno_carcinoma` DOUBLE,
    `j_adeno_carcinoma_fup_days` DOUBLE,
    `j_adeno_carcinoma_fup_age` DOUBLE,
    `j_adeno_carcinoma_dx_age` DOUBLE,
    `j_alcohol_related_dx_age` DOUBLE,
    `j_alcohol_related` DOUBLE,
    `j_alcohol_related_fup_age` DOUBLE,
    `j_alcohol_related_fup_days` DOUBLE,
    `j_bcell` DOUBLE,
    `j_bcell_fup_days` DOUBLE,
    `j_bcell_fup_age` DOUBLE,
    `j_bcell_dx_age` DOUBLE,
    `j_bili_cancer` DOUBLE,
    `j_bili_cancer_fup_days` DOUBLE,
    `j_bili_cancer_fup_age` DOUBLE,
    `j_bili_cancer_dx_age` DOUBLE,
    `j_blad_cancer` DOUBLE,
    `j_blad_cancer_fup_days` DOUBLE,
    `j_blad_cancer_fup_age` DOUBLE,
    `j_blad_cancer_dx_age` DOUBLE,
    `j_breast_cancer` DOUBLE,
    `j_breast_cancer_fup_days` DOUBLE,
    `j_breast_cancer_fup_age` DOUBLE,
    `j_breast_cancer_dx_age` DOUBLE,
    `j_breast_invasive` DOUBLE,
    `j_breast_insitu` DOUBLE,
    `j_breast_ductal` DOUBLE,
    `j_breast_lobular` DOUBLE,
    `j_breast_tubular` DOUBLE,
    `j_breast_er_pos_or_equiv` DOUBLE,
    `j_breast_er_neg` DOUBLE,
    `j_breast_pr_pos_or_equiv` DOUBLE,
    `j_breast_pr_neg` DOUBLE,
    `j_breast_er_or_pr_pos` DOUBLE,
    `j_breast_er_and_pr_neg` DOUBLE,
    `j_breast_her2_pos_or_equiv` DOUBLE,
    `j_breast_her2_neg` DOUBLE,
    `j_breast_er_pr_and_her2_neg` DOUBLE,
    `j_breast_grade34` DOUBLE,
    `j_breast_grade2` DOUBLE,
    `j_breast_grade1` DOUBLE,
    `j_carcinoma` DOUBLE,
    `j_carcinoma_fup_days` DOUBLE,
    `j_carcinoma_fup_age` DOUBLE,
    `j_carcinoma_dx_age` DOUBLE,
    `j_colo_cancer` DOUBLE,
    `j_colo_cancer_fup_days` DOUBLE,
    `j_colo_cancer_fup_age` DOUBLE,
    `j_colo_cancer_dx_age` DOUBLE,
    `j_colo_distal` DOUBLE,
    `j_colo_distal_proximal` DOUBLE,
    `j_colo_proximal` DOUBLE,
    `j_colo_rectal` DOUBLE,
    `j_diabetes_related_dx_age` DOUBLE,
    `j_diabetes_related` DOUBLE,
    `j_diabetes_related_fup_age` DOUBLE,
    `j_diabetes_related_fup_days` DOUBLE,
    `j_ebv_related_dx_age` DOUBLE,
    `j_ebv_related` DOUBLE,
    `j_ebv_related_fup_age` DOUBLE,
    `j_ebv_related_fup_days` DOUBLE,
    `j_endo_cancer` DOUBLE,
    `j_endo_cancer_fup_days` DOUBLE,
    `j_endo_cancer_fup_age` DOUBLE,
    `j_endo_cancer_dx_age` DOUBLE,
    `j_endo_neuro` DOUBLE,
    `j_endo_neuro_fup_days` DOUBLE,
    `j_endo_neuro_fup_age` DOUBLE,
    `j_endo_neuro_dx_age` DOUBLE,
    `j_esoph_cancer` DOUBLE,
    `j_esoph_cancer_fup_days` DOUBLE,
    `j_esoph_cancer_fup_age` DOUBLE,
    `j_esoph_cancer_dx_age` DOUBLE,
    `j_esoph_adeno_carcinoma` DOUBLE,
    `j_esoph_squamous` DOUBLE,
    `j_hbv_related_dx_age` DOUBLE,
    `j_hbv_related` DOUBLE,
    `j_hbv_related_fup_age` DOUBLE,
    `j_hbv_related_fup_days` DOUBLE,
    `j_hcv_related_dx_age` DOUBLE,
    `j_hcv_related` DOUBLE,
    `j_hcv_related_fup_age` DOUBLE,
    `j_hcv_related_fup_days` DOUBLE,
    `j_height_related_dx_age` DOUBLE,
    `j_height_related` DOUBLE,
    `j_height_related_fup_age` DOUBLE,
    `j_height_related_fup_days` DOUBLE,
    `j_helicobacter_related_dx_age` DOUBLE,
    `j_helicobacter_related` DOUBLE,
    `j_helicobacter_related_fup_age` DOUBLE,
    `j_helicobacter_related_fup_days` DOUBLE,
    `j_hematologic` DOUBLE,
    `j_hematologic_fup_days` DOUBLE,
    `j_hematologic_fup_age` DOUBLE,
    `j_hematologic_dx_age` DOUBLE,
    `j_hnc_cancer` DOUBLE,
    `j_hnc_cancer_fup_days` DOUBLE,
    `j_hnc_cancer_fup_age` DOUBLE,
    `j_hnc_cancer_dx_age` DOUBLE,
    `j_hnc_larynx` DOUBLE,
    `j_hnc_lip_oral_pharynx` DOUBLE,
    `j_hnc_naso_mid_sinus` DOUBLE,
    `j_hpv_related_dx_age` DOUBLE,
    `j_hpv_related` DOUBLE,
    `j_hpv_related_fup_age` DOUBLE,
    `j_hpv_related_fup_days` DOUBLE,
    `j_infection_related_dx_age` DOUBLE,
    `j_infection_related` DOUBLE,
    `j_infection_related_fup_age` DOUBLE,
    `j_infection_related_fup_days` DOUBLE,
    `j_kidney_cancer_fup_days` DOUBLE,
    `j_kidney_cancer_fup_age` DOUBLE,
    `j_kidney_cancer_dx_age` DOUBLE,
    `j_kidney_cancer` DOUBLE,
    `j_kidney_renalcell_clearcell` DOUBLE,
    `j_kidney_renalcell_nos` DOUBLE,
    `j_gast_cancer` DOUBLE,
    `j_gast_cancer_fup_days` DOUBLE,
    `j_gast_cancer_fup_age` DOUBLE,
    `j_gast_cancer_dx_age` DOUBLE,
    `j_gast_cardia` DOUBLE,
    `j_gast_noncardia` DOUBLE,
    `j_glio_cancer` DOUBLE,
    `j_glio_cancer_fup_days` DOUBLE,
    `j_glio_cancer_fup_age` DOUBLE,
    `j_glio_cancer_dx_age` DOUBLE,
    `j_liver_xintra_cancer_fup_days` DOUBLE,
    `j_liver_xintra_cancer_fup_age` DOUBLE,
    `j_liver_xintra_cancer_dx_age` DOUBLE,
    `j_liver_xintra_cancer` DOUBLE,
    `j_lung_cancer` DOUBLE,
    `j_lung_cancer_fup_days` DOUBLE,
    `j_lung_cancer_fup_age` DOUBLE,
    `j_lung_cancer_dx_age` DOUBLE,
    `j_lung_smallcell` DOUBLE,
    `j_lung_adeno` DOUBLE,
    `j_lung_squam` DOUBLE,
    `j_lymphoid` DOUBLE,
    `j_lymphoid_fup_days` DOUBLE,
    `j_lymphoid_fup_age` DOUBLE,
    `j_lymphoid_dx_age` DOUBLE,
    `j_cll` DOUBLE,
    `j_cll_fup_days` DOUBLE,
    `j_cll_fup_age` DOUBLE,
    `j_cll_dx_age` DOUBLE,
    `j_mbreast_cancer` DOUBLE,
    `j_mbreast_cancer_fup_days` DOUBLE,
    `j_mbreast_cancer_fup_age` DOUBLE,
    `j_mbreast_cancer_dx_age` DOUBLE,
    `j_mela_cancer` DOUBLE,
    `j_mela_cancer_fup_days` DOUBLE,
    `j_mela_cancer_fup_age` DOUBLE,
    `j_mela_cancer_dx_age` DOUBLE,
    `j_mela_invasive_cancer` DOUBLE,
    `j_mela_invasive_cancer_fup_age` DOUBLE,
    `j_mela_invasive_cancer_dx_age` DOUBLE,
    `j_mela_invasive_cancer_fup_days` DOUBLE,
    `j_mesoth` DOUBLE,
    `j_mesoth_fup_days` DOUBLE,
    `j_mesoth_fup_age` DOUBLE,
    `j_mesoth_dx_age` DOUBLE,
    `j_myeloid` DOUBLE,
    `j_myeloid_fup_days` DOUBLE,
    `j_myeloid_fup_age` DOUBLE,
    `j_myeloid_dx_age` DOUBLE,
    `j_obesity_related_dx_age` DOUBLE,
    `j_obesity_related` DOUBLE,
    `j_obesity_related_fup_age` DOUBLE,
    `j_obesity_related_fup_days` DOUBLE,
    `j_osumm_cancer` DOUBLE,
    `j_osumm_cancer_fup_days` DOUBLE,
    `j_osumm_cancer_fup_age` DOUBLE,
    `j_osumm_cancer_dx_age` DOUBLE,
    `j_osumm_serous_grade_high` DOUBLE,
    `j_panc_cancer` DOUBLE,
    `j_panc_cancer_fup_days` DOUBLE,
    `j_panc_cancer_fup_age` DOUBLE,
    `j_panc_cancer_dx_age` DOUBLE,
    `j_phys_act_related_dx_age` DOUBLE,
    `j_phys_act_related` DOUBLE,
    `j_phys_act_related_fup_age` DOUBLE,
    `j_phys_act_related_fup_days` DOUBLE,
    `j_pros_cancer` DOUBLE,
    `j_pros_cancer_fup_days` DOUBLE,
    `j_pros_cancer_fup_age` DOUBLE,
    `j_pros_cancer_dx_age` DOUBLE,
    `j_pros_non_advanced` DOUBLE,
    `j_pros_advanced_including7` DOUBLE,
    `j_pros_advanced_excluding7` DOUBLE,
    `j_sarcoma` DOUBLE,
    `j_sarcoma_fup_days` DOUBLE,
    `j_sarcoma_fup_age` DOUBLE,
    `j_sarcoma_dx_age` DOUBLE,
    `j_smoking_related_dx_age` DOUBLE,
    `j_smoking_related` DOUBLE,
    `j_smoking_related_fup_age` DOUBLE,
    `j_smoking_related_fup_days` DOUBLE,
    `j_solid_tumor` DOUBLE,
    `j_solid_tumor_fup_days` DOUBLE,
    `j_solid_tumor_fup_age` DOUBLE,
    `j_solid_tumor_dx_age` DOUBLE,
    `j_squamous` DOUBLE,
    `j_squamous_fup_days` DOUBLE,
    `j_squamous_fup_age` DOUBLE,
    `j_squamous_dx_age` DOUBLE,
    `j_thyd_cancer` DOUBLE,
    `j_thyd_cancer_fup_days` DOUBLE,
    `j_thyd_cancer_fup_age` DOUBLE,
    `j_thyd_cancer_dx_age` DOUBLE,
    `j_upgi_cancer` DOUBLE,
    `j_upgi_cancer_fup_days` DOUBLE,
    `j_upgi_cancer_fup_age` DOUBLE,
    `j_upgi_cancer_dx_age` DOUBLE,
    `j_urothelial` DOUBLE,
    `j_urothelial_fup_days` DOUBLE,
    `j_urothelial_fup_age` DOUBLE,
    `j_urothelial_dx_age` DOUBLE,
    `is_dead` DOUBLE,
    `mortality_exitage` DOUBLE,
    `dth_days` DOUBLE,
    `mortality_exitdays_unadj` DOUBLE,
    `f_death_ischemic` DOUBLE,
    `f_death_cerebrovascular` DOUBLE,
    `f_death_rheumatic` DOUBLE,
    `f_death_hypertensive` DOUBLE,
    `f_death_peripheral` DOUBLE,
    `f_death_heart` DOUBLE,
    `f_death_cardiac` DOUBLE,
    `f_death_arrhythmia` DOUBLE,
    `f_death_endocarditis` DOUBLE,
    `f_death_cardiovascular` DOUBLE,
    `f_death_cancer` DOUBLE,
    `f_death_chronicresp` DOUBLE,
    `f_death_alzheimers` DOUBLE,
    `f_death_diabetes` DOUBLE,
    `f_death_nephritis` DOUBLE,
    `f_death_chronicliver` DOUBLE,
    `f_death_parkinsons` DOUBLE,
    `bq_educat_o` DOUBLE,
    `bq_marital_co` DOUBLE,
    `bq_fmenstr_o` DOUBLE,
    `bq_tubal_o` DOUBLE,
    `bq_bbd_b` DOUBLE,
    `bq_benign_ovcyst_b` DOUBLE,
    `bq_endometriosis_b` DOUBLE,
    `bq_uterine_fib_b` DOUBLE,
    `bq_trypreg_b` DOUBLE,
    `bq_urinatea_o` DOUBLE,
    `bq_infprosa_o` DOUBLE,
    `bq_hearta_f_b` DOUBLE,
    `bq_bronchit_f_b` DOUBLE,
    `bq_polyps_f_b` DOUBLE,
    `bq_ulcerative_colitits_b` DOUBLE,
    `bq_crohns_disease_b` DOUBLE,
    `bq_familial_polyposis_b` DOUBLE,
    `bq_hepatitis_b` DOUBLE,
    `bq_cirrhosis_b` DOUBLE,
    `bq_divertic_f_b` DOUBLE,
    `bq_gallblad_f_b` DOUBLE,
    `bq_age_co` DOUBLE,
    `bq_race7_ca` DOUBLE,
    `bq_hispanic_f_b` DOUBLE,
    `bq_surg_resection_b` DOUBLE,
    `bq_surg_prostatectomy_b` DOUBLE,
    `bq_hyster_f_b` DOUBLE,
    `bq_ovariesr_f_ca` DOUBLE,
    `bq_infpros_f_b` DOUBLE,
    `bq_urinate_f_o` DOUBLE,
    `bq_smoked_f_b` DOUBLE,
    `bq_smokea_f_co` DOUBLE,
    `bq_ssmokea_f_co` DOUBLE,
    `bq_cig_stop_co` DOUBLE,
    `bq_bmi_20_co` DOUBLE,
    `bq_bmi_50_co` DOUBLE,
    `bq_bmi_curr_co` DOUBLE,
    `bq_weight_f_co` DOUBLE,
    `bq_weight20_f_co` DOUBLE,
    `bq_weight50_f_co` DOUBLE,
    `bq_height_f_co` DOUBLE,
    `bq_fh_cancer_b` DOUBLE,
    `center` DOUBLE,
    `arm` DOUBLE,
    `sex` DOUBLE,
    `genetic_ancestry_platform` DOUBLE,
    `in_final_gsa_population` DOUBLE,
    `ancestry_admix_p_f` DOUBLE,
    `ancestry_admix_p_e` DOUBLE,
    `ancestry_admix_p_a` DOUBLE,
    `ancestry_genetic_distance1` DOUBLE,
    `ancestry_genetic_distance2` DOUBLE,
    `ancestry_genetic_distance3` DOUBLE,
    `ancestry_genetic_distance4` DOUBLE,
    `genetic_ancestry` DOUBLE,
    `genetic_ancestry_pca7` DOUBLE,
    `eu_pca_component1` DOUBLE,
    `eu_pca_component2` DOUBLE,
    `eu_pca_component3` DOUBLE,
    `eu_pca_component4` DOUBLE,
    `eu_pca_component5` DOUBLE,
    `eu_pca_component6` DOUBLE,
    `eu_pca_component7` DOUBLE,
    `eu_pca_component8` DOUBLE,
    `eu_pca_component9` DOUBLE,
    `eu_pca_component10` DOUBLE,
    `aa_pca_component1` DOUBLE,
    `aa_pca_component2` DOUBLE,
    `aa_pca_component3` DOUBLE,
    `aa_pca_component4` DOUBLE,
    `aa_pca_component5` DOUBLE,
    `aa_pca_component6` DOUBLE,
    `aa_pca_component7` DOUBLE,
    `aa_pca_component8` DOUBLE,
    `aa_pca_component9` DOUBLE,
    `aa_pca_component10` DOUBLE,
    `ea_pca_component1` DOUBLE,
    `ea_pca_component2` DOUBLE,
    `ea_pca_component3` DOUBLE,
    `ea_pca_component4` DOUBLE,
    `ea_pca_component5` DOUBLE,
    `ea_pca_component6` DOUBLE,
    `ea_pca_component7` DOUBLE,
    `ea_pca_component8` DOUBLE,
    `ea_pca_component9` DOUBLE,
    `ea_pca_component10` DOUBLE,
    `h2_pca_component1` DOUBLE,
    `h2_pca_component2` DOUBLE,
    `h2_pca_component3` DOUBLE,
    `h2_pca_component4` DOUBLE,
    `h2_pca_component5` DOUBLE,
    `h2_pca_component6` DOUBLE,
    `h2_pca_component7` DOUBLE,
    `h2_pca_component8` DOUBLE,
    `h2_pca_component9` DOUBLE,
    `h2_pca_component10` DOUBLE,
    `h1_pca_component1` DOUBLE,
    `h1_pca_component2` DOUBLE,
    `h1_pca_component3` DOUBLE,
    `h1_pca_component4` DOUBLE,
    `h1_pca_component5` DOUBLE,
    `h1_pca_component6` DOUBLE,
    `h1_pca_component7` DOUBLE,
    `h1_pca_component8` DOUBLE,
    `h1_pca_component9` DOUBLE,
    `h1_pca_component10` DOUBLE,
    `sa_pca_component1` DOUBLE,
    `sa_pca_component2` DOUBLE,
    `sa_pca_component3` DOUBLE,
    `sa_pca_component4` DOUBLE,
    `sa_pca_component5` DOUBLE,
    `sa_pca_component6` DOUBLE,
    `sa_pca_component7` DOUBLE,
    `sa_pca_component8` DOUBLE,
    `sa_pca_component9` DOUBLE,
    `sa_pca_component10` DOUBLE,
    `ot_pca_component1` DOUBLE,
    `ot_pca_component2` DOUBLE,
    `ot_pca_component3` DOUBLE,
    `ot_pca_component4` DOUBLE,
    `ot_pca_component5` DOUBLE,
    `ot_pca_component6` DOUBLE,
    `ot_pca_component7` DOUBLE,
    `ot_pca_component8` DOUBLE,
    `ot_pca_component9` DOUBLE,
    `ot_pca_component10` DOUBLE,
    `pca_components_platform` DOUBLE,
    `has_pca_components` DOUBLE,
    `genetic_ancestry_platform_study` DOUBLE,
    `dqx_age_co` DOUBLE,
    `dqx_qxn_physicact_40_o` DOUBLE,
    `dqx_qxn_physicact_now_o` DOUBLE,
    `sqx_age_co` DOUBLE,
    `sqx_sit_ht_o` DOUBLE,
    `sqx_waist_hip_o` DOUBLE,
    `sqx_height_co` DOUBLE,
    `sqx_wt30s_co` DOUBLE,
    `sqx_wt40s_co` DOUBLE,
    `sqx_wt50s_co` DOUBLE,
    `sqx_wt60s_co` DOUBLE,
    `sqx_wt70s_co` DOUBLE,
    `sqx_wt_curr_co` DOUBLE,
    `sqx_bmi30s_co` DOUBLE,
    `sqx_bmi40s_co` DOUBLE,
    `sqx_bmi50s_co` DOUBLE,
    `sqx_bmi60s_co` DOUBLE,
    `sqx_bmi70s_co` DOUBLE,
    `sqx_bmi_curr_co` DOUBLE,
    `sqx_cholesterol_b` DOUBLE,
    `sqx_asthma_b` DOUBLE,
    `sqxbq_hearta_b` DOUBLE,
    `sqxbq_stroke_b` DOUBLE,
    `sqxbq_hyperten_b` DOUBLE,
    `sqxbq_diabetes_b` DOUBLE,
    `sqxbq_osteopor_b` DOUBLE,
    `sqxbq_emphysema_b` DOUBLE,
    `sqxbq_arthritis_b` DOUBLE,
    `sqx_broke_hip_b` DOUBLE,
    `sqx_broke_arm_b` DOUBLE,
    `sqx_broke_vertebra_b` DOUBLE,
    `sqx_broke_none_b` DOUBLE,
    `sqx_balding_trend_o` DOUBLE,
    `sqx_urinate_o` DOUBLE,
    `sqxbq_bpha_o` DOUBLE,
    `sqxbq_bph_b` DOUBLE,
    `sqx_lift_weights_b` DOUBLE,
    `sqx_lift_weights_lev_o` DOUBLE,
    `sqx_active_b` DOUBLE,
    `sqx_fh_blad_b` DOUBLE,
    `sqx_fh_breast_b` DOUBLE,
    `sqx_fh_colo_b` DOUBLE,
    `sqx_fh_endo_b` DOUBLE,
    `sqx_fh_leuk_b` DOUBLE,
    `sqx_fh_lung_b` DOUBLE,
    `sqx_fh_lymph_b` DOUBLE,
    `sqx_fh_ovar_b` DOUBLE,
    `sqx_fh_pros_b` DOUBLE,
    `sqx_fh_cancer_f_b` DOUBLE,
    `sqx_twins_b` DOUBLE,
    `sqx_smk100_b` DOUBLE,
    `sqx_amt_smk_o` DOUBLE,
    `sqx_smk_crave1_b` DOUBLE,
    `sqx_smk_crave2_b` DOUBLE,
    `sqx_smk_crave3_b` DOUBLE,
    `sqx_smk_crave4_b` DOUBLE,
    `sqx_smk_try_quit_b` DOUBLE,
    `sqx_smk_age_quit_co` DOUBLE,
    `sqx_worry_lungca_o` DOUBLE,
    `sqx_risk_lungca_o` DOUBLE,
    `sqx_smk_his_co` DOUBLE,
    `sqx_smk_behv_co` DOUBLE,
    `sqx_smk_ftnd_co` DOUBLE,
    `sqx_years_quit_co` DOUBLE,
    `sqx_cig_years_co` DOUBLE,
    `sqx_gain_chest_shoulders_b` DOUBLE,
    `sqx_gain_waist_stomach_b` DOUBLE,
    `sqx_gain_hips_thighs_b` DOUBLE,
    `sqx_gain_equally_over_b` DOUBLE,
    `sqx_lose_chest_shoulders_b` DOUBLE,
    `sqx_lose_waist_stomach_b` DOUBLE,
    `sqx_lose_hips_thighs_b` DOUBLE,
    `sqx_lose_equally_over_b` DOUBLE,
    `sqxbq_rheumatoid_arthritis_b` DOUBLE,
    `sqxbq_osteoarthritis_b` DOUBLE,
    `sqx_moderate_week_co` DOUBLE,
    `sqx_strenuous_week_co` DOUBLE,
    `sqx_ever_balding_b` DOUBLE,
    `sqx_top_bald_b` DOUBLE,
    `bq_menstr_natural_o` DOUBLE,
    `sqx_current_cigarette_b` DOUBLE,
    `sqxbq_relapse_b` DOUBLE,
    `bq_current_cigarette_b` DOUBLE,
    `bq_cig_stat_o` DOUBLE,
    `bq_cig_years_co` DOUBLE,
    `bq_cigar_o` DOUBLE,
    `bq_cigpd_f_o` DOUBLE,
    `bq_filtered_f_b` DOUBLE,
    `bq_pack_years_co` DOUBLE,
    `bq_pipe_o` DOUBLE,
    `sqx_pace_o` DOUBLE,
    `sqx_stairs_o` DOUBLE,
    `sqx_walk_mi_o` DOUBLE,
    `pack_years_bqelsesqx_co` DOUBLE,
    `sqx_smk_exp_adult_o` DOUBLE,
    `sqx_smk_lgt_ca` DOUBLE,
    `sqx_smk_menthol_b` DOUBLE,
    `sqx_smk_plan_quit_o` DOUBLE,
    `sqx_smk_wake_o` DOUBLE,
    `sqx_smk30days_b` DOUBLE,
    `sqxo_cig_stat_o` DOUBLE,
    `sqx_urinatea_o` DOUBLE,
    `sv_coffee_reg_nosug_dhq` DOUBLE,
    `sv_coffee_decaf_nosug_dhq` DOUBLE,
    `mped_fruit_nojuice_dhq` DOUBLE,
    `dt_alc_alc_drinks_dhq` DOUBLE,
    `drinker_dhq` DOUBLE,
    `g_candy_choc_dhq` DOUBLE,
    `g_red5_dhq` DOUBLE,
    `g_process_6_dhq` DOUBLE,
    `g_fruit_dhq` DOUBLE,
    `g_vegetable_dhq` DOUBLE,
    `g_fish_total_dhq` DOUBLE,
    `g_salty_grain_snack_dhq` DOUBLE,
    `g_fruit_citrus_dhq` DOUBLE,
    `g_soda_reg_dhq` DOUBLE,
    `dt_kcal_dhq` DOUBLE,
    `dt_prot_dhq` DOUBLE,
    `dt_fat_dhq` DOUBLE,
    `dt_carb_dhq` DOUBLE,
    `dt_fiber_csfii_dhq` DOUBLE,
    `dt_caffeine_dhq` DOUBLE,
    `gly_load_dhq` DOUBLE,
    `mped_grain_dhq` DOUBLE,
    `mped_grain_whole_dhq` DOUBLE,
    `mped_veg_dark_green_dhq` DOUBLE,
    `mped_dairy_dhq` DOUBLE,
    `mped_dairy_milk_dhq` DOUBLE,
    `mped_m_soy_dhq` DOUBLE,
    `mped_m_nut_seed_dhq` DOUBLE,
    `mped_legume_dhq` DOUBLE,
    `mped_added_sugar_dhq` DOUBLE,
    `pe_fr_protein_dhq` DOUBLE,
    `pe_fr_fat_dhq` DOUBLE,
    `pe_fr_carb_dhq` DOUBLE,
    `pe_fr_alc_dhq` DOUBLE,
    `gly_index_dhq` DOUBLE,
    `dt_sugar_dhq` DOUBLE,
    `age_dhq` DOUBLE,
    `dhq_completedvalid` DOUBLE,
    `mped_alc_bev_alc_drinks18_dhq` DOUBLE,
    `mped_alc_bev_alc_drinks25_dhq` DOUBLE,
    `mped_alc_bev_alc_drinks40_dhq` DOUBLE,
    `mped_alc_bev_alc_drinks55_dhq` DOUBLE,
    `qxn_f_coffee_dhq` DOUBLE,
    `whfrden_dhq` DOUBLE,
    `grnden_dhq` DOUBLE,
    `wgrnden_dhq` DOUBLE,
    `dairyden_dhq` DOUBLE,
    `hei2005_total_score_dhq` DOUBLE,
    `hei2010_total_score_dhq` DOUBLE,
    `addsug_perc2015_dhq` DOUBLE,
    `hei2015_total_score_dhq` DOUBLE,
    `saltsnkden_g_dhq` DOUBLE,
    `milkden_dhq` DOUBLE,
    `frtden_g_dhq` DOUBLE,
    `citfrtden_g_dhq` DOUBLE,
    `vegtotden_g_dhq` DOUBLE,
    `dkgrvegden_dhq` DOUBLE,
    `legumeden_dhq` DOUBLE,
    `nutden_dhq` DOUBLE,
    `redmtden_g_dhq` DOUBLE,
    `procmtden_g_dhq` DOUBLE,
    `fishden_g_dhq` DOUBLE,
    `soyden_dhq` DOUBLE,
    `current_drinker` DOUBLE,
    `former_drinker` DOUBLE,
    `drinker_status_dhq_o` DOUBLE,
    `ph_status` DOUBLE,
    `first_psa_level` DOUBLE,
    `first_psa_year` DOUBLE,
    `first_ca125_level` DOUBLE,
    `first_ca125_year` DOUBLE,
    `adenoma_stat` DOUBLE,
    `adenoma_fup_age` DOUBLE,
    `adenoma_dx_age` DOUBLE,
    `advanced_adenoma_stat` DOUBLE,
    `advanced_adenoma_fup_age` DOUBLE,
    `advanced_adenoma_dx_age` DOUBLE,
    `non_advanced_adenoma_stat` DOUBLE,
    `non_advanced_adenoma_fup_age` DOUBLE,
    `non_advanced_adenoma_dx_age` DOUBLE
) ENGINE=MYISAM;

-- load data into staging table (gsa_qx_v7.na)
-- D:/Development/Work/nci-webtools-dceg-plco-atlas/database/import/raw
LOAD DATA LOCAL INFILE "../raw/participant_data.tsv" INTO TABLE participant_data_stage
    FIELDS TERMINATED BY '\t'
    IGNORE 1 ROWS (
        plco_id,
        @chf_cat,
        @ischemicheart_cat,
        @depression_cat,
        @diabetes_cat,
        @ra_oa_cat,
        @chronickidney_cat,
        @copd_cat,
        @atrial_fib_cat,
        @alzh_cat,
        @alzh_demen_cat,
        @any_use,
        @part_d_mosx,
        @chronic,
        @mos,
        @j_adeno_carcinoma,
        @j_adeno_carcinoma_fup_days,
        @j_adeno_carcinoma_fup_age,
        @j_adeno_carcinoma_dx_age,
        @j_alcohol_related_dx_age,
        @j_alcohol_related,
        @j_alcohol_related_fup_age,
        @j_alcohol_related_fup_days,
        @j_bcell,
        @j_bcell_fup_days,
        @j_bcell_fup_age,
        @j_bcell_dx_age,
        @j_bili_cancer,
        @j_bili_cancer_fup_days,
        @j_bili_cancer_fup_age,
        @j_bili_cancer_dx_age,
        @j_blad_cancer,
        @j_blad_cancer_fup_days,
        @j_blad_cancer_fup_age,
        @j_blad_cancer_dx_age,
        @j_breast_cancer,
        @j_breast_cancer_fup_days,
        @j_breast_cancer_fup_age,
        @j_breast_cancer_dx_age,
        @j_breast_invasive,
        @j_breast_insitu,
        @j_breast_ductal,
        @j_breast_lobular,
        @j_breast_tubular,
        @j_breast_er_pos_or_equiv,
        @j_breast_er_neg,
        @j_breast_pr_pos_or_equiv,
        @j_breast_pr_neg,
        @j_breast_er_or_pr_pos,
        @j_breast_er_and_pr_neg,
        @j_breast_her2_pos_or_equiv,
        @j_breast_her2_neg,
        @j_breast_er_pr_and_her2_neg,
        @j_breast_grade34,
        @j_breast_grade2,
        @j_breast_grade1,
        @j_carcinoma,
        @j_carcinoma_fup_days,
        @j_carcinoma_fup_age,
        @j_carcinoma_dx_age,
        @j_colo_cancer,
        @j_colo_cancer_fup_days,
        @j_colo_cancer_fup_age,
        @j_colo_cancer_dx_age,
        @j_colo_distal,
        @j_colo_distal_proximal,
        @j_colo_proximal,
        @j_colo_rectal,
        @j_diabetes_related_dx_age,
        @j_diabetes_related,
        @j_diabetes_related_fup_age,
        @j_diabetes_related_fup_days,
        @j_ebv_related_dx_age,
        @j_ebv_related,
        @j_ebv_related_fup_age,
        @j_ebv_related_fup_days,
        @j_endo_cancer,
        @j_endo_cancer_fup_days,
        @j_endo_cancer_fup_age,
        @j_endo_cancer_dx_age,
        @j_endo_neuro,
        @j_endo_neuro_fup_days,
        @j_endo_neuro_fup_age,
        @j_endo_neuro_dx_age,
        @j_esoph_cancer,
        @j_esoph_cancer_fup_days,
        @j_esoph_cancer_fup_age,
        @j_esoph_cancer_dx_age,
        @j_esoph_adeno_carcinoma,
        @j_esoph_squamous,
        @j_hbv_related_dx_age,
        @j_hbv_related,
        @j_hbv_related_fup_age,
        @j_hbv_related_fup_days,
        @j_hcv_related_dx_age,
        @j_hcv_related,
        @j_hcv_related_fup_age,
        @j_hcv_related_fup_days,
        @j_height_related_dx_age,
        @j_height_related,
        @j_height_related_fup_age,
        @j_height_related_fup_days,
        @j_helicobacter_related_dx_age,
        @j_helicobacter_related,
        @j_helicobacter_related_fup_age,
        @j_helicobacter_related_fup_days,
        @j_hematologic,
        @j_hematologic_fup_days,
        @j_hematologic_fup_age,
        @j_hematologic_dx_age,
        @j_hnc_cancer,
        @j_hnc_cancer_fup_days,
        @j_hnc_cancer_fup_age,
        @j_hnc_cancer_dx_age,
        @j_hnc_larynx,
        @j_hnc_lip_oral_pharynx,
        @j_hnc_naso_mid_sinus,
        @j_hpv_related_dx_age,
        @j_hpv_related,
        @j_hpv_related_fup_age,
        @j_hpv_related_fup_days,
        @j_infection_related_dx_age,
        @j_infection_related,
        @j_infection_related_fup_age,
        @j_infection_related_fup_days,
        @j_kidney_cancer_fup_days,
        @j_kidney_cancer_fup_age,
        @j_kidney_cancer_dx_age,
        @j_kidney_cancer,
        @j_kidney_renalcell_clearcell,
        @j_kidney_renalcell_nos,
        @j_gast_cancer,
        @j_gast_cancer_fup_days,
        @j_gast_cancer_fup_age,
        @j_gast_cancer_dx_age,
        @j_gast_cardia,
        @j_gast_noncardia,
        @j_glio_cancer,
        @j_glio_cancer_fup_days,
        @j_glio_cancer_fup_age,
        @j_glio_cancer_dx_age,
        @j_liver_xintra_cancer_fup_days,
        @j_liver_xintra_cancer_fup_age,
        @j_liver_xintra_cancer_dx_age,
        @j_liver_xintra_cancer,
        @j_lung_cancer,
        @j_lung_cancer_fup_days,
        @j_lung_cancer_fup_age,
        @j_lung_cancer_dx_age,
        @j_lung_smallcell,
        @j_lung_adeno,
        @j_lung_squam,
        @j_lymphoid,
        @j_lymphoid_fup_days,
        @j_lymphoid_fup_age,
        @j_lymphoid_dx_age,
        @j_cll,
        @j_cll_fup_days,
        @j_cll_fup_age,
        @j_cll_dx_age,
        @j_mbreast_cancer,
        @j_mbreast_cancer_fup_days,
        @j_mbreast_cancer_fup_age,
        @j_mbreast_cancer_dx_age,
        @j_mela_cancer,
        @j_mela_cancer_fup_days,
        @j_mela_cancer_fup_age,
        @j_mela_cancer_dx_age,
        @j_mela_invasive_cancer,
        @j_mela_invasive_cancer_fup_age,
        @j_mela_invasive_cancer_dx_age,
        @j_mela_invasive_cancer_fup_days,
        @j_mesoth,
        @j_mesoth_fup_days,
        @j_mesoth_fup_age,
        @j_mesoth_dx_age,
        @j_myeloid,
        @j_myeloid_fup_days,
        @j_myeloid_fup_age,
        @j_myeloid_dx_age,
        @j_obesity_related_dx_age,
        @j_obesity_related,
        @j_obesity_related_fup_age,
        @j_obesity_related_fup_days,
        @j_osumm_cancer,
        @j_osumm_cancer_fup_days,
        @j_osumm_cancer_fup_age,
        @j_osumm_cancer_dx_age,
        @j_osumm_serous_grade_high,
        @j_panc_cancer,
        @j_panc_cancer_fup_days,
        @j_panc_cancer_fup_age,
        @j_panc_cancer_dx_age,
        @j_phys_act_related_dx_age,
        @j_phys_act_related,
        @j_phys_act_related_fup_age,
        @j_phys_act_related_fup_days,
        @j_pros_cancer,
        @j_pros_cancer_fup_days,
        @j_pros_cancer_fup_age,
        @j_pros_cancer_dx_age,
        @j_pros_non_advanced,
        @j_pros_advanced_including7,
        @j_pros_advanced_excluding7,
        @j_sarcoma,
        @j_sarcoma_fup_days,
        @j_sarcoma_fup_age,
        @j_sarcoma_dx_age,
        @j_smoking_related_dx_age,
        @j_smoking_related,
        @j_smoking_related_fup_age,
        @j_smoking_related_fup_days,
        @j_solid_tumor,
        @j_solid_tumor_fup_days,
        @j_solid_tumor_fup_age,
        @j_solid_tumor_dx_age,
        @j_squamous,
        @j_squamous_fup_days,
        @j_squamous_fup_age,
        @j_squamous_dx_age,
        @j_thyd_cancer,
        @j_thyd_cancer_fup_days,
        @j_thyd_cancer_fup_age,
        @j_thyd_cancer_dx_age,
        @j_upgi_cancer,
        @j_upgi_cancer_fup_days,
        @j_upgi_cancer_fup_age,
        @j_upgi_cancer_dx_age,
        @j_urothelial,
        @j_urothelial_fup_days,
        @j_urothelial_fup_age,
        @j_urothelial_dx_age,
        @is_dead,
        @mortality_exitage,
        @dth_days,
        @mortality_exitdays_unadj,
        @f_death_ischemic,
        @f_death_cerebrovascular,
        @f_death_rheumatic,
        @f_death_hypertensive,
        @f_death_peripheral,
        @f_death_heart,
        @f_death_cardiac,
        @f_death_arrhythmia,
        @f_death_endocarditis,
        @f_death_cardiovascular,
        @f_death_cancer,
        @f_death_chronicresp,
        @f_death_alzheimers,
        @f_death_diabetes,
        @f_death_nephritis,
        @f_death_chronicliver,
        @f_death_parkinsons,
        @bq_educat_o,
        @bq_marital_co,
        @bq_fmenstr_o,
        @bq_tubal_o,
        @bq_bbd_b,
        @bq_benign_ovcyst_b,
        @bq_endometriosis_b,
        @bq_uterine_fib_b,
        @bq_trypreg_b,
        @bq_urinatea_o,
        @bq_infprosa_o,
        @bq_hearta_f_b,
        @bq_bronchit_f_b,
        @bq_polyps_f_b,
        @bq_ulcerative_colitits_b,
        @bq_crohns_disease_b,
        @bq_familial_polyposis_b,
        @bq_hepatitis_b,
        @bq_cirrhosis_b,
        @bq_divertic_f_b,
        @bq_gallblad_f_b,
        @bq_age_co,
        @bq_race7_ca,
        @bq_hispanic_f_b,
        @bq_surg_resection_b,
        @bq_surg_prostatectomy_b,
        @bq_hyster_f_b,
        @bq_ovariesr_f_ca,
        @bq_infpros_f_b,
        @bq_urinate_f_o,
        @bq_smoked_f_b,
        @bq_smokea_f_co,
        @bq_ssmokea_f_co,
        @bq_cig_stop_co,
        @bq_bmi_20_co,
        @bq_bmi_50_co,
        @bq_bmi_curr_co,
        @bq_weight_f_co,
        @bq_weight20_f_co,
        @bq_weight50_f_co,
        @bq_height_f_co,
        @bq_fh_cancer_b,
        @center,
        @arm,
        @sex,
        @genetic_ancestry_platform,
        @in_final_gsa_population,
        @ancestry_admix_p_f,
        @ancestry_admix_p_e,
        @ancestry_admix_p_a,
        @ancestry_genetic_distance1,
        @ancestry_genetic_distance2,
        @ancestry_genetic_distance3,
        @ancestry_genetic_distance4,
        @genetic_ancestry,
        @genetic_ancestry_pca7,
        @eu_pca_component1,
        @eu_pca_component2,
        @eu_pca_component3,
        @eu_pca_component4,
        @eu_pca_component5,
        @eu_pca_component6,
        @eu_pca_component7,
        @eu_pca_component8,
        @eu_pca_component9,
        @eu_pca_component10,
        @aa_pca_component1,
        @aa_pca_component2,
        @aa_pca_component3,
        @aa_pca_component4,
        @aa_pca_component5,
        @aa_pca_component6,
        @aa_pca_component7,
        @aa_pca_component8,
        @aa_pca_component9,
        @aa_pca_component10,
        @ea_pca_component1,
        @ea_pca_component2,
        @ea_pca_component3,
        @ea_pca_component4,
        @ea_pca_component5,
        @ea_pca_component6,
        @ea_pca_component7,
        @ea_pca_component8,
        @ea_pca_component9,
        @ea_pca_component10,
        @h2_pca_component1,
        @h2_pca_component2,
        @h2_pca_component3,
        @h2_pca_component4,
        @h2_pca_component5,
        @h2_pca_component6,
        @h2_pca_component7,
        @h2_pca_component8,
        @h2_pca_component9,
        @h2_pca_component10,
        @h1_pca_component1,
        @h1_pca_component2,
        @h1_pca_component3,
        @h1_pca_component4,
        @h1_pca_component5,
        @h1_pca_component6,
        @h1_pca_component7,
        @h1_pca_component8,
        @h1_pca_component9,
        @h1_pca_component10,
        @sa_pca_component1,
        @sa_pca_component2,
        @sa_pca_component3,
        @sa_pca_component4,
        @sa_pca_component5,
        @sa_pca_component6,
        @sa_pca_component7,
        @sa_pca_component8,
        @sa_pca_component9,
        @sa_pca_component10,
        @ot_pca_component1,
        @ot_pca_component2,
        @ot_pca_component3,
        @ot_pca_component4,
        @ot_pca_component5,
        @ot_pca_component6,
        @ot_pca_component7,
        @ot_pca_component8,
        @ot_pca_component9,
        @ot_pca_component10,
        @pca_components_platform,
        @has_pca_components,
        @genetic_ancestry_platform_study,
        @dqx_age_co,
        @dqx_qxn_physicact_40_o,
        @dqx_qxn_physicact_now_o,
        @sqx_age_co,
        @sqx_sit_ht_o,
        @sqx_waist_hip_o,
        @sqx_height_co,
        @sqx_wt30s_co,
        @sqx_wt40s_co,
        @sqx_wt50s_co,
        @sqx_wt60s_co,
        @sqx_wt70s_co,
        @sqx_wt_curr_co,
        @sqx_bmi30s_co,
        @sqx_bmi40s_co,
        @sqx_bmi50s_co,
        @sqx_bmi60s_co,
        @sqx_bmi70s_co,
        @sqx_bmi_curr_co,
        @sqx_cholesterol_b,
        @sqx_asthma_b,
        @sqxbq_hearta_b,
        @sqxbq_stroke_b,
        @sqxbq_hyperten_b,
        @sqxbq_diabetes_b,
        @sqxbq_osteopor_b,
        @sqxbq_emphysema_b,
        @sqxbq_arthritis_b,
        @sqx_broke_hip_b,
        @sqx_broke_arm_b,
        @sqx_broke_vertebra_b,
        @sqx_broke_none_b,
        @sqx_balding_trend_o,
        @sqx_urinate_o,
        @sqxbq_bpha_o,
        @sqxbq_bph_b,
        @sqx_lift_weights_b,
        @sqx_lift_weights_lev_o,
        @sqx_active_b,
        @sqx_fh_blad_b,
        @sqx_fh_breast_b,
        @sqx_fh_colo_b,
        @sqx_fh_endo_b,
        @sqx_fh_leuk_b,
        @sqx_fh_lung_b,
        @sqx_fh_lymph_b,
        @sqx_fh_ovar_b,
        @sqx_fh_pros_b,
        @sqx_fh_cancer_f_b,
        @sqx_twins_b,
        @sqx_smk100_b,
        @sqx_amt_smk_o,
        @sqx_smk_crave1_b,
        @sqx_smk_crave2_b,
        @sqx_smk_crave3_b,
        @sqx_smk_crave4_b,
        @sqx_smk_try_quit_b,
        @sqx_smk_age_quit_co,
        @sqx_worry_lungca_o,
        @sqx_risk_lungca_o,
        @sqx_smk_his_co,
        @sqx_smk_behv_co,
        @sqx_smk_ftnd_co,
        @sqx_years_quit_co,
        @sqx_cig_years_co,
        @sqx_gain_chest_shoulders_b,
        @sqx_gain_waist_stomach_b,
        @sqx_gain_hips_thighs_b,
        @sqx_gain_equally_over_b,
        @sqx_lose_chest_shoulders_b,
        @sqx_lose_waist_stomach_b,
        @sqx_lose_hips_thighs_b,
        @sqx_lose_equally_over_b,
        @sqxbq_rheumatoid_arthritis_b,
        @sqxbq_osteoarthritis_b,
        @sqx_moderate_week_co,
        @sqx_strenuous_week_co,
        @sqx_ever_balding_b,
        @sqx_top_bald_b,
        @bq_menstr_natural_o,
        @sqx_current_cigarette_b,
        @sqxbq_relapse_b,
        @bq_current_cigarette_b,
        @bq_cig_stat_o,
        @bq_cig_years_co,
        @bq_cigar_o,
        @bq_cigpd_f_o,
        @bq_filtered_f_b,
        @bq_pack_years_co,
        @bq_pipe_o,
        @sqx_pace_o,
        @sqx_stairs_o,
        @sqx_walk_mi_o,
        @pack_years_bqelsesqx_co,
        @sqx_smk_exp_adult_o,
        @sqx_smk_lgt_ca,
        @sqx_smk_menthol_b,
        @sqx_smk_plan_quit_o,
        @sqx_smk_wake_o,
        @sqx_smk30days_b,
        @sqxo_cig_stat_o,
        @sqx_urinatea_o,
        @sv_coffee_reg_nosug_dhq,
        @sv_coffee_decaf_nosug_dhq,
        @mped_fruit_nojuice_dhq,
        @dt_alc_alc_drinks_dhq,
        @drinker_dhq,
        @g_candy_choc_dhq,
        @g_red5_dhq,
        @g_process_6_dhq,
        @g_fruit_dhq,
        @g_vegetable_dhq,
        @g_fish_total_dhq,
        @g_salty_grain_snack_dhq,
        @g_fruit_citrus_dhq,
        @g_soda_reg_dhq,
        @dt_kcal_dhq,
        @dt_prot_dhq,
        @dt_fat_dhq,
        @dt_carb_dhq,
        @dt_fiber_csfii_dhq,
        @dt_caffeine_dhq,
        @gly_load_dhq,
        @mped_grain_dhq,
        @mped_grain_whole_dhq,
        @mped_veg_dark_green_dhq,
        @mped_dairy_dhq,
        @mped_dairy_milk_dhq,
        @mped_m_soy_dhq,
        @mped_m_nut_seed_dhq,
        @mped_legume_dhq,
        @mped_added_sugar_dhq,
        @pe_fr_protein_dhq,
        @pe_fr_fat_dhq,
        @pe_fr_carb_dhq,
        @pe_fr_alc_dhq,
        @gly_index_dhq,
        @dt_sugar_dhq,
        @age_dhq,
        @dhq_completedvalid,
        @mped_alc_bev_alc_drinks18_dhq,
        @mped_alc_bev_alc_drinks25_dhq,
        @mped_alc_bev_alc_drinks40_dhq,
        @mped_alc_bev_alc_drinks55_dhq,
        @qxn_f_coffee_dhq,
        @whfrden_dhq,
        @grnden_dhq,
        @wgrnden_dhq,
        @dairyden_dhq,
        @hei2005_total_score_dhq,
        @hei2010_total_score_dhq,
        @addsug_perc2015_dhq,
        @hei2015_total_score_dhq,
        @saltsnkden_g_dhq,
        @milkden_dhq,
        @frtden_g_dhq,
        @citfrtden_g_dhq,
        @vegtotden_g_dhq,
        @dkgrvegden_dhq,
        @legumeden_dhq,
        @nutden_dhq,
        @redmtden_g_dhq,
        @procmtden_g_dhq,
        @fishden_g_dhq,
        @soyden_dhq,
        @current_drinker,
        @former_drinker,
        @drinker_status_dhq_o,
        @ph_status,
        @first_psa_level,
        @first_psa_year,
        @first_ca125_level,
        @first_ca125_year,
        @adenoma_stat,
        @adenoma_fup_age,
        @adenoma_dx_age,
        @advanced_adenoma_stat,
        @advanced_adenoma_fup_age,
        @advanced_adenoma_dx_age,
        @non_advanced_adenoma_stat,
        @non_advanced_adenoma_fup_age,
        @non_advanced_adenoma_dx_age
    ) SET
        plco_id = IF(@plco_id IN('NA', ''), NULL, @plco_id),
        chf_cat = IF(@chf_cat IN('NA', ''), NULL, @chf_cat),
        ischemicheart_cat = IF(@ischemicheart_cat IN('NA', ''), NULL, @ischemicheart_cat),
        depression_cat = IF(@depression_cat IN('NA', ''), NULL, @depression_cat),
        diabetes_cat = IF(@diabetes_cat IN('NA', ''), NULL, @diabetes_cat),
        ra_oa_cat = IF(@ra_oa_cat IN('NA', ''), NULL, @ra_oa_cat),
        chronickidney_cat = IF(@chronickidney_cat IN('NA', ''), NULL, @chronickidney_cat),
        copd_cat = IF(@copd_cat IN('NA', ''), NULL, @copd_cat),
        atrial_fib_cat = IF(@atrial_fib_cat IN('NA', ''), NULL, @atrial_fib_cat),
        alzh_cat = IF(@alzh_cat IN('NA', ''), NULL, @alzh_cat),
        alzh_demen_cat = IF(@alzh_demen_cat IN('NA', ''), NULL, @alzh_demen_cat),
        any_use = IF(@any_use IN('NA', ''), NULL, @any_use),
        part_d_mosx = IF(@part_d_mosx IN('NA', ''), NULL, @part_d_mosx),
        chronic = IF(@chronic IN('NA', ''), NULL, @chronic),
        mos = IF(@mos IN('NA', ''), NULL, @mos),
        j_adeno_carcinoma = IF(@j_adeno_carcinoma IN('NA', ''), NULL, @j_adeno_carcinoma),
        j_adeno_carcinoma_fup_days = IF(@j_adeno_carcinoma_fup_days IN('NA', ''), NULL, @j_adeno_carcinoma_fup_days),
        j_adeno_carcinoma_fup_age = IF(@j_adeno_carcinoma_fup_age IN('NA', ''), NULL, @j_adeno_carcinoma_fup_age),
        j_adeno_carcinoma_dx_age = IF(@j_adeno_carcinoma_dx_age IN('NA', ''), NULL, @j_adeno_carcinoma_dx_age),
        j_alcohol_related_dx_age = IF(@j_alcohol_related_dx_age IN('NA', ''), NULL, @j_alcohol_related_dx_age),
        j_alcohol_related = IF(@j_alcohol_related IN('NA', ''), NULL, @j_alcohol_related),
        j_alcohol_related_fup_age = IF(@j_alcohol_related_fup_age IN('NA', ''), NULL, @j_alcohol_related_fup_age),
        j_alcohol_related_fup_days = IF(@j_alcohol_related_fup_days IN('NA', ''), NULL, @j_alcohol_related_fup_days),
        j_bcell = IF(@j_bcell IN('NA', ''), NULL, @j_bcell),
        j_bcell_fup_days = IF(@j_bcell_fup_days IN('NA', ''), NULL, @j_bcell_fup_days),
        j_bcell_fup_age = IF(@j_bcell_fup_age IN('NA', ''), NULL, @j_bcell_fup_age),
        j_bcell_dx_age = IF(@j_bcell_dx_age IN('NA', ''), NULL, @j_bcell_dx_age),
        j_bili_cancer = IF(@j_bili_cancer IN('NA', ''), NULL, @j_bili_cancer),
        j_bili_cancer_fup_days = IF(@j_bili_cancer_fup_days IN('NA', ''), NULL, @j_bili_cancer_fup_days),
        j_bili_cancer_fup_age = IF(@j_bili_cancer_fup_age IN('NA', ''), NULL, @j_bili_cancer_fup_age),
        j_bili_cancer_dx_age = IF(@j_bili_cancer_dx_age IN('NA', ''), NULL, @j_bili_cancer_dx_age),
        j_blad_cancer = IF(@j_blad_cancer IN('NA', ''), NULL, @j_blad_cancer),
        j_blad_cancer_fup_days = IF(@j_blad_cancer_fup_days IN('NA', ''), NULL, @j_blad_cancer_fup_days),
        j_blad_cancer_fup_age = IF(@j_blad_cancer_fup_age IN('NA', ''), NULL, @j_blad_cancer_fup_age),
        j_blad_cancer_dx_age = IF(@j_blad_cancer_dx_age IN('NA', ''), NULL, @j_blad_cancer_dx_age),
        j_breast_cancer = IF(@j_breast_cancer IN('NA', ''), NULL, @j_breast_cancer),
        j_breast_cancer_fup_days = IF(@j_breast_cancer_fup_days IN('NA', ''), NULL, @j_breast_cancer_fup_days),
        j_breast_cancer_fup_age = IF(@j_breast_cancer_fup_age IN('NA', ''), NULL, @j_breast_cancer_fup_age),
        j_breast_cancer_dx_age = IF(@j_breast_cancer_dx_age IN('NA', ''), NULL, @j_breast_cancer_dx_age),
        j_breast_invasive = IF(@j_breast_invasive IN('NA', ''), NULL, @j_breast_invasive),
        j_breast_insitu = IF(@j_breast_insitu IN('NA', ''), NULL, @j_breast_insitu),
        j_breast_ductal = IF(@j_breast_ductal IN('NA', ''), NULL, @j_breast_ductal),
        j_breast_lobular = IF(@j_breast_lobular IN('NA', ''), NULL, @j_breast_lobular),
        j_breast_tubular = IF(@j_breast_tubular IN('NA', ''), NULL, @j_breast_tubular),
        j_breast_er_pos_or_equiv = IF(@j_breast_er_pos_or_equiv IN('NA', ''), NULL, @j_breast_er_pos_or_equiv),
        j_breast_er_neg = IF(@j_breast_er_neg IN('NA', ''), NULL, @j_breast_er_neg),
        j_breast_pr_pos_or_equiv = IF(@j_breast_pr_pos_or_equiv IN('NA', ''), NULL, @j_breast_pr_pos_or_equiv),
        j_breast_pr_neg = IF(@j_breast_pr_neg IN('NA', ''), NULL, @j_breast_pr_neg),
        j_breast_er_or_pr_pos = IF(@j_breast_er_or_pr_pos IN('NA', ''), NULL, @j_breast_er_or_pr_pos),
        j_breast_er_and_pr_neg = IF(@j_breast_er_and_pr_neg IN('NA', ''), NULL, @j_breast_er_and_pr_neg),
        j_breast_her2_pos_or_equiv = IF(@j_breast_her2_pos_or_equiv IN('NA', ''), NULL, @j_breast_her2_pos_or_equiv),
        j_breast_her2_neg = IF(@j_breast_her2_neg IN('NA', ''), NULL, @j_breast_her2_neg),
        j_breast_er_pr_and_her2_neg = IF(@j_breast_er_pr_and_her2_neg IN('NA', ''), NULL, @j_breast_er_pr_and_her2_neg),
        j_breast_grade34 = IF(@j_breast_grade34 IN('NA', ''), NULL, @j_breast_grade34),
        j_breast_grade2 = IF(@j_breast_grade2 IN('NA', ''), NULL, @j_breast_grade2),
        j_breast_grade1 = IF(@j_breast_grade1 IN('NA', ''), NULL, @j_breast_grade1),
        j_carcinoma = IF(@j_carcinoma IN('NA', ''), NULL, @j_carcinoma),
        j_carcinoma_fup_days = IF(@j_carcinoma_fup_days IN('NA', ''), NULL, @j_carcinoma_fup_days),
        j_carcinoma_fup_age = IF(@j_carcinoma_fup_age IN('NA', ''), NULL, @j_carcinoma_fup_age),
        j_carcinoma_dx_age = IF(@j_carcinoma_dx_age IN('NA', ''), NULL, @j_carcinoma_dx_age),
        j_colo_cancer = IF(@j_colo_cancer IN('NA', ''), NULL, @j_colo_cancer),
        j_colo_cancer_fup_days = IF(@j_colo_cancer_fup_days IN('NA', ''), NULL, @j_colo_cancer_fup_days),
        j_colo_cancer_fup_age = IF(@j_colo_cancer_fup_age IN('NA', ''), NULL, @j_colo_cancer_fup_age),
        j_colo_cancer_dx_age = IF(@j_colo_cancer_dx_age IN('NA', ''), NULL, @j_colo_cancer_dx_age),
        j_colo_distal = IF(@j_colo_distal IN('NA', ''), NULL, @j_colo_distal),
        j_colo_distal_proximal = IF(@j_colo_distal_proximal IN('NA', ''), NULL, @j_colo_distal_proximal),
        j_colo_proximal = IF(@j_colo_proximal IN('NA', ''), NULL, @j_colo_proximal),
        j_colo_rectal = IF(@j_colo_rectal IN('NA', ''), NULL, @j_colo_rectal),
        j_diabetes_related_dx_age = IF(@j_diabetes_related_dx_age IN('NA', ''), NULL, @j_diabetes_related_dx_age),
        j_diabetes_related = IF(@j_diabetes_related IN('NA', ''), NULL, @j_diabetes_related),
        j_diabetes_related_fup_age = IF(@j_diabetes_related_fup_age IN('NA', ''), NULL, @j_diabetes_related_fup_age),
        j_diabetes_related_fup_days = IF(@j_diabetes_related_fup_days IN('NA', ''), NULL, @j_diabetes_related_fup_days),
        j_ebv_related_dx_age = IF(@j_ebv_related_dx_age IN('NA', ''), NULL, @j_ebv_related_dx_age),
        j_ebv_related = IF(@j_ebv_related IN('NA', ''), NULL, @j_ebv_related),
        j_ebv_related_fup_age = IF(@j_ebv_related_fup_age IN('NA', ''), NULL, @j_ebv_related_fup_age),
        j_ebv_related_fup_days = IF(@j_ebv_related_fup_days IN('NA', ''), NULL, @j_ebv_related_fup_days),
        j_endo_cancer = IF(@j_endo_cancer IN('NA', ''), NULL, @j_endo_cancer),
        j_endo_cancer_fup_days = IF(@j_endo_cancer_fup_days IN('NA', ''), NULL, @j_endo_cancer_fup_days),
        j_endo_cancer_fup_age = IF(@j_endo_cancer_fup_age IN('NA', ''), NULL, @j_endo_cancer_fup_age),
        j_endo_cancer_dx_age = IF(@j_endo_cancer_dx_age IN('NA', ''), NULL, @j_endo_cancer_dx_age),
        j_endo_neuro = IF(@j_endo_neuro IN('NA', ''), NULL, @j_endo_neuro),
        j_endo_neuro_fup_days = IF(@j_endo_neuro_fup_days IN('NA', ''), NULL, @j_endo_neuro_fup_days),
        j_endo_neuro_fup_age = IF(@j_endo_neuro_fup_age IN('NA', ''), NULL, @j_endo_neuro_fup_age),
        j_endo_neuro_dx_age = IF(@j_endo_neuro_dx_age IN('NA', ''), NULL, @j_endo_neuro_dx_age),
        j_esoph_cancer = IF(@j_esoph_cancer IN('NA', ''), NULL, @j_esoph_cancer),
        j_esoph_cancer_fup_days = IF(@j_esoph_cancer_fup_days IN('NA', ''), NULL, @j_esoph_cancer_fup_days),
        j_esoph_cancer_fup_age = IF(@j_esoph_cancer_fup_age IN('NA', ''), NULL, @j_esoph_cancer_fup_age),
        j_esoph_cancer_dx_age = IF(@j_esoph_cancer_dx_age IN('NA', ''), NULL, @j_esoph_cancer_dx_age),
        j_esoph_adeno_carcinoma = IF(@j_esoph_adeno_carcinoma IN('NA', ''), NULL, @j_esoph_adeno_carcinoma),
        j_esoph_squamous = IF(@j_esoph_squamous IN('NA', ''), NULL, @j_esoph_squamous),
        j_hbv_related_dx_age = IF(@j_hbv_related_dx_age IN('NA', ''), NULL, @j_hbv_related_dx_age),
        j_hbv_related = IF(@j_hbv_related IN('NA', ''), NULL, @j_hbv_related),
        j_hbv_related_fup_age = IF(@j_hbv_related_fup_age IN('NA', ''), NULL, @j_hbv_related_fup_age),
        j_hbv_related_fup_days = IF(@j_hbv_related_fup_days IN('NA', ''), NULL, @j_hbv_related_fup_days),
        j_hcv_related_dx_age = IF(@j_hcv_related_dx_age IN('NA', ''), NULL, @j_hcv_related_dx_age),
        j_hcv_related = IF(@j_hcv_related IN('NA', ''), NULL, @j_hcv_related),
        j_hcv_related_fup_age = IF(@j_hcv_related_fup_age IN('NA', ''), NULL, @j_hcv_related_fup_age),
        j_hcv_related_fup_days = IF(@j_hcv_related_fup_days IN('NA', ''), NULL, @j_hcv_related_fup_days),
        j_height_related_dx_age = IF(@j_height_related_dx_age IN('NA', ''), NULL, @j_height_related_dx_age),
        j_height_related = IF(@j_height_related IN('NA', ''), NULL, @j_height_related),
        j_height_related_fup_age = IF(@j_height_related_fup_age IN('NA', ''), NULL, @j_height_related_fup_age),
        j_height_related_fup_days = IF(@j_height_related_fup_days IN('NA', ''), NULL, @j_height_related_fup_days),
        j_helicobacter_related_dx_age = IF(@j_helicobacter_related_dx_age IN('NA', ''), NULL, @j_helicobacter_related_dx_age),
        j_helicobacter_related = IF(@j_helicobacter_related IN('NA', ''), NULL, @j_helicobacter_related),
        j_helicobacter_related_fup_age = IF(@j_helicobacter_related_fup_age IN('NA', ''), NULL, @j_helicobacter_related_fup_age),
        j_helicobacter_related_fup_days = IF(@j_helicobacter_related_fup_days IN('NA', ''), NULL, @j_helicobacter_related_fup_days),
        j_hematologic = IF(@j_hematologic IN('NA', ''), NULL, @j_hematologic),
        j_hematologic_fup_days = IF(@j_hematologic_fup_days IN('NA', ''), NULL, @j_hematologic_fup_days),
        j_hematologic_fup_age = IF(@j_hematologic_fup_age IN('NA', ''), NULL, @j_hematologic_fup_age),
        j_hematologic_dx_age = IF(@j_hematologic_dx_age IN('NA', ''), NULL, @j_hematologic_dx_age),
        j_hnc_cancer = IF(@j_hnc_cancer IN('NA', ''), NULL, @j_hnc_cancer),
        j_hnc_cancer_fup_days = IF(@j_hnc_cancer_fup_days IN('NA', ''), NULL, @j_hnc_cancer_fup_days),
        j_hnc_cancer_fup_age = IF(@j_hnc_cancer_fup_age IN('NA', ''), NULL, @j_hnc_cancer_fup_age),
        j_hnc_cancer_dx_age = IF(@j_hnc_cancer_dx_age IN('NA', ''), NULL, @j_hnc_cancer_dx_age),
        j_hnc_larynx = IF(@j_hnc_larynx IN('NA', ''), NULL, @j_hnc_larynx),
        j_hnc_lip_oral_pharynx = IF(@j_hnc_lip_oral_pharynx IN('NA', ''), NULL, @j_hnc_lip_oral_pharynx),
        j_hnc_naso_mid_sinus = IF(@j_hnc_naso_mid_sinus IN('NA', ''), NULL, @j_hnc_naso_mid_sinus),
        j_hpv_related_dx_age = IF(@j_hpv_related_dx_age IN('NA', ''), NULL, @j_hpv_related_dx_age),
        j_hpv_related = IF(@j_hpv_related IN('NA', ''), NULL, @j_hpv_related),
        j_hpv_related_fup_age = IF(@j_hpv_related_fup_age IN('NA', ''), NULL, @j_hpv_related_fup_age),
        j_hpv_related_fup_days = IF(@j_hpv_related_fup_days IN('NA', ''), NULL, @j_hpv_related_fup_days),
        j_infection_related_dx_age = IF(@j_infection_related_dx_age IN('NA', ''), NULL, @j_infection_related_dx_age),
        j_infection_related = IF(@j_infection_related IN('NA', ''), NULL, @j_infection_related),
        j_infection_related_fup_age = IF(@j_infection_related_fup_age IN('NA', ''), NULL, @j_infection_related_fup_age),
        j_infection_related_fup_days = IF(@j_infection_related_fup_days IN('NA', ''), NULL, @j_infection_related_fup_days),
        j_kidney_cancer_fup_days = IF(@j_kidney_cancer_fup_days IN('NA', ''), NULL, @j_kidney_cancer_fup_days),
        j_kidney_cancer_fup_age = IF(@j_kidney_cancer_fup_age IN('NA', ''), NULL, @j_kidney_cancer_fup_age),
        j_kidney_cancer_dx_age = IF(@j_kidney_cancer_dx_age IN('NA', ''), NULL, @j_kidney_cancer_dx_age),
        j_kidney_cancer = IF(@j_kidney_cancer IN('NA', ''), NULL, @j_kidney_cancer),
        j_kidney_renalcell_clearcell = IF(@j_kidney_renalcell_clearcell IN('NA', ''), NULL, @j_kidney_renalcell_clearcell),
        j_kidney_renalcell_nos = IF(@j_kidney_renalcell_nos IN('NA', ''), NULL, @j_kidney_renalcell_nos),
        j_gast_cancer = IF(@j_gast_cancer IN('NA', ''), NULL, @j_gast_cancer),
        j_gast_cancer_fup_days = IF(@j_gast_cancer_fup_days IN('NA', ''), NULL, @j_gast_cancer_fup_days),
        j_gast_cancer_fup_age = IF(@j_gast_cancer_fup_age IN('NA', ''), NULL, @j_gast_cancer_fup_age),
        j_gast_cancer_dx_age = IF(@j_gast_cancer_dx_age IN('NA', ''), NULL, @j_gast_cancer_dx_age),
        j_gast_cardia = IF(@j_gast_cardia IN('NA', ''), NULL, @j_gast_cardia),
        j_gast_noncardia = IF(@j_gast_noncardia IN('NA', ''), NULL, @j_gast_noncardia),
        j_glio_cancer = IF(@j_glio_cancer IN('NA', ''), NULL, @j_glio_cancer),
        j_glio_cancer_fup_days = IF(@j_glio_cancer_fup_days IN('NA', ''), NULL, @j_glio_cancer_fup_days),
        j_glio_cancer_fup_age = IF(@j_glio_cancer_fup_age IN('NA', ''), NULL, @j_glio_cancer_fup_age),
        j_glio_cancer_dx_age = IF(@j_glio_cancer_dx_age IN('NA', ''), NULL, @j_glio_cancer_dx_age),
        j_liver_xintra_cancer_fup_days = IF(@j_liver_xintra_cancer_fup_days IN('NA', ''), NULL, @j_liver_xintra_cancer_fup_days),
        j_liver_xintra_cancer_fup_age = IF(@j_liver_xintra_cancer_fup_age IN('NA', ''), NULL, @j_liver_xintra_cancer_fup_age),
        j_liver_xintra_cancer_dx_age = IF(@j_liver_xintra_cancer_dx_age IN('NA', ''), NULL, @j_liver_xintra_cancer_dx_age),
        j_liver_xintra_cancer = IF(@j_liver_xintra_cancer IN('NA', ''), NULL, @j_liver_xintra_cancer),
        j_lung_cancer = IF(@j_lung_cancer IN('NA', ''), NULL, @j_lung_cancer),
        j_lung_cancer_fup_days = IF(@j_lung_cancer_fup_days IN('NA', ''), NULL, @j_lung_cancer_fup_days),
        j_lung_cancer_fup_age = IF(@j_lung_cancer_fup_age IN('NA', ''), NULL, @j_lung_cancer_fup_age),
        j_lung_cancer_dx_age = IF(@j_lung_cancer_dx_age IN('NA', ''), NULL, @j_lung_cancer_dx_age),
        j_lung_smallcell = IF(@j_lung_smallcell IN('NA', ''), NULL, @j_lung_smallcell),
        j_lung_adeno = IF(@j_lung_adeno IN('NA', ''), NULL, @j_lung_adeno),
        j_lung_squam = IF(@j_lung_squam IN('NA', ''), NULL, @j_lung_squam),
        j_lymphoid = IF(@j_lymphoid IN('NA', ''), NULL, @j_lymphoid),
        j_lymphoid_fup_days = IF(@j_lymphoid_fup_days IN('NA', ''), NULL, @j_lymphoid_fup_days),
        j_lymphoid_fup_age = IF(@j_lymphoid_fup_age IN('NA', ''), NULL, @j_lymphoid_fup_age),
        j_lymphoid_dx_age = IF(@j_lymphoid_dx_age IN('NA', ''), NULL, @j_lymphoid_dx_age),
        j_cll = IF(@j_cll IN('NA', ''), NULL, @j_cll),
        j_cll_fup_days = IF(@j_cll_fup_days IN('NA', ''), NULL, @j_cll_fup_days),
        j_cll_fup_age = IF(@j_cll_fup_age IN('NA', ''), NULL, @j_cll_fup_age),
        j_cll_dx_age = IF(@j_cll_dx_age IN('NA', ''), NULL, @j_cll_dx_age),
        j_mbreast_cancer = IF(@j_mbreast_cancer IN('NA', ''), NULL, @j_mbreast_cancer),
        j_mbreast_cancer_fup_days = IF(@j_mbreast_cancer_fup_days IN('NA', ''), NULL, @j_mbreast_cancer_fup_days),
        j_mbreast_cancer_fup_age = IF(@j_mbreast_cancer_fup_age IN('NA', ''), NULL, @j_mbreast_cancer_fup_age),
        j_mbreast_cancer_dx_age = IF(@j_mbreast_cancer_dx_age IN('NA', ''), NULL, @j_mbreast_cancer_dx_age),
        j_mela_cancer = IF(@j_mela_cancer IN('NA', ''), NULL, @j_mela_cancer),
        j_mela_cancer_fup_days = IF(@j_mela_cancer_fup_days IN('NA', ''), NULL, @j_mela_cancer_fup_days),
        j_mela_cancer_fup_age = IF(@j_mela_cancer_fup_age IN('NA', ''), NULL, @j_mela_cancer_fup_age),
        j_mela_cancer_dx_age = IF(@j_mela_cancer_dx_age IN('NA', ''), NULL, @j_mela_cancer_dx_age),
        j_mela_invasive_cancer = IF(@j_mela_invasive_cancer IN('NA', ''), NULL, @j_mela_invasive_cancer),
        j_mela_invasive_cancer_fup_age = IF(@j_mela_invasive_cancer_fup_age IN('NA', ''), NULL, @j_mela_invasive_cancer_fup_age),
        j_mela_invasive_cancer_dx_age = IF(@j_mela_invasive_cancer_dx_age IN('NA', ''), NULL, @j_mela_invasive_cancer_dx_age),
        j_mela_invasive_cancer_fup_days = IF(@j_mela_invasive_cancer_fup_days IN('NA', ''), NULL, @j_mela_invasive_cancer_fup_days),
        j_mesoth = IF(@j_mesoth IN('NA', ''), NULL, @j_mesoth),
        j_mesoth_fup_days = IF(@j_mesoth_fup_days IN('NA', ''), NULL, @j_mesoth_fup_days),
        j_mesoth_fup_age = IF(@j_mesoth_fup_age IN('NA', ''), NULL, @j_mesoth_fup_age),
        j_mesoth_dx_age = IF(@j_mesoth_dx_age IN('NA', ''), NULL, @j_mesoth_dx_age),
        j_myeloid = IF(@j_myeloid IN('NA', ''), NULL, @j_myeloid),
        j_myeloid_fup_days = IF(@j_myeloid_fup_days IN('NA', ''), NULL, @j_myeloid_fup_days),
        j_myeloid_fup_age = IF(@j_myeloid_fup_age IN('NA', ''), NULL, @j_myeloid_fup_age),
        j_myeloid_dx_age = IF(@j_myeloid_dx_age IN('NA', ''), NULL, @j_myeloid_dx_age),
        j_obesity_related_dx_age = IF(@j_obesity_related_dx_age IN('NA', ''), NULL, @j_obesity_related_dx_age),
        j_obesity_related = IF(@j_obesity_related IN('NA', ''), NULL, @j_obesity_related),
        j_obesity_related_fup_age = IF(@j_obesity_related_fup_age IN('NA', ''), NULL, @j_obesity_related_fup_age),
        j_obesity_related_fup_days = IF(@j_obesity_related_fup_days IN('NA', ''), NULL, @j_obesity_related_fup_days),
        j_osumm_cancer = IF(@j_osumm_cancer IN('NA', ''), NULL, @j_osumm_cancer),
        j_osumm_cancer_fup_days = IF(@j_osumm_cancer_fup_days IN('NA', ''), NULL, @j_osumm_cancer_fup_days),
        j_osumm_cancer_fup_age = IF(@j_osumm_cancer_fup_age IN('NA', ''), NULL, @j_osumm_cancer_fup_age),
        j_osumm_cancer_dx_age = IF(@j_osumm_cancer_dx_age IN('NA', ''), NULL, @j_osumm_cancer_dx_age),
        j_osumm_serous_grade_high = IF(@j_osumm_serous_grade_high IN('NA', ''), NULL, @j_osumm_serous_grade_high),
        j_panc_cancer = IF(@j_panc_cancer IN('NA', ''), NULL, @j_panc_cancer),
        j_panc_cancer_fup_days = IF(@j_panc_cancer_fup_days IN('NA', ''), NULL, @j_panc_cancer_fup_days),
        j_panc_cancer_fup_age = IF(@j_panc_cancer_fup_age IN('NA', ''), NULL, @j_panc_cancer_fup_age),
        j_panc_cancer_dx_age = IF(@j_panc_cancer_dx_age IN('NA', ''), NULL, @j_panc_cancer_dx_age),
        j_phys_act_related_dx_age = IF(@j_phys_act_related_dx_age IN('NA', ''), NULL, @j_phys_act_related_dx_age),
        j_phys_act_related = IF(@j_phys_act_related IN('NA', ''), NULL, @j_phys_act_related),
        j_phys_act_related_fup_age = IF(@j_phys_act_related_fup_age IN('NA', ''), NULL, @j_phys_act_related_fup_age),
        j_phys_act_related_fup_days = IF(@j_phys_act_related_fup_days IN('NA', ''), NULL, @j_phys_act_related_fup_days),
        j_pros_cancer = IF(@j_pros_cancer IN('NA', ''), NULL, @j_pros_cancer),
        j_pros_cancer_fup_days = IF(@j_pros_cancer_fup_days IN('NA', ''), NULL, @j_pros_cancer_fup_days),
        j_pros_cancer_fup_age = IF(@j_pros_cancer_fup_age IN('NA', ''), NULL, @j_pros_cancer_fup_age),
        j_pros_cancer_dx_age = IF(@j_pros_cancer_dx_age IN('NA', ''), NULL, @j_pros_cancer_dx_age),
        j_pros_non_advanced = IF(@j_pros_non_advanced IN('NA', ''), NULL, @j_pros_non_advanced),
        j_pros_advanced_including7 = IF(@j_pros_advanced_including7 IN('NA', ''), NULL, @j_pros_advanced_including7),
        j_pros_advanced_excluding7 = IF(@j_pros_advanced_excluding7 IN('NA', ''), NULL, @j_pros_advanced_excluding7),
        j_sarcoma = IF(@j_sarcoma IN('NA', ''), NULL, @j_sarcoma),
        j_sarcoma_fup_days = IF(@j_sarcoma_fup_days IN('NA', ''), NULL, @j_sarcoma_fup_days),
        j_sarcoma_fup_age = IF(@j_sarcoma_fup_age IN('NA', ''), NULL, @j_sarcoma_fup_age),
        j_sarcoma_dx_age = IF(@j_sarcoma_dx_age IN('NA', ''), NULL, @j_sarcoma_dx_age),
        j_smoking_related_dx_age = IF(@j_smoking_related_dx_age IN('NA', ''), NULL, @j_smoking_related_dx_age),
        j_smoking_related = IF(@j_smoking_related IN('NA', ''), NULL, @j_smoking_related),
        j_smoking_related_fup_age = IF(@j_smoking_related_fup_age IN('NA', ''), NULL, @j_smoking_related_fup_age),
        j_smoking_related_fup_days = IF(@j_smoking_related_fup_days IN('NA', ''), NULL, @j_smoking_related_fup_days),
        j_solid_tumor = IF(@j_solid_tumor IN('NA', ''), NULL, @j_solid_tumor),
        j_solid_tumor_fup_days = IF(@j_solid_tumor_fup_days IN('NA', ''), NULL, @j_solid_tumor_fup_days),
        j_solid_tumor_fup_age = IF(@j_solid_tumor_fup_age IN('NA', ''), NULL, @j_solid_tumor_fup_age),
        j_solid_tumor_dx_age = IF(@j_solid_tumor_dx_age IN('NA', ''), NULL, @j_solid_tumor_dx_age),
        j_squamous = IF(@j_squamous IN('NA', ''), NULL, @j_squamous),
        j_squamous_fup_days = IF(@j_squamous_fup_days IN('NA', ''), NULL, @j_squamous_fup_days),
        j_squamous_fup_age = IF(@j_squamous_fup_age IN('NA', ''), NULL, @j_squamous_fup_age),
        j_squamous_dx_age = IF(@j_squamous_dx_age IN('NA', ''), NULL, @j_squamous_dx_age),
        j_thyd_cancer = IF(@j_thyd_cancer IN('NA', ''), NULL, @j_thyd_cancer),
        j_thyd_cancer_fup_days = IF(@j_thyd_cancer_fup_days IN('NA', ''), NULL, @j_thyd_cancer_fup_days),
        j_thyd_cancer_fup_age = IF(@j_thyd_cancer_fup_age IN('NA', ''), NULL, @j_thyd_cancer_fup_age),
        j_thyd_cancer_dx_age = IF(@j_thyd_cancer_dx_age IN('NA', ''), NULL, @j_thyd_cancer_dx_age),
        j_upgi_cancer = IF(@j_upgi_cancer IN('NA', ''), NULL, @j_upgi_cancer),
        j_upgi_cancer_fup_days = IF(@j_upgi_cancer_fup_days IN('NA', ''), NULL, @j_upgi_cancer_fup_days),
        j_upgi_cancer_fup_age = IF(@j_upgi_cancer_fup_age IN('NA', ''), NULL, @j_upgi_cancer_fup_age),
        j_upgi_cancer_dx_age = IF(@j_upgi_cancer_dx_age IN('NA', ''), NULL, @j_upgi_cancer_dx_age),
        j_urothelial = IF(@j_urothelial IN('NA', ''), NULL, @j_urothelial),
        j_urothelial_fup_days = IF(@j_urothelial_fup_days IN('NA', ''), NULL, @j_urothelial_fup_days),
        j_urothelial_fup_age = IF(@j_urothelial_fup_age IN('NA', ''), NULL, @j_urothelial_fup_age),
        j_urothelial_dx_age = IF(@j_urothelial_dx_age IN('NA', ''), NULL, @j_urothelial_dx_age),
        is_dead = IF(@is_dead IN('NA', ''), NULL, @is_dead),
        mortality_exitage = IF(@mortality_exitage IN('NA', ''), NULL, @mortality_exitage),
        dth_days = IF(@dth_days IN('NA', ''), NULL, @dth_days),
        mortality_exitdays_unadj = IF(@mortality_exitdays_unadj IN('NA', ''), NULL, @mortality_exitdays_unadj),
        f_death_ischemic = IF(@f_death_ischemic IN('NA', ''), NULL, @f_death_ischemic),
        f_death_cerebrovascular = IF(@f_death_cerebrovascular IN('NA', ''), NULL, @f_death_cerebrovascular),
        f_death_rheumatic = IF(@f_death_rheumatic IN('NA', ''), NULL, @f_death_rheumatic),
        f_death_hypertensive = IF(@f_death_hypertensive IN('NA', ''), NULL, @f_death_hypertensive),
        f_death_peripheral = IF(@f_death_peripheral IN('NA', ''), NULL, @f_death_peripheral),
        f_death_heart = IF(@f_death_heart IN('NA', ''), NULL, @f_death_heart),
        f_death_cardiac = IF(@f_death_cardiac IN('NA', ''), NULL, @f_death_cardiac),
        f_death_arrhythmia = IF(@f_death_arrhythmia IN('NA', ''), NULL, @f_death_arrhythmia),
        f_death_endocarditis = IF(@f_death_endocarditis IN('NA', ''), NULL, @f_death_endocarditis),
        f_death_cardiovascular = IF(@f_death_cardiovascular IN('NA', ''), NULL, @f_death_cardiovascular),
        f_death_cancer = IF(@f_death_cancer IN('NA', ''), NULL, @f_death_cancer),
        f_death_chronicresp = IF(@f_death_chronicresp IN('NA', ''), NULL, @f_death_chronicresp),
        f_death_alzheimers = IF(@f_death_alzheimers IN('NA', ''), NULL, @f_death_alzheimers),
        f_death_diabetes = IF(@f_death_diabetes IN('NA', ''), NULL, @f_death_diabetes),
        f_death_nephritis = IF(@f_death_nephritis IN('NA', ''), NULL, @f_death_nephritis),
        f_death_chronicliver = IF(@f_death_chronicliver IN('NA', ''), NULL, @f_death_chronicliver),
        f_death_parkinsons = IF(@f_death_parkinsons IN('NA', ''), NULL, @f_death_parkinsons),
        bq_educat_o = IF(@bq_educat_o IN('NA', ''), NULL, @bq_educat_o),
        bq_marital_co = IF(@bq_marital_co IN('NA', ''), NULL, @bq_marital_co),
        bq_fmenstr_o = IF(@bq_fmenstr_o IN('NA', ''), NULL, @bq_fmenstr_o),
        bq_tubal_o = IF(@bq_tubal_o IN('NA', ''), NULL, @bq_tubal_o),
        bq_bbd_b = IF(@bq_bbd_b IN('NA', ''), NULL, @bq_bbd_b),
        bq_benign_ovcyst_b = IF(@bq_benign_ovcyst_b IN('NA', ''), NULL, @bq_benign_ovcyst_b),
        bq_endometriosis_b = IF(@bq_endometriosis_b IN('NA', ''), NULL, @bq_endometriosis_b),
        bq_uterine_fib_b = IF(@bq_uterine_fib_b IN('NA', ''), NULL, @bq_uterine_fib_b),
        bq_trypreg_b = IF(@bq_trypreg_b IN('NA', ''), NULL, @bq_trypreg_b),
        bq_urinatea_o = IF(@bq_urinatea_o IN('NA', ''), NULL, @bq_urinatea_o),
        bq_infprosa_o = IF(@bq_infprosa_o IN('NA', ''), NULL, @bq_infprosa_o),
        bq_hearta_f_b = IF(@bq_hearta_f_b IN('NA', ''), NULL, @bq_hearta_f_b),
        bq_bronchit_f_b = IF(@bq_bronchit_f_b IN('NA', ''), NULL, @bq_bronchit_f_b),
        bq_polyps_f_b = IF(@bq_polyps_f_b IN('NA', ''), NULL, @bq_polyps_f_b),
        bq_ulcerative_colitits_b = IF(@bq_ulcerative_colitits_b IN('NA', ''), NULL, @bq_ulcerative_colitits_b),
        bq_crohns_disease_b = IF(@bq_crohns_disease_b IN('NA', ''), NULL, @bq_crohns_disease_b),
        bq_familial_polyposis_b = IF(@bq_familial_polyposis_b IN('NA', ''), NULL, @bq_familial_polyposis_b),
        bq_hepatitis_b = IF(@bq_hepatitis_b IN('NA', ''), NULL, @bq_hepatitis_b),
        bq_cirrhosis_b = IF(@bq_cirrhosis_b IN('NA', ''), NULL, @bq_cirrhosis_b),
        bq_divertic_f_b = IF(@bq_divertic_f_b IN('NA', ''), NULL, @bq_divertic_f_b),
        bq_gallblad_f_b = IF(@bq_gallblad_f_b IN('NA', ''), NULL, @bq_gallblad_f_b),
        bq_age_co = IF(@bq_age_co IN('NA', ''), NULL, @bq_age_co),
        bq_race7_ca = IF(@bq_race7_ca IN('NA', ''), NULL, @bq_race7_ca),
        bq_hispanic_f_b = IF(@bq_hispanic_f_b IN('NA', ''), NULL, @bq_hispanic_f_b),
        bq_surg_resection_b = IF(@bq_surg_resection_b IN('NA', ''), NULL, @bq_surg_resection_b),
        bq_surg_prostatectomy_b = IF(@bq_surg_prostatectomy_b IN('NA', ''), NULL, @bq_surg_prostatectomy_b),
        bq_hyster_f_b = IF(@bq_hyster_f_b IN('NA', ''), NULL, @bq_hyster_f_b),
        bq_ovariesr_f_ca = IF(@bq_ovariesr_f_ca IN('NA', ''), NULL, @bq_ovariesr_f_ca),
        bq_infpros_f_b = IF(@bq_infpros_f_b IN('NA', ''), NULL, @bq_infpros_f_b),
        bq_urinate_f_o = IF(@bq_urinate_f_o IN('NA', ''), NULL, @bq_urinate_f_o),
        bq_smoked_f_b = IF(@bq_smoked_f_b IN('NA', ''), NULL, @bq_smoked_f_b),
        bq_smokea_f_co = IF(@bq_smokea_f_co IN('NA', ''), NULL, @bq_smokea_f_co),
        bq_ssmokea_f_co = IF(@bq_ssmokea_f_co IN('NA', ''), NULL, @bq_ssmokea_f_co),
        bq_cig_stop_co = IF(@bq_cig_stop_co IN('NA', ''), NULL, @bq_cig_stop_co),
        bq_bmi_20_co = IF(@bq_bmi_20_co IN('NA', ''), NULL, @bq_bmi_20_co),
        bq_bmi_50_co = IF(@bq_bmi_50_co IN('NA', ''), NULL, @bq_bmi_50_co),
        bq_bmi_curr_co = IF(@bq_bmi_curr_co IN('NA', ''), NULL, @bq_bmi_curr_co),
        bq_weight_f_co = IF(@bq_weight_f_co IN('NA', ''), NULL, @bq_weight_f_co),
        bq_weight20_f_co = IF(@bq_weight20_f_co IN('NA', ''), NULL, @bq_weight20_f_co),
        bq_weight50_f_co = IF(@bq_weight50_f_co IN('NA', ''), NULL, @bq_weight50_f_co),
        bq_height_f_co = IF(@bq_height_f_co IN('NA', ''), NULL, @bq_height_f_co),
        bq_fh_cancer_b = IF(@bq_fh_cancer_b IN('NA', ''), NULL, @bq_fh_cancer_b),
        center = IF(@center IN('NA', ''), NULL, @center),
        arm = IF(@arm IN('NA', ''), NULL, @arm),
        sex = IF(@sex IN('NA', ''), NULL, @sex),
        genetic_ancestry_platform = IF(@genetic_ancestry_platform IN('NA', ''), NULL, @genetic_ancestry_platform),
        in_final_gsa_population = IF(@in_final_gsa_population IN('NA', ''), NULL, @in_final_gsa_population),
        ancestry_admix_p_f = IF(@ancestry_admix_p_f IN('NA', ''), NULL, @ancestry_admix_p_f),
        ancestry_admix_p_e = IF(@ancestry_admix_p_e IN('NA', ''), NULL, @ancestry_admix_p_e),
        ancestry_admix_p_a = IF(@ancestry_admix_p_a IN('NA', ''), NULL, @ancestry_admix_p_a),
        ancestry_genetic_distance1 = IF(@ancestry_genetic_distance1 IN('NA', ''), NULL, @ancestry_genetic_distance1),
        ancestry_genetic_distance2 = IF(@ancestry_genetic_distance2 IN('NA', ''), NULL, @ancestry_genetic_distance2),
        ancestry_genetic_distance3 = IF(@ancestry_genetic_distance3 IN('NA', ''), NULL, @ancestry_genetic_distance3),
        ancestry_genetic_distance4 = IF(@ancestry_genetic_distance4 IN('NA', ''), NULL, @ancestry_genetic_distance4),
        genetic_ancestry = IF(@genetic_ancestry IN('NA', ''), NULL, @genetic_ancestry),
        genetic_ancestry_pca7 = IF(@genetic_ancestry_pca7 IN('NA', ''), NULL, @genetic_ancestry_pca7),
        eu_pca_component1 = IF(@eu_pca_component1 IN('NA', ''), NULL, @eu_pca_component1),
        eu_pca_component2 = IF(@eu_pca_component2 IN('NA', ''), NULL, @eu_pca_component2),
        eu_pca_component3 = IF(@eu_pca_component3 IN('NA', ''), NULL, @eu_pca_component3),
        eu_pca_component4 = IF(@eu_pca_component4 IN('NA', ''), NULL, @eu_pca_component4),
        eu_pca_component5 = IF(@eu_pca_component5 IN('NA', ''), NULL, @eu_pca_component5),
        eu_pca_component6 = IF(@eu_pca_component6 IN('NA', ''), NULL, @eu_pca_component6),
        eu_pca_component7 = IF(@eu_pca_component7 IN('NA', ''), NULL, @eu_pca_component7),
        eu_pca_component8 = IF(@eu_pca_component8 IN('NA', ''), NULL, @eu_pca_component8),
        eu_pca_component9 = IF(@eu_pca_component9 IN('NA', ''), NULL, @eu_pca_component9),
        eu_pca_component10 = IF(@eu_pca_component10 IN('NA', ''), NULL, @eu_pca_component10),
        aa_pca_component1 = IF(@aa_pca_component1 IN('NA', ''), NULL, @aa_pca_component1),
        aa_pca_component2 = IF(@aa_pca_component2 IN('NA', ''), NULL, @aa_pca_component2),
        aa_pca_component3 = IF(@aa_pca_component3 IN('NA', ''), NULL, @aa_pca_component3),
        aa_pca_component4 = IF(@aa_pca_component4 IN('NA', ''), NULL, @aa_pca_component4),
        aa_pca_component5 = IF(@aa_pca_component5 IN('NA', ''), NULL, @aa_pca_component5),
        aa_pca_component6 = IF(@aa_pca_component6 IN('NA', ''), NULL, @aa_pca_component6),
        aa_pca_component7 = IF(@aa_pca_component7 IN('NA', ''), NULL, @aa_pca_component7),
        aa_pca_component8 = IF(@aa_pca_component8 IN('NA', ''), NULL, @aa_pca_component8),
        aa_pca_component9 = IF(@aa_pca_component9 IN('NA', ''), NULL, @aa_pca_component9),
        aa_pca_component10 = IF(@aa_pca_component10 IN('NA', ''), NULL, @aa_pca_component10),
        ea_pca_component1 = IF(@ea_pca_component1 IN('NA', ''), NULL, @ea_pca_component1),
        ea_pca_component2 = IF(@ea_pca_component2 IN('NA', ''), NULL, @ea_pca_component2),
        ea_pca_component3 = IF(@ea_pca_component3 IN('NA', ''), NULL, @ea_pca_component3),
        ea_pca_component4 = IF(@ea_pca_component4 IN('NA', ''), NULL, @ea_pca_component4),
        ea_pca_component5 = IF(@ea_pca_component5 IN('NA', ''), NULL, @ea_pca_component5),
        ea_pca_component6 = IF(@ea_pca_component6 IN('NA', ''), NULL, @ea_pca_component6),
        ea_pca_component7 = IF(@ea_pca_component7 IN('NA', ''), NULL, @ea_pca_component7),
        ea_pca_component8 = IF(@ea_pca_component8 IN('NA', ''), NULL, @ea_pca_component8),
        ea_pca_component9 = IF(@ea_pca_component9 IN('NA', ''), NULL, @ea_pca_component9),
        ea_pca_component10 = IF(@ea_pca_component10 IN('NA', ''), NULL, @ea_pca_component10),
        h2_pca_component1 = IF(@h2_pca_component1 IN('NA', ''), NULL, @h2_pca_component1),
        h2_pca_component2 = IF(@h2_pca_component2 IN('NA', ''), NULL, @h2_pca_component2),
        h2_pca_component3 = IF(@h2_pca_component3 IN('NA', ''), NULL, @h2_pca_component3),
        h2_pca_component4 = IF(@h2_pca_component4 IN('NA', ''), NULL, @h2_pca_component4),
        h2_pca_component5 = IF(@h2_pca_component5 IN('NA', ''), NULL, @h2_pca_component5),
        h2_pca_component6 = IF(@h2_pca_component6 IN('NA', ''), NULL, @h2_pca_component6),
        h2_pca_component7 = IF(@h2_pca_component7 IN('NA', ''), NULL, @h2_pca_component7),
        h2_pca_component8 = IF(@h2_pca_component8 IN('NA', ''), NULL, @h2_pca_component8),
        h2_pca_component9 = IF(@h2_pca_component9 IN('NA', ''), NULL, @h2_pca_component9),
        h2_pca_component10 = IF(@h2_pca_component10 IN('NA', ''), NULL, @h2_pca_component10),
        h1_pca_component1 = IF(@h1_pca_component1 IN('NA', ''), NULL, @h1_pca_component1),
        h1_pca_component2 = IF(@h1_pca_component2 IN('NA', ''), NULL, @h1_pca_component2),
        h1_pca_component3 = IF(@h1_pca_component3 IN('NA', ''), NULL, @h1_pca_component3),
        h1_pca_component4 = IF(@h1_pca_component4 IN('NA', ''), NULL, @h1_pca_component4),
        h1_pca_component5 = IF(@h1_pca_component5 IN('NA', ''), NULL, @h1_pca_component5),
        h1_pca_component6 = IF(@h1_pca_component6 IN('NA', ''), NULL, @h1_pca_component6),
        h1_pca_component7 = IF(@h1_pca_component7 IN('NA', ''), NULL, @h1_pca_component7),
        h1_pca_component8 = IF(@h1_pca_component8 IN('NA', ''), NULL, @h1_pca_component8),
        h1_pca_component9 = IF(@h1_pca_component9 IN('NA', ''), NULL, @h1_pca_component9),
        h1_pca_component10 = IF(@h1_pca_component10 IN('NA', ''), NULL, @h1_pca_component10),
        sa_pca_component1 = IF(@sa_pca_component1 IN('NA', ''), NULL, @sa_pca_component1),
        sa_pca_component2 = IF(@sa_pca_component2 IN('NA', ''), NULL, @sa_pca_component2),
        sa_pca_component3 = IF(@sa_pca_component3 IN('NA', ''), NULL, @sa_pca_component3),
        sa_pca_component4 = IF(@sa_pca_component4 IN('NA', ''), NULL, @sa_pca_component4),
        sa_pca_component5 = IF(@sa_pca_component5 IN('NA', ''), NULL, @sa_pca_component5),
        sa_pca_component6 = IF(@sa_pca_component6 IN('NA', ''), NULL, @sa_pca_component6),
        sa_pca_component7 = IF(@sa_pca_component7 IN('NA', ''), NULL, @sa_pca_component7),
        sa_pca_component8 = IF(@sa_pca_component8 IN('NA', ''), NULL, @sa_pca_component8),
        sa_pca_component9 = IF(@sa_pca_component9 IN('NA', ''), NULL, @sa_pca_component9),
        sa_pca_component10 = IF(@sa_pca_component10 IN('NA', ''), NULL, @sa_pca_component10),
        ot_pca_component1 = IF(@ot_pca_component1 IN('NA', ''), NULL, @ot_pca_component1),
        ot_pca_component2 = IF(@ot_pca_component2 IN('NA', ''), NULL, @ot_pca_component2),
        ot_pca_component3 = IF(@ot_pca_component3 IN('NA', ''), NULL, @ot_pca_component3),
        ot_pca_component4 = IF(@ot_pca_component4 IN('NA', ''), NULL, @ot_pca_component4),
        ot_pca_component5 = IF(@ot_pca_component5 IN('NA', ''), NULL, @ot_pca_component5),
        ot_pca_component6 = IF(@ot_pca_component6 IN('NA', ''), NULL, @ot_pca_component6),
        ot_pca_component7 = IF(@ot_pca_component7 IN('NA', ''), NULL, @ot_pca_component7),
        ot_pca_component8 = IF(@ot_pca_component8 IN('NA', ''), NULL, @ot_pca_component8),
        ot_pca_component9 = IF(@ot_pca_component9 IN('NA', ''), NULL, @ot_pca_component9),
        ot_pca_component10 = IF(@ot_pca_component10 IN('NA', ''), NULL, @ot_pca_component10),
        pca_components_platform = IF(@pca_components_platform IN('NA', ''), NULL, @pca_components_platform),
        has_pca_components = IF(@has_pca_components IN('NA', ''), NULL, @has_pca_components),
        genetic_ancestry_platform_study = IF(@genetic_ancestry_platform_study IN('NA', ''), NULL, @genetic_ancestry_platform_study),
        dqx_age_co = IF(@dqx_age_co IN('NA', ''), NULL, @dqx_age_co),
        dqx_qxn_physicact_40_o = IF(@dqx_qxn_physicact_40_o IN('NA', ''), NULL, @dqx_qxn_physicact_40_o),
        dqx_qxn_physicact_now_o = IF(@dqx_qxn_physicact_now_o IN('NA', ''), NULL, @dqx_qxn_physicact_now_o),
        sqx_age_co = IF(@sqx_age_co IN('NA', ''), NULL, @sqx_age_co),
        sqx_sit_ht_o = IF(@sqx_sit_ht_o IN('NA', ''), NULL, @sqx_sit_ht_o),
        sqx_waist_hip_o = IF(@sqx_waist_hip_o IN('NA', ''), NULL, @sqx_waist_hip_o),
        sqx_height_co = IF(@sqx_height_co IN('NA', ''), NULL, @sqx_height_co),
        sqx_wt30s_co = IF(@sqx_wt30s_co IN('NA', ''), NULL, @sqx_wt30s_co),
        sqx_wt40s_co = IF(@sqx_wt40s_co IN('NA', ''), NULL, @sqx_wt40s_co),
        sqx_wt50s_co = IF(@sqx_wt50s_co IN('NA', ''), NULL, @sqx_wt50s_co),
        sqx_wt60s_co = IF(@sqx_wt60s_co IN('NA', ''), NULL, @sqx_wt60s_co),
        sqx_wt70s_co = IF(@sqx_wt70s_co IN('NA', ''), NULL, @sqx_wt70s_co),
        sqx_wt_curr_co = IF(@sqx_wt_curr_co IN('NA', ''), NULL, @sqx_wt_curr_co),
        sqx_bmi30s_co = IF(@sqx_bmi30s_co IN('NA', ''), NULL, @sqx_bmi30s_co),
        sqx_bmi40s_co = IF(@sqx_bmi40s_co IN('NA', ''), NULL, @sqx_bmi40s_co),
        sqx_bmi50s_co = IF(@sqx_bmi50s_co IN('NA', ''), NULL, @sqx_bmi50s_co),
        sqx_bmi60s_co = IF(@sqx_bmi60s_co IN('NA', ''), NULL, @sqx_bmi60s_co),
        sqx_bmi70s_co = IF(@sqx_bmi70s_co IN('NA', ''), NULL, @sqx_bmi70s_co),
        sqx_bmi_curr_co = IF(@sqx_bmi_curr_co IN('NA', ''), NULL, @sqx_bmi_curr_co),
        sqx_cholesterol_b = IF(@sqx_cholesterol_b IN('NA', ''), NULL, @sqx_cholesterol_b),
        sqx_asthma_b = IF(@sqx_asthma_b IN('NA', ''), NULL, @sqx_asthma_b),
        sqxbq_hearta_b = IF(@sqxbq_hearta_b IN('NA', ''), NULL, @sqxbq_hearta_b),
        sqxbq_stroke_b = IF(@sqxbq_stroke_b IN('NA', ''), NULL, @sqxbq_stroke_b),
        sqxbq_hyperten_b = IF(@sqxbq_hyperten_b IN('NA', ''), NULL, @sqxbq_hyperten_b),
        sqxbq_diabetes_b = IF(@sqxbq_diabetes_b IN('NA', ''), NULL, @sqxbq_diabetes_b),
        sqxbq_osteopor_b = IF(@sqxbq_osteopor_b IN('NA', ''), NULL, @sqxbq_osteopor_b),
        sqxbq_emphysema_b = IF(@sqxbq_emphysema_b IN('NA', ''), NULL, @sqxbq_emphysema_b),
        sqxbq_arthritis_b = IF(@sqxbq_arthritis_b IN('NA', ''), NULL, @sqxbq_arthritis_b),
        sqx_broke_hip_b = IF(@sqx_broke_hip_b IN('NA', ''), NULL, @sqx_broke_hip_b),
        sqx_broke_arm_b = IF(@sqx_broke_arm_b IN('NA', ''), NULL, @sqx_broke_arm_b),
        sqx_broke_vertebra_b = IF(@sqx_broke_vertebra_b IN('NA', ''), NULL, @sqx_broke_vertebra_b),
        sqx_broke_none_b = IF(@sqx_broke_none_b IN('NA', ''), NULL, @sqx_broke_none_b),
        sqx_balding_trend_o = IF(@sqx_balding_trend_o IN('NA', ''), NULL, @sqx_balding_trend_o),
        sqx_urinate_o = IF(@sqx_urinate_o IN('NA', ''), NULL, @sqx_urinate_o),
        sqxbq_bpha_o = IF(@sqxbq_bpha_o IN('NA', ''), NULL, @sqxbq_bpha_o),
        sqxbq_bph_b = IF(@sqxbq_bph_b IN('NA', ''), NULL, @sqxbq_bph_b),
        sqx_lift_weights_b = IF(@sqx_lift_weights_b IN('NA', ''), NULL, @sqx_lift_weights_b),
        sqx_lift_weights_lev_o = IF(@sqx_lift_weights_lev_o IN('NA', ''), NULL, @sqx_lift_weights_lev_o),
        sqx_active_b = IF(@sqx_active_b IN('NA', ''), NULL, @sqx_active_b),
        sqx_fh_blad_b = IF(@sqx_fh_blad_b IN('NA', ''), NULL, @sqx_fh_blad_b),
        sqx_fh_breast_b = IF(@sqx_fh_breast_b IN('NA', ''), NULL, @sqx_fh_breast_b),
        sqx_fh_colo_b = IF(@sqx_fh_colo_b IN('NA', ''), NULL, @sqx_fh_colo_b),
        sqx_fh_endo_b = IF(@sqx_fh_endo_b IN('NA', ''), NULL, @sqx_fh_endo_b),
        sqx_fh_leuk_b = IF(@sqx_fh_leuk_b IN('NA', ''), NULL, @sqx_fh_leuk_b),
        sqx_fh_lung_b = IF(@sqx_fh_lung_b IN('NA', ''), NULL, @sqx_fh_lung_b),
        sqx_fh_lymph_b = IF(@sqx_fh_lymph_b IN('NA', ''), NULL, @sqx_fh_lymph_b),
        sqx_fh_ovar_b = IF(@sqx_fh_ovar_b IN('NA', ''), NULL, @sqx_fh_ovar_b),
        sqx_fh_pros_b = IF(@sqx_fh_pros_b IN('NA', ''), NULL, @sqx_fh_pros_b),
        sqx_fh_cancer_f_b = IF(@sqx_fh_cancer_f_b IN('NA', ''), NULL, @sqx_fh_cancer_f_b),
        sqx_twins_b = IF(@sqx_twins_b IN('NA', ''), NULL, @sqx_twins_b),
        sqx_smk100_b = IF(@sqx_smk100_b IN('NA', ''), NULL, @sqx_smk100_b),
        sqx_amt_smk_o = IF(@sqx_amt_smk_o IN('NA', ''), NULL, @sqx_amt_smk_o),
        sqx_smk_crave1_b = IF(@sqx_smk_crave1_b IN('NA', ''), NULL, @sqx_smk_crave1_b),
        sqx_smk_crave2_b = IF(@sqx_smk_crave2_b IN('NA', ''), NULL, @sqx_smk_crave2_b),
        sqx_smk_crave3_b = IF(@sqx_smk_crave3_b IN('NA', ''), NULL, @sqx_smk_crave3_b),
        sqx_smk_crave4_b = IF(@sqx_smk_crave4_b IN('NA', ''), NULL, @sqx_smk_crave4_b),
        sqx_smk_try_quit_b = IF(@sqx_smk_try_quit_b IN('NA', ''), NULL, @sqx_smk_try_quit_b),
        sqx_smk_age_quit_co = IF(@sqx_smk_age_quit_co IN('NA', ''), NULL, @sqx_smk_age_quit_co),
        sqx_worry_lungca_o = IF(@sqx_worry_lungca_o IN('NA', ''), NULL, @sqx_worry_lungca_o),
        sqx_risk_lungca_o = IF(@sqx_risk_lungca_o IN('NA', ''), NULL, @sqx_risk_lungca_o),
        sqx_smk_his_co = IF(@sqx_smk_his_co IN('NA', ''), NULL, @sqx_smk_his_co),
        sqx_smk_behv_co = IF(@sqx_smk_behv_co IN('NA', ''), NULL, @sqx_smk_behv_co),
        sqx_smk_ftnd_co = IF(@sqx_smk_ftnd_co IN('NA', ''), NULL, @sqx_smk_ftnd_co),
        sqx_years_quit_co = IF(@sqx_years_quit_co IN('NA', ''), NULL, @sqx_years_quit_co),
        sqx_cig_years_co = IF(@sqx_cig_years_co IN('NA', ''), NULL, @sqx_cig_years_co),
        sqx_gain_chest_shoulders_b = IF(@sqx_gain_chest_shoulders_b IN('NA', ''), NULL, @sqx_gain_chest_shoulders_b),
        sqx_gain_waist_stomach_b = IF(@sqx_gain_waist_stomach_b IN('NA', ''), NULL, @sqx_gain_waist_stomach_b),
        sqx_gain_hips_thighs_b = IF(@sqx_gain_hips_thighs_b IN('NA', ''), NULL, @sqx_gain_hips_thighs_b),
        sqx_gain_equally_over_b = IF(@sqx_gain_equally_over_b IN('NA', ''), NULL, @sqx_gain_equally_over_b),
        sqx_lose_chest_shoulders_b = IF(@sqx_lose_chest_shoulders_b IN('NA', ''), NULL, @sqx_lose_chest_shoulders_b),
        sqx_lose_waist_stomach_b = IF(@sqx_lose_waist_stomach_b IN('NA', ''), NULL, @sqx_lose_waist_stomach_b),
        sqx_lose_hips_thighs_b = IF(@sqx_lose_hips_thighs_b IN('NA', ''), NULL, @sqx_lose_hips_thighs_b),
        sqx_lose_equally_over_b = IF(@sqx_lose_equally_over_b IN('NA', ''), NULL, @sqx_lose_equally_over_b),
        sqxbq_rheumatoid_arthritis_b = IF(@sqxbq_rheumatoid_arthritis_b IN('NA', ''), NULL, @sqxbq_rheumatoid_arthritis_b),
        sqxbq_osteoarthritis_b = IF(@sqxbq_osteoarthritis_b IN('NA', ''), NULL, @sqxbq_osteoarthritis_b),
        sqx_moderate_week_co = IF(@sqx_moderate_week_co IN('NA', ''), NULL, @sqx_moderate_week_co),
        sqx_strenuous_week_co = IF(@sqx_strenuous_week_co IN('NA', ''), NULL, @sqx_strenuous_week_co),
        sqx_ever_balding_b = IF(@sqx_ever_balding_b IN('NA', ''), NULL, @sqx_ever_balding_b),
        sqx_top_bald_b = IF(@sqx_top_bald_b IN('NA', ''), NULL, @sqx_top_bald_b),
        bq_menstr_natural_o = IF(@bq_menstr_natural_o IN('NA', ''), NULL, @bq_menstr_natural_o),
        sqx_current_cigarette_b = IF(@sqx_current_cigarette_b IN('NA', ''), NULL, @sqx_current_cigarette_b),
        sqxbq_relapse_b = IF(@sqxbq_relapse_b IN('NA', ''), NULL, @sqxbq_relapse_b),
        bq_current_cigarette_b = IF(@bq_current_cigarette_b IN('NA', ''), NULL, @bq_current_cigarette_b),
        bq_cig_stat_o = IF(@bq_cig_stat_o IN('NA', ''), NULL, @bq_cig_stat_o),
        bq_cig_years_co = IF(@bq_cig_years_co IN('NA', ''), NULL, @bq_cig_years_co),
        bq_cigar_o = IF(@bq_cigar_o IN('NA', ''), NULL, @bq_cigar_o),
        bq_cigpd_f_o = IF(@bq_cigpd_f_o IN('NA', ''), NULL, @bq_cigpd_f_o),
        bq_filtered_f_b = IF(@bq_filtered_f_b IN('NA', ''), NULL, @bq_filtered_f_b),
        bq_pack_years_co = IF(@bq_pack_years_co IN('NA', ''), NULL, @bq_pack_years_co),
        bq_pipe_o = IF(@bq_pipe_o IN('NA', ''), NULL, @bq_pipe_o),
        sqx_pace_o = IF(@sqx_pace_o IN('NA', ''), NULL, @sqx_pace_o),
        sqx_stairs_o = IF(@sqx_stairs_o IN('NA', ''), NULL, @sqx_stairs_o),
        sqx_walk_mi_o = IF(@sqx_walk_mi_o IN('NA', ''), NULL, @sqx_walk_mi_o),
        pack_years_bqelsesqx_co = IF(@pack_years_bqelsesqx_co IN('NA', ''), NULL, @pack_years_bqelsesqx_co),
        sqx_smk_exp_adult_o = IF(@sqx_smk_exp_adult_o IN('NA', ''), NULL, @sqx_smk_exp_adult_o),
        sqx_smk_lgt_ca = IF(@sqx_smk_lgt_ca IN('NA', ''), NULL, @sqx_smk_lgt_ca),
        sqx_smk_menthol_b = IF(@sqx_smk_menthol_b IN('NA', ''), NULL, @sqx_smk_menthol_b),
        sqx_smk_plan_quit_o = IF(@sqx_smk_plan_quit_o IN('NA', ''), NULL, @sqx_smk_plan_quit_o),
        sqx_smk_wake_o = IF(@sqx_smk_wake_o IN('NA', ''), NULL, @sqx_smk_wake_o),
        sqx_smk30days_b = IF(@sqx_smk30days_b IN('NA', ''), NULL, @sqx_smk30days_b),
        sqxo_cig_stat_o = IF(@sqxo_cig_stat_o IN('NA', ''), NULL, @sqxo_cig_stat_o),
        sqx_urinatea_o = IF(@sqx_urinatea_o IN('NA', ''), NULL, @sqx_urinatea_o),
        sv_coffee_reg_nosug_dhq = IF(@sv_coffee_reg_nosug_dhq IN('NA', ''), NULL, @sv_coffee_reg_nosug_dhq),
        sv_coffee_decaf_nosug_dhq = IF(@sv_coffee_decaf_nosug_dhq IN('NA', ''), NULL, @sv_coffee_decaf_nosug_dhq),
        mped_fruit_nojuice_dhq = IF(@mped_fruit_nojuice_dhq IN('NA', ''), NULL, @mped_fruit_nojuice_dhq),
        dt_alc_alc_drinks_dhq = IF(@dt_alc_alc_drinks_dhq IN('NA', ''), NULL, @dt_alc_alc_drinks_dhq),
        drinker_dhq = IF(@drinker_dhq IN('NA', ''), NULL, @drinker_dhq),
        g_candy_choc_dhq = IF(@g_candy_choc_dhq IN('NA', ''), NULL, @g_candy_choc_dhq),
        g_red5_dhq = IF(@g_red5_dhq IN('NA', ''), NULL, @g_red5_dhq),
        g_process_6_dhq = IF(@g_process_6_dhq IN('NA', ''), NULL, @g_process_6_dhq),
        g_fruit_dhq = IF(@g_fruit_dhq IN('NA', ''), NULL, @g_fruit_dhq),
        g_vegetable_dhq = IF(@g_vegetable_dhq IN('NA', ''), NULL, @g_vegetable_dhq),
        g_fish_total_dhq = IF(@g_fish_total_dhq IN('NA', ''), NULL, @g_fish_total_dhq),
        g_salty_grain_snack_dhq = IF(@g_salty_grain_snack_dhq IN('NA', ''), NULL, @g_salty_grain_snack_dhq),
        g_fruit_citrus_dhq = IF(@g_fruit_citrus_dhq IN('NA', ''), NULL, @g_fruit_citrus_dhq),
        g_soda_reg_dhq = IF(@g_soda_reg_dhq IN('NA', ''), NULL, @g_soda_reg_dhq),
        dt_kcal_dhq = IF(@dt_kcal_dhq IN('NA', ''), NULL, @dt_kcal_dhq),
        dt_prot_dhq = IF(@dt_prot_dhq IN('NA', ''), NULL, @dt_prot_dhq),
        dt_fat_dhq = IF(@dt_fat_dhq IN('NA', ''), NULL, @dt_fat_dhq),
        dt_carb_dhq = IF(@dt_carb_dhq IN('NA', ''), NULL, @dt_carb_dhq),
        dt_fiber_csfii_dhq = IF(@dt_fiber_csfii_dhq IN('NA', ''), NULL, @dt_fiber_csfii_dhq),
        dt_caffeine_dhq = IF(@dt_caffeine_dhq IN('NA', ''), NULL, @dt_caffeine_dhq),
        gly_load_dhq = IF(@gly_load_dhq IN('NA', ''), NULL, @gly_load_dhq),
        mped_grain_dhq = IF(@mped_grain_dhq IN('NA', ''), NULL, @mped_grain_dhq),
        mped_grain_whole_dhq = IF(@mped_grain_whole_dhq IN('NA', ''), NULL, @mped_grain_whole_dhq),
        mped_veg_dark_green_dhq = IF(@mped_veg_dark_green_dhq IN('NA', ''), NULL, @mped_veg_dark_green_dhq),
        mped_dairy_dhq = IF(@mped_dairy_dhq IN('NA', ''), NULL, @mped_dairy_dhq),
        mped_dairy_milk_dhq = IF(@mped_dairy_milk_dhq IN('NA', ''), NULL, @mped_dairy_milk_dhq),
        mped_m_soy_dhq = IF(@mped_m_soy_dhq IN('NA', ''), NULL, @mped_m_soy_dhq),
        mped_m_nut_seed_dhq = IF(@mped_m_nut_seed_dhq IN('NA', ''), NULL, @mped_m_nut_seed_dhq),
        mped_legume_dhq = IF(@mped_legume_dhq IN('NA', ''), NULL, @mped_legume_dhq),
        mped_added_sugar_dhq = IF(@mped_added_sugar_dhq IN('NA', ''), NULL, @mped_added_sugar_dhq),
        pe_fr_protein_dhq = IF(@pe_fr_protein_dhq IN('NA', ''), NULL, @pe_fr_protein_dhq),
        pe_fr_fat_dhq = IF(@pe_fr_fat_dhq IN('NA', ''), NULL, @pe_fr_fat_dhq),
        pe_fr_carb_dhq = IF(@pe_fr_carb_dhq IN('NA', ''), NULL, @pe_fr_carb_dhq),
        pe_fr_alc_dhq = IF(@pe_fr_alc_dhq IN('NA', ''), NULL, @pe_fr_alc_dhq),
        gly_index_dhq = IF(@gly_index_dhq IN('NA', ''), NULL, @gly_index_dhq),
        dt_sugar_dhq = IF(@dt_sugar_dhq IN('NA', ''), NULL, @dt_sugar_dhq),
        age_dhq = IF(@age_dhq IN('NA', ''), NULL, @age_dhq),
        dhq_completedvalid = IF(@dhq_completedvalid IN('NA', ''), NULL, @dhq_completedvalid),
        mped_alc_bev_alc_drinks18_dhq = IF(@mped_alc_bev_alc_drinks18_dhq IN('NA', ''), NULL, @mped_alc_bev_alc_drinks18_dhq),
        mped_alc_bev_alc_drinks25_dhq = IF(@mped_alc_bev_alc_drinks25_dhq IN('NA', ''), NULL, @mped_alc_bev_alc_drinks25_dhq),
        mped_alc_bev_alc_drinks40_dhq = IF(@mped_alc_bev_alc_drinks40_dhq IN('NA', ''), NULL, @mped_alc_bev_alc_drinks40_dhq),
        mped_alc_bev_alc_drinks55_dhq = IF(@mped_alc_bev_alc_drinks55_dhq IN('NA', ''), NULL, @mped_alc_bev_alc_drinks55_dhq),
        qxn_f_coffee_dhq = IF(@qxn_f_coffee_dhq IN('NA', ''), NULL, @qxn_f_coffee_dhq),
        whfrden_dhq = IF(@whfrden_dhq IN('NA', ''), NULL, @whfrden_dhq),
        grnden_dhq = IF(@grnden_dhq IN('NA', ''), NULL, @grnden_dhq),
        wgrnden_dhq = IF(@wgrnden_dhq IN('NA', ''), NULL, @wgrnden_dhq),
        dairyden_dhq = IF(@dairyden_dhq IN('NA', ''), NULL, @dairyden_dhq),
        hei2005_total_score_dhq = IF(@hei2005_total_score_dhq IN('NA', ''), NULL, @hei2005_total_score_dhq),
        hei2010_total_score_dhq = IF(@hei2010_total_score_dhq IN('NA', ''), NULL, @hei2010_total_score_dhq),
        addsug_perc2015_dhq = IF(@addsug_perc2015_dhq IN('NA', ''), NULL, @addsug_perc2015_dhq),
        hei2015_total_score_dhq = IF(@hei2015_total_score_dhq IN('NA', ''), NULL, @hei2015_total_score_dhq),
        saltsnkden_g_dhq = IF(@saltsnkden_g_dhq IN('NA', ''), NULL, @saltsnkden_g_dhq),
        milkden_dhq = IF(@milkden_dhq IN('NA', ''), NULL, @milkden_dhq),
        frtden_g_dhq = IF(@frtden_g_dhq IN('NA', ''), NULL, @frtden_g_dhq),
        citfrtden_g_dhq = IF(@citfrtden_g_dhq IN('NA', ''), NULL, @citfrtden_g_dhq),
        vegtotden_g_dhq = IF(@vegtotden_g_dhq IN('NA', ''), NULL, @vegtotden_g_dhq),
        dkgrvegden_dhq = IF(@dkgrvegden_dhq IN('NA', ''), NULL, @dkgrvegden_dhq),
        legumeden_dhq = IF(@legumeden_dhq IN('NA', ''), NULL, @legumeden_dhq),
        nutden_dhq = IF(@nutden_dhq IN('NA', ''), NULL, @nutden_dhq),
        redmtden_g_dhq = IF(@redmtden_g_dhq IN('NA', ''), NULL, @redmtden_g_dhq),
        procmtden_g_dhq = IF(@procmtden_g_dhq IN('NA', ''), NULL, @procmtden_g_dhq),
        fishden_g_dhq = IF(@fishden_g_dhq IN('NA', ''), NULL, @fishden_g_dhq),
        soyden_dhq = IF(@soyden_dhq IN('NA', ''), NULL, @soyden_dhq),
        current_drinker = IF(@current_drinker IN('NA', ''), NULL, @current_drinker),
        former_drinker = IF(@former_drinker IN('NA', ''), NULL, @former_drinker),
        drinker_status_dhq_o = IF(@drinker_status_dhq_o IN('NA', ''), NULL, @drinker_status_dhq_o),
        ph_status = IF(@ph_status IN('NA', ''), NULL, @ph_status),
        first_psa_level = IF(@first_psa_level IN('NA', ''), NULL, @first_psa_level),
        first_psa_year = IF(@first_psa_year IN('NA', ''), NULL, @first_psa_year),
        first_ca125_level = IF(@first_ca125_level IN('NA', ''), NULL, @first_ca125_level),
        first_ca125_year = IF(@first_ca125_year IN('NA', ''), NULL, @first_ca125_year),
        adenoma_stat = IF(@adenoma_stat IN('NA', ''), NULL, @adenoma_stat),
        adenoma_fup_age = IF(@adenoma_fup_age IN('NA', ''), NULL, @adenoma_fup_age),
        adenoma_dx_age = IF(@adenoma_dx_age IN('NA', ''), NULL, @adenoma_dx_age),
        advanced_adenoma_stat = IF(@advanced_adenoma_stat IN('NA', ''), NULL, @advanced_adenoma_stat),
        advanced_adenoma_fup_age = IF(@advanced_adenoma_fup_age IN('NA', ''), NULL, @advanced_adenoma_fup_age),
        advanced_adenoma_dx_age = IF(@advanced_adenoma_dx_age IN('NA', ''), NULL, @advanced_adenoma_dx_age),
        non_advanced_adenoma_stat = IF(@non_advanced_adenoma_stat IN('NA', ''), NULL, @non_advanced_adenoma_stat),
        non_advanced_adenoma_fup_age = IF(@non_advanced_adenoma_fup_age IN('NA', ''), NULL, @non_advanced_adenoma_fup_age),
        non_advanced_adenoma_dx_age = IF(@non_advanced_adenoma_dx_age IN('NA', ''), NULL, @non_advanced_adenoma_dx_age);

-- import phenotype_sample values
INSERT INTO participant (id, ancestry, sex)
SELECT
    id,
    CASE bq_race7_ca
        WHEN 1 THEN 'white'
        WHEN 2 THEN 'black'
        WHEN 3 THEN 'hispanic'
        WHEN 4 THEN 'asian'
        WHEN 5 THEN 'pacific_islander'
        WHEN 6 THEN 'american_indian'
        ELSE NULL
    END AS ancestry,
    CASE sex
      WHEN 1 THEN 'male'
      WHEN 2 THEN 'female'
      ELSE NULL
    END AS sex
FROM participant_data_stage;

-- remove invalid age_name values 
-- (non-numeric values which are not columns in the participant data stage table)
UPDATE phenotype p 
    SET age_name = NULL
    WHERE 0 = (
    SELECT COUNT(*) FROM information_schema.columns
      WHERE
        table_name = 'participant_data_stage' AND 
        column_name = p.age_name)
    AND age_name NOT REGEXP '^[0-9]+$';


-- import participant_data values
CALL insert_participant_data();

-- create indexes on tables
ALTER TABLE participant_data
    ADD INDEX idx_participant_data__phenotype_id  (phenotype_id);

-- insert average and standard deviation metadata
INSERT INTO phenotype_metadata (phenotype_id, sex, chromosome, average_value, standard_deviation)
SELECT
    phenotype_id,
    "all" as sex,
    "all" as chromosome,
    avg(value) as average_value,
    std(value) as standard_deviation
FROM participant_data
GROUP BY phenotype_id
ON DUPLICATE KEY UPDATE
    average_value = VALUES(average_value),
    standard_deviation = VALUES(standard_deviation);

COMMIT;