START TRANSACTION;

-- if this script hangs, we should flush all tables
-- FLUSH TABLES;

-- needed if local_infile is disabled, need root privileges
-- SET GLOBAL local_infile = 'ON';

SET autocommit = 0;

-- recreate tables
DROP TABLE IF EXISTS participant_data_stage;
DROP TABLE IF EXISTS participant_data;
DROP TABLE IF EXISTS participant;

CREATE TABLE IF NOT EXISTS `participant` (
    `id`            INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `sex`           ENUM('female', 'male'),
    `ancestry`      ENUM('white', 'black', 'hispanic', 'asian', 'pacific_islander', 'american_indian')
);

CREATE TABLE IF NOT EXISTS `participant_data` (
    `id` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `phenotype_id` INTEGER NOT NULL,
    `participant_id` INTEGER,
    `value` DOUBLE,
    `age` INTEGER,
    FOREIGN KEY (phenotype_id) REFERENCES phenotype(id),
    FOREIGN KEY (participant_id) REFERENCES participant(id)
);

CREATE TABLE `participant_data_stage` (
    `id` integer primary key auto_increment,
    `plco_id` text,
    `chf_cat` double,
    `ischemicheart_cat` double,
    `depression_cat` double,
    `diabetes_cat` double,
    `ra_oa_cat` double,
    `chronickidney_cat` double,
    `copd_cat` double,
    `atrial_fib_cat` double,
    `alzh_cat` double,
    `alzh_demen_cat` double,
    `any_use` double,
    `part_d_mos` double,
    `chronic` double,
    `part_d_yrs` double,
    `j_adeno_carcinoma` double,
    `j_adeno_carcinoma_fup_days` double,
    `j_adeno_carcinoma_fup_age` double,
    `j_adeno_carcinoma_dx_age` double,
    `j_alcohol_related_dx_age` double,
    `j_alcohol_related` double,
    `j_alcohol_related_fup_age` double,
    `j_alcohol_related_fup_days` double,
    `j_bcell` double,
    `j_bcell_fup_days` double,
    `j_bcell_fup_age` double,
    `j_bcell_dx_age` double,
    `j_bili_cancer` double,
    `j_bili_cancer_fup_days` double,
    `j_bili_cancer_fup_age` double,
    `j_bili_cancer_dx_age` double,
    `j_blad_cancer` double,
    `j_blad_cancer_fup_days` double,
    `j_blad_cancer_fup_age` double,
    `j_blad_cancer_dx_age` double,
    `j_breast_cancer` double,
    `j_breast_cancer_fup_days` double,
    `j_breast_cancer_fup_age` double,
    `j_breast_cancer_dx_age` double,
    `j_breast_invasive` double,
    `j_breast_insitu` double,
    `j_breast_ductal` double,
    `j_breast_lobular` double,
    `j_breast_tubular` double,
    `j_breast_er_pos_or_equiv` double,
    `j_breast_er_neg` double,
    `j_breast_pr_pos_or_equiv` double,
    `j_breast_pr_neg` double,
    `j_breast_er_or_pr_pos` double,
    `j_breast_er_and_pr_neg` double,
    `j_breast_her2_pos_or_equiv` double,
    `j_breast_her2_neg` double,
    `j_breast_er_pr_and_her2_neg` double,
    `j_breast_grade34` double,
    `j_breast_grade2` double,
    `j_breast_grade1` double,
    `j_carcinoma` double,
    `j_carcinoma_fup_days` double,
    `j_carcinoma_fup_age` double,
    `j_carcinoma_dx_age` double,
    `j_colo_cancer` double,
    `j_colo_cancer_fup_days` double,
    `j_colo_cancer_fup_age` double,
    `j_colo_cancer_dx_age` double,
    `j_colo_distal` double,
    `j_colo_distal_proximal` double,
    `j_colo_proximal` double,
    `j_colo_rectal` double,
    `j_diabetes_related_dx_age` double,
    `j_diabetes_related` double,
    `j_diabetes_related_fup_age` double,
    `j_diabetes_related_fup_days` double,
    `j_ebv_related_dx_age` double,
    `j_ebv_related` double,
    `j_ebv_related_fup_age` double,
    `j_ebv_related_fup_days` double,
    `j_endo_cancer` double,
    `j_endo_cancer_fup_days` double,
    `j_endo_cancer_fup_age` double,
    `j_endo_cancer_dx_age` double,
    `j_endo_neuro` double,
    `j_endo_neuro_fup_days` double,
    `j_endo_neuro_fup_age` double,
    `j_endo_neuro_dx_age` double,
    `j_esoph_cancer` double,
    `j_esoph_cancer_fup_days` double,
    `j_esoph_cancer_fup_age` double,
    `j_esoph_cancer_dx_age` double,
    `j_esoph_adeno_carcinoma` double,
    `j_esoph_squamous` double,
    `j_hbv_related_dx_age` double,
    `j_hbv_related` double,
    `j_hbv_related_fup_age` double,
    `j_hbv_related_fup_days` double,
    `j_hcv_related_dx_age` double,
    `j_hcv_related` double,
    `j_hcv_related_fup_age` double,
    `j_hcv_related_fup_days` double,
    `j_height_related_dx_age` double,
    `j_height_related` double,
    `j_height_related_fup_age` double,
    `j_height_related_fup_days` double,
    `j_helicobacter_related_dx_age` double,
    `j_helicobacter_related` double,
    `j_helicobacter_related_fup_age` double,
    `j_helicobacter_related_fup_days` double,
    `j_hematologic` double,
    `j_hematologic_fup_days` double,
    `j_hematologic_fup_age` double,
    `j_hematologic_dx_age` double,
    `j_hnc_cancer` double,
    `j_hnc_cancer_fup_days` double,
    `j_hnc_cancer_fup_age` double,
    `j_hnc_cancer_dx_age` double,
    `j_hnc_larynx` double,
    `j_hnc_lip_oral_pharynx` double,
    `j_hnc_naso_mid_sinus` double,
    `j_hpv_related_dx_age` double,
    `j_hpv_related` double,
    `j_hpv_related_fup_age` double,
    `j_hpv_related_fup_days` double,
    `j_infection_related_dx_age` double,
    `j_infection_related` double,
    `j_infection_related_fup_age` double,
    `j_infection_related_fup_days` double,
    `j_kidney_cancer_fup_days` double,
    `j_kidney_cancer_fup_age` double,
    `j_kidney_cancer_dx_age` double,
    `j_kidney_cancer` double,
    `j_kidney_renalcell_clearcell` double,
    `j_kidney_renalcell_nos` double,
    `j_gast_cancer` double,
    `j_gast_cancer_fup_days` double,
    `j_gast_cancer_fup_age` double,
    `j_gast_cancer_dx_age` double,
    `j_gast_cardia` double,
    `j_gast_noncardia` double,
    `j_glio_cancer` double,
    `j_glio_cancer_fup_days` double,
    `j_glio_cancer_fup_age` double,
    `j_glio_cancer_dx_age` double,
    `j_liver_xintra_cancer_fup_days` double,
    `j_liver_xintra_cancer_fup_age` double,
    `j_liver_xintra_cancer_dx_age` double,
    `j_liver_xintra_cancer` double,
    `j_lung_cancer` double,
    `j_lung_cancer_fup_days` double,
    `j_lung_cancer_fup_age` double,
    `j_lung_cancer_dx_age` double,
    `j_lung_smallcell` double,
    `j_lung_adeno` double,
    `j_lung_squam` double,
    `j_lymphoid` double,
    `j_lymphoid_fup_days` double,
    `j_lymphoid_fup_age` double,
    `j_lymphoid_dx_age` double,
    `j_cll` double,
    `j_cll_fup_days` double,
    `j_cll_fup_age` double,
    `j_cll_dx_age` double,
    `j_mbreast_cancer` double,
    `j_mbreast_cancer_fup_days` double,
    `j_mbreast_cancer_fup_age` double,
    `j_mbreast_cancer_dx_age` double,
    `j_mela_cancer` double,
    `j_mela_cancer_fup_days` double,
    `j_mela_cancer_fup_age` double,
    `j_mela_cancer_dx_age` double,
    `j_mela_invasive_cancer` double,
    `j_mela_invasive_cancer_fup_age` double,
    `j_mela_invasive_cancer_dx_age` double,
    `j_mela_invasive_cancer_fup_days` double,
    `j_mesoth` double,
    `j_mesoth_fup_days` double,
    `j_mesoth_fup_age` double,
    `j_mesoth_dx_age` double,
    `j_myeloid` double,
    `j_myeloid_fup_days` double,
    `j_myeloid_fup_age` double,
    `j_myeloid_dx_age` double,
    `j_obesity_related_dx_age` double,
    `j_obesity_related` double,
    `j_obesity_related_fup_age` double,
    `j_obesity_related_fup_days` double,
    `j_osumm_cancer` double,
    `j_osumm_cancer_fup_days` double,
    `j_osumm_cancer_fup_age` double,
    `j_osumm_cancer_dx_age` double,
    `j_osumm_serous_grade_high` double,
    `j_panc_cancer` double,
    `j_panc_cancer_fup_days` double,
    `j_panc_cancer_fup_age` double,
    `j_panc_cancer_dx_age` double,
    `j_phys_act_related_dx_age` double,
    `j_phys_act_related` double,
    `j_phys_act_related_fup_age` double,
    `j_phys_act_related_fup_days` double,
    `j_pros_cancer` double,
    `j_pros_cancer_fup_days` double,
    `j_pros_cancer_fup_age` double,
    `j_pros_cancer_dx_age` double,
    `j_pros_non_advanced` double,
    `j_pros_advanced_including7` double,
    `j_pros_advanced_excluding7` double,
    `j_sarcoma` double,
    `j_sarcoma_fup_days` double,
    `j_sarcoma_fup_age` double,
    `j_sarcoma_dx_age` double,
    `j_smoking_related_dx_age` double,
    `j_smoking_related` double,
    `j_smoking_related_fup_age` double,
    `j_smoking_related_fup_days` double,
    `j_solid_tumor` double,
    `j_solid_tumor_fup_days` double,
    `j_solid_tumor_fup_age` double,
    `j_solid_tumor_dx_age` double,
    `j_squamous` double,
    `j_squamous_fup_days` double,
    `j_squamous_fup_age` double,
    `j_squamous_dx_age` double,
    `j_thyd_cancer` double,
    `j_thyd_cancer_fup_days` double,
    `j_thyd_cancer_fup_age` double,
    `j_thyd_cancer_dx_age` double,
    `j_upgi_cancer` double,
    `j_upgi_cancer_fup_days` double,
    `j_upgi_cancer_fup_age` double,
    `j_upgi_cancer_dx_age` double,
    `j_urothelial` double,
    `j_urothelial_fup_days` double,
    `j_urothelial_fup_age` double,
    `j_urothelial_dx_age` double,
    `is_dead` double,
    `mortality_exitage` double,
    `dth_days` double,
    `mortality_exitdays_unadj` double,
    `f_death_ischemic` double,
    `f_death_cerebrovascular` double,
    `f_death_rheumatic` double,
    `f_death_hypertensive` double,
    `f_death_peripheral` double,
    `f_death_heart` double,
    `f_death_cardiac` double,
    `f_death_arrhythmia` double,
    `f_death_endocarditis` double,
    `f_death_cardiovascular` double,
    `f_death_cancer` double,
    `f_death_chronicresp` double,
    `f_death_alzheimers` double,
    `f_death_diabetes` double,
    `f_death_nephritis` double,
    `f_death_chronicliver` double,
    `f_death_parkinsons` double,
    `bq_educat_o` double,
    `bq_marital_co` double,
    `bq_fmenstr_o` double,
    `bq_tubal_o` double,
    `bq_bbd_b` double,
    `bq_benign_ovcyst_b` double,
    `bq_endometriosis_b` double,
    `bq_uterine_fib_b` double,
    `bq_trypreg_b` double,
    `bq_urinatea_o` double,
    `bq_infprosa_o` double,
    `bq_hearta_f_b` double,
    `bq_bronchit_f_b` double,
    `bq_polyps_f_b` double,
    `bq_ulcerative_colitits_b` double,
    `bq_crohns_disease_b` double,
    `bq_familial_polyposis_b` double,
    `bq_hepatitis_b` double,
    `bq_cirrhosis_b` double,
    `bq_divertic_f_b` double,
    `bq_gallblad_f_b` double,
    `bq_age_co` double,
    `bq_race7_ca` double,
    `bq_hispanic_f_b` double,
    `bq_surg_resection_b` double,
    `bq_surg_prostatectomy_b` double,
    `bq_hyster_f_b` double,
    `bq_ovariesr_f_ca` double,
    `bq_infpros_f_b` double,
    `bq_urinate_f_o` double,
    `bq_smoked_f_b` double,
    `bq_smokea_f_co` double,
    `bq_ssmokea_f_co` double,
    `bq_cig_stop_co` double,
    `bq_bmi_20_co` double,
    `bq_bmi_50_co` double,
    `bq_bmi_curr_co` double,
    `bq_weight_f_co` double,
    `bq_weight20_f_co` double,
    `bq_weight50_f_co` double,
    `bq_height_f_co` double,
    `bq_fh_cancer_b` double,
    `center` double,
    `arm` double,
    `sex` double,
    `dqx_age_co` double,
    `dqx_qxn_physicact_40_o` double,
    `dqx_qxn_physicact_now_o` double,
    `sqx_age_co` double,
    `sqx_sit_ht_o` double,
    `sqx_waist_hip_o` double,
    `sqx_height_co` double,
    `sqx_wt30s_co` double,
    `sqx_wt40s_co` double,
    `sqx_wt50s_co` double,
    `sqx_wt60s_co` double,
    `sqx_wt70s_co` double,
    `sqx_wt_curr_co` double,
    `sqx_bmi30s_co` double,
    `sqx_bmi40s_co` double,
    `sqx_bmi50s_co` double,
    `sqx_bmi60s_co` double,
    `sqx_bmi70s_co` double,
    `sqx_bmi_curr_co` double,
    `sqx_cholesterol_b` double,
    `sqx_asthma_b` double,
    `sqxbq_hearta_b` double,
    `sqxbq_stroke_b` double,
    `sqxbq_hyperten_b` double,
    `sqxbq_diabetes_b` double,
    `sqxbq_osteopor_b` double,
    `sqxbq_emphysema_b` double,
    `sqxbq_arthritis_b` double,
    `sqx_broke_hip_b` double,
    `sqx_broke_arm_b` double,
    `sqx_broke_vertebra_b` double,
    `sqx_broke_none_b` double,
    `sqx_balding_trend_o` double,
    `sqx_urinate_o` double,
    `sqxbq_bpha_o` double,
    `sqxbq_bph_b` double,
    `sqx_lift_weights_b` double,
    `sqx_lift_weights_lev_o` double,
    `sqx_active_b` double,
    `sqx_fh_blad_b` double,
    `sqx_fh_breast_b` double,
    `sqx_fh_colo_b` double,
    `sqx_fh_endo_b` double,
    `sqx_fh_leuk_b` double,
    `sqx_fh_lung_b` double,
    `sqx_fh_lymph_b` double,
    `sqx_fh_ovar_b` double,
    `sqx_fh_pros_b` double,
    `sqx_fh_cancer_f_b` double,
    `sqx_twins_b` double,
    `sqx_smk100_b` double,
    `sqx_amt_smk_o` double,
    `sqx_smk_crave1_b` double,
    `sqx_smk_crave2_b` double,
    `sqx_smk_crave3_b` double,
    `sqx_smk_crave4_b` double,
    `sqx_smk_try_quit_b` double,
    `sqx_smk_age_quit_co` double,
    `sqx_worry_lungca_o` double,
    `sqx_risk_lungca_o` double,
    `sqx_smk_his_co` double,
    `sqx_smk_behv_co` double,
    `sqx_smk_ftnd_co` double,
    `sqx_years_quit_co` double,
    `sqx_cig_years_co` double,
    `sqx_gain_chest_shoulders_b` double,
    `sqx_gain_waist_stomach_b` double,
    `sqx_gain_hips_thighs_b` double,
    `sqx_gain_equally_over_b` double,
    `sqx_lose_chest_shoulders_b` double,
    `sqx_lose_waist_stomach_b` double,
    `sqx_lose_hips_thighs_b` double,
    `sqx_lose_equally_over_b` double,
    `sqxbq_rheumatoid_arthritis_b` double,
    `sqxbq_osteoarthritis_b` double,
    `sqx_moderate_week_co` double,
    `sqx_strenuous_week_co` double,
    `sqx_ever_balding_b` double,
    `sqx_top_bald_b` double,
    `bq_menstr_natural_o` double,
    `sqx_current_cigarette_b` double,
    `sqxbq_relapse_b` double,
    `bq_current_cigarette_b` double,
    `bq_cig_stat_o` double,
    `bq_cig_years_co` double,
    `bq_cigar_o` double,
    `bq_cigpd_f_o` double,
    `bq_filtered_f_b` double,
    `bq_pack_years_co` double,
    `bq_pipe_o` double,
    `sqx_pace_o` double,
    `sqx_stairs_o` double,
    `sqx_walk_mi_o` double,
    `pack_years_bqelsesqx_co` double,
    `sqx_smk_exp_adult_o` double,
    `sqx_smk_lgt_ca` double,
    `sqx_smk_menthol_b` double,
    `sqx_smk_plan_quit_o` double,
    `sqx_smk_wake_o` double,
    `sqx_smk30days_b` double,
    `sqxo_cig_stat_o` double,
    `sqx_urinatea_o` double,
    `sv_coffee_reg_nosug_dhq` double,
    `sv_coffee_decaf_nosug_dhq` double,
    `mped_fruit_nojuice_dhq` double,
    `dt_alc_alc_drinks_dhq` double,
    `drinker_dhq` double,
    `g_candy_choc_dhq` double,
    `g_red5_dhq` double,
    `g_process_6_dhq` double,
    `g_fruit_dhq` double,
    `g_vegetable_dhq` double,
    `g_fish_total_dhq` double,
    `g_salty_grain_snack_dhq` double,
    `g_fruit_citrus_dhq` double,
    `g_soda_reg_dhq` double,
    `dt_kcal_dhq` double,
    `dt_prot_dhq` double,
    `dt_fat_dhq` double,
    `dt_carb_dhq` double,
    `dt_fiber_csfii_dhq` double,
    `dt_caffeine_dhq` double,
    `gly_load_dhq` double,
    `mped_grain_dhq` double,
    `mped_grain_whole_dhq` double,
    `mped_veg_dark_green_dhq` double,
    `mped_dairy_dhq` double,
    `mped_dairy_milk_dhq` double,
    `mped_m_soy_dhq` double,
    `mped_m_nut_seed_dhq` double,
    `mped_legume_dhq` double,
    `mped_added_sugar_dhq` double,
    `pe_fr_protein_dhq` double,
    `pe_fr_fat_dhq` double,
    `pe_fr_carb_dhq` double,
    `pe_fr_alc_dhq` double,
    `gly_index_dhq` double,
    `dt_sugar_dhq` double,
    `age_dhq` double,
    `dhq_completedvalid` double,
    `mped_alc_bev_alc_drinks18_dhq` double,
    `mped_alc_bev_alc_drinks25_dhq` double,
    `mped_alc_bev_alc_drinks40_dhq` double,
    `mped_alc_bev_alc_drinks55_dhq` double,
    `qxn_f_coffee_dhq` double,
    `whfrden_dhq` double,
    `grnden_dhq` double,
    `wgrnden_dhq` double,
    `dairyden_dhq` double,
    `hei2005_total_score_dhq` double,
    `hei2010_total_score_dhq` double,
    `addsug_perc2015_dhq` double,
    `hei2015_total_score_dhq` double,
    `saltsnkden_g_dhq` double,
    `milkden_dhq` double,
    `frtden_g_dhq` double,
    `citfrtden_g_dhq` double,
    `vegtotden_g_dhq` double,
    `dkgrvegden_dhq` double,
    `legumeden_dhq` double,
    `nutden_dhq` double,
    `redmtden_g_dhq` double,
    `procmtden_g_dhq` double,
    `fishden_g_dhq` double,
    `soyden_dhq` double,
    `current_drinker` double,
    `former_drinker` double,
    `drinker_status_dhq_o` double,
    `ph_status` double,
    `first_psa_level` double,
    `first_psa_year` double,
    `first_ca125_level` double,
    `first_ca125_year` double,
    `adenoma_stat` double,
    `adenoma_fup_age` double,
    `adenoma_dx_age` double,
    `advanced_adenoma_stat` double,
    `advanced_adenoma_fup_age` double,
    `advanced_adenoma_dx_age` double,
    `non_advanced_adenoma_stat` double,
    `non_advanced_adenoma_fup_age` double,
    `non_advanced_adenoma_dx_age` double
) ENGINE=MYISAM;

-- load data into staging table (na)
LOAD DATA LOCAL INFILE "../raw/participant_data.tsv" INTO TABLE participant_data_stage
    FIELDS TERMINATED BY '\t'
    IGNORE 1 ROWS (
        plco_id,
        @chf_cat,
        @ischemicheart_cat,
        @depression_cat,
        @diabetes_cat,
        @ra_oa_cat,
        @chronickidney_cat,
        @copd_cat,
        @atrial_fib_cat,
        @alzh_cat,
        @alzh_demen_cat,
        @any_use,
        @part_d_mos,
        @chronic,
        @part_d_yrs,
        @j_adeno_carcinoma,
        @j_adeno_carcinoma_fup_days,
        @j_adeno_carcinoma_fup_age,
        @j_adeno_carcinoma_dx_age,
        @j_alcohol_related_dx_age,
        @j_alcohol_related,
        @j_alcohol_related_fup_age,
        @j_alcohol_related_fup_days,
        @j_bcell,
        @j_bcell_fup_days,
        @j_bcell_fup_age,
        @j_bcell_dx_age,
        @j_bili_cancer,
        @j_bili_cancer_fup_days,
        @j_bili_cancer_fup_age,
        @j_bili_cancer_dx_age,
        @j_blad_cancer,
        @j_blad_cancer_fup_days,
        @j_blad_cancer_fup_age,
        @j_blad_cancer_dx_age,
        @j_breast_cancer,
        @j_breast_cancer_fup_days,
        @j_breast_cancer_fup_age,
        @j_breast_cancer_dx_age,
        @j_breast_invasive,
        @j_breast_insitu,
        @j_breast_ductal,
        @j_breast_lobular,
        @j_breast_tubular,
        @j_breast_er_pos_or_equiv,
        @j_breast_er_neg,
        @j_breast_pr_pos_or_equiv,
        @j_breast_pr_neg,
        @j_breast_er_or_pr_pos,
        @j_breast_er_and_pr_neg,
        @j_breast_her2_pos_or_equiv,
        @j_breast_her2_neg,
        @j_breast_er_pr_and_her2_neg,
        @j_breast_grade34,
        @j_breast_grade2,
        @j_breast_grade1,
        @j_carcinoma,
        @j_carcinoma_fup_days,
        @j_carcinoma_fup_age,
        @j_carcinoma_dx_age,
        @j_colo_cancer,
        @j_colo_cancer_fup_days,
        @j_colo_cancer_fup_age,
        @j_colo_cancer_dx_age,
        @j_colo_distal,
        @j_colo_distal_proximal,
        @j_colo_proximal,
        @j_colo_rectal,
        @j_diabetes_related_dx_age,
        @j_diabetes_related,
        @j_diabetes_related_fup_age,
        @j_diabetes_related_fup_days,
        @j_ebv_related_dx_age,
        @j_ebv_related,
        @j_ebv_related_fup_age,
        @j_ebv_related_fup_days,
        @j_endo_cancer,
        @j_endo_cancer_fup_days,
        @j_endo_cancer_fup_age,
        @j_endo_cancer_dx_age,
        @j_endo_neuro,
        @j_endo_neuro_fup_days,
        @j_endo_neuro_fup_age,
        @j_endo_neuro_dx_age,
        @j_esoph_cancer,
        @j_esoph_cancer_fup_days,
        @j_esoph_cancer_fup_age,
        @j_esoph_cancer_dx_age,
        @j_esoph_adeno_carcinoma,
        @j_esoph_squamous,
        @j_hbv_related_dx_age,
        @j_hbv_related,
        @j_hbv_related_fup_age,
        @j_hbv_related_fup_days,
        @j_hcv_related_dx_age,
        @j_hcv_related,
        @j_hcv_related_fup_age,
        @j_hcv_related_fup_days,
        @j_height_related_dx_age,
        @j_height_related,
        @j_height_related_fup_age,
        @j_height_related_fup_days,
        @j_helicobacter_related_dx_age,
        @j_helicobacter_related,
        @j_helicobacter_related_fup_age,
        @j_helicobacter_related_fup_days,
        @j_hematologic,
        @j_hematologic_fup_days,
        @j_hematologic_fup_age,
        @j_hematologic_dx_age,
        @j_hnc_cancer,
        @j_hnc_cancer_fup_days,
        @j_hnc_cancer_fup_age,
        @j_hnc_cancer_dx_age,
        @j_hnc_larynx,
        @j_hnc_lip_oral_pharynx,
        @j_hnc_naso_mid_sinus,
        @j_hpv_related_dx_age,
        @j_hpv_related,
        @j_hpv_related_fup_age,
        @j_hpv_related_fup_days,
        @j_infection_related_dx_age,
        @j_infection_related,
        @j_infection_related_fup_age,
        @j_infection_related_fup_days,
        @j_kidney_cancer_fup_days,
        @j_kidney_cancer_fup_age,
        @j_kidney_cancer_dx_age,
        @j_kidney_cancer,
        @j_kidney_renalcell_clearcell,
        @j_kidney_renalcell_nos,
        @j_gast_cancer,
        @j_gast_cancer_fup_days,
        @j_gast_cancer_fup_age,
        @j_gast_cancer_dx_age,
        @j_gast_cardia,
        @j_gast_noncardia,
        @j_glio_cancer,
        @j_glio_cancer_fup_days,
        @j_glio_cancer_fup_age,
        @j_glio_cancer_dx_age,
        @j_liver_xintra_cancer_fup_days,
        @j_liver_xintra_cancer_fup_age,
        @j_liver_xintra_cancer_dx_age,
        @j_liver_xintra_cancer,
        @j_lung_cancer,
        @j_lung_cancer_fup_days,
        @j_lung_cancer_fup_age,
        @j_lung_cancer_dx_age,
        @j_lung_smallcell,
        @j_lung_adeno,
        @j_lung_squam,
        @j_lymphoid,
        @j_lymphoid_fup_days,
        @j_lymphoid_fup_age,
        @j_lymphoid_dx_age,
        @j_cll,
        @j_cll_fup_days,
        @j_cll_fup_age,
        @j_cll_dx_age,
        @j_mbreast_cancer,
        @j_mbreast_cancer_fup_days,
        @j_mbreast_cancer_fup_age,
        @j_mbreast_cancer_dx_age,
        @j_mela_cancer,
        @j_mela_cancer_fup_days,
        @j_mela_cancer_fup_age,
        @j_mela_cancer_dx_age,
        @j_mela_invasive_cancer,
        @j_mela_invasive_cancer_fup_age,
        @j_mela_invasive_cancer_dx_age,
        @j_mela_invasive_cancer_fup_days,
        @j_mesoth,
        @j_mesoth_fup_days,
        @j_mesoth_fup_age,
        @j_mesoth_dx_age,
        @j_myeloid,
        @j_myeloid_fup_days,
        @j_myeloid_fup_age,
        @j_myeloid_dx_age,
        @j_obesity_related_dx_age,
        @j_obesity_related,
        @j_obesity_related_fup_age,
        @j_obesity_related_fup_days,
        @j_osumm_cancer,
        @j_osumm_cancer_fup_days,
        @j_osumm_cancer_fup_age,
        @j_osumm_cancer_dx_age,
        @j_osumm_serous_grade_high,
        @j_panc_cancer,
        @j_panc_cancer_fup_days,
        @j_panc_cancer_fup_age,
        @j_panc_cancer_dx_age,
        @j_phys_act_related_dx_age,
        @j_phys_act_related,
        @j_phys_act_related_fup_age,
        @j_phys_act_related_fup_days,
        @j_pros_cancer,
        @j_pros_cancer_fup_days,
        @j_pros_cancer_fup_age,
        @j_pros_cancer_dx_age,
        @j_pros_non_advanced,
        @j_pros_advanced_including7,
        @j_pros_advanced_excluding7,
        @j_sarcoma,
        @j_sarcoma_fup_days,
        @j_sarcoma_fup_age,
        @j_sarcoma_dx_age,
        @j_smoking_related_dx_age,
        @j_smoking_related,
        @j_smoking_related_fup_age,
        @j_smoking_related_fup_days,
        @j_solid_tumor,
        @j_solid_tumor_fup_days,
        @j_solid_tumor_fup_age,
        @j_solid_tumor_dx_age,
        @j_squamous,
        @j_squamous_fup_days,
        @j_squamous_fup_age,
        @j_squamous_dx_age,
        @j_thyd_cancer,
        @j_thyd_cancer_fup_days,
        @j_thyd_cancer_fup_age,
        @j_thyd_cancer_dx_age,
        @j_upgi_cancer,
        @j_upgi_cancer_fup_days,
        @j_upgi_cancer_fup_age,
        @j_upgi_cancer_dx_age,
        @j_urothelial,
        @j_urothelial_fup_days,
        @j_urothelial_fup_age,
        @j_urothelial_dx_age,
        @is_dead,
        @mortality_exitage,
        @dth_days,
        @mortality_exitdays_unadj,
        @f_death_ischemic,
        @f_death_cerebrovascular,
        @f_death_rheumatic,
        @f_death_hypertensive,
        @f_death_peripheral,
        @f_death_heart,
        @f_death_cardiac,
        @f_death_arrhythmia,
        @f_death_endocarditis,
        @f_death_cardiovascular,
        @f_death_cancer,
        @f_death_chronicresp,
        @f_death_alzheimers,
        @f_death_diabetes,
        @f_death_nephritis,
        @f_death_chronicliver,
        @f_death_parkinsons,
        @bq_educat_o,
        @bq_marital_co,
        @bq_fmenstr_o,
        @bq_tubal_o,
        @bq_bbd_b,
        @bq_benign_ovcyst_b,
        @bq_endometriosis_b,
        @bq_uterine_fib_b,
        @bq_trypreg_b,
        @bq_urinatea_o,
        @bq_infprosa_o,
        @bq_hearta_f_b,
        @bq_bronchit_f_b,
        @bq_polyps_f_b,
        @bq_ulcerative_colitits_b,
        @bq_crohns_disease_b,
        @bq_familial_polyposis_b,
        @bq_hepatitis_b,
        @bq_cirrhosis_b,
        @bq_divertic_f_b,
        @bq_gallblad_f_b,
        @bq_age_co,
        @bq_race7_ca,
        @bq_hispanic_f_b,
        @bq_surg_resection_b,
        @bq_surg_prostatectomy_b,
        @bq_hyster_f_b,
        @bq_ovariesr_f_ca,
        @bq_infpros_f_b,
        @bq_urinate_f_o,
        @bq_smoked_f_b,
        @bq_smokea_f_co,
        @bq_ssmokea_f_co,
        @bq_cig_stop_co,
        @bq_bmi_20_co,
        @bq_bmi_50_co,
        @bq_bmi_curr_co,
        @bq_weight_f_co,
        @bq_weight20_f_co,
        @bq_weight50_f_co,
        @bq_height_f_co,
        @bq_fh_cancer_b,
        @center,
        @arm,
        @sex,
        @dqx_age_co,
        @dqx_qxn_physicact_40_o,
        @dqx_qxn_physicact_now_o,
        @sqx_age_co,
        @sqx_sit_ht_o,
        @sqx_waist_hip_o,
        @sqx_height_co,
        @sqx_wt30s_co,
        @sqx_wt40s_co,
        @sqx_wt50s_co,
        @sqx_wt60s_co,
        @sqx_wt70s_co,
        @sqx_wt_curr_co,
        @sqx_bmi30s_co,
        @sqx_bmi40s_co,
        @sqx_bmi50s_co,
        @sqx_bmi60s_co,
        @sqx_bmi70s_co,
        @sqx_bmi_curr_co,
        @sqx_cholesterol_b,
        @sqx_asthma_b,
        @sqxbq_hearta_b,
        @sqxbq_stroke_b,
        @sqxbq_hyperten_b,
        @sqxbq_diabetes_b,
        @sqxbq_osteopor_b,
        @sqxbq_emphysema_b,
        @sqxbq_arthritis_b,
        @sqx_broke_hip_b,
        @sqx_broke_arm_b,
        @sqx_broke_vertebra_b,
        @sqx_broke_none_b,
        @sqx_balding_trend_o,
        @sqx_urinate_o,
        @sqxbq_bpha_o,
        @sqxbq_bph_b,
        @sqx_lift_weights_b,
        @sqx_lift_weights_lev_o,
        @sqx_active_b,
        @sqx_fh_blad_b,
        @sqx_fh_breast_b,
        @sqx_fh_colo_b,
        @sqx_fh_endo_b,
        @sqx_fh_leuk_b,
        @sqx_fh_lung_b,
        @sqx_fh_lymph_b,
        @sqx_fh_ovar_b,
        @sqx_fh_pros_b,
        @sqx_fh_cancer_f_b,
        @sqx_twins_b,
        @sqx_smk100_b,
        @sqx_amt_smk_o,
        @sqx_smk_crave1_b,
        @sqx_smk_crave2_b,
        @sqx_smk_crave3_b,
        @sqx_smk_crave4_b,
        @sqx_smk_try_quit_b,
        @sqx_smk_age_quit_co,
        @sqx_worry_lungca_o,
        @sqx_risk_lungca_o,
        @sqx_smk_his_co,
        @sqx_smk_behv_co,
        @sqx_smk_ftnd_co,
        @sqx_years_quit_co,
        @sqx_cig_years_co,
        @sqx_gain_chest_shoulders_b,
        @sqx_gain_waist_stomach_b,
        @sqx_gain_hips_thighs_b,
        @sqx_gain_equally_over_b,
        @sqx_lose_chest_shoulders_b,
        @sqx_lose_waist_stomach_b,
        @sqx_lose_hips_thighs_b,
        @sqx_lose_equally_over_b,
        @sqxbq_rheumatoid_arthritis_b,
        @sqxbq_osteoarthritis_b,
        @sqx_moderate_week_co,
        @sqx_strenuous_week_co,
        @sqx_ever_balding_b,
        @sqx_top_bald_b,
        @bq_menstr_natural_o,
        @sqx_current_cigarette_b,
        @sqxbq_relapse_b,
        @bq_current_cigarette_b,
        @bq_cig_stat_o,
        @bq_cig_years_co,
        @bq_cigar_o,
        @bq_cigpd_f_o,
        @bq_filtered_f_b,
        @bq_pack_years_co,
        @bq_pipe_o,
        @sqx_pace_o,
        @sqx_stairs_o,
        @sqx_walk_mi_o,
        @pack_years_bqelsesqx_co,
        @sqx_smk_exp_adult_o,
        @sqx_smk_lgt_ca,
        @sqx_smk_menthol_b,
        @sqx_smk_plan_quit_o,
        @sqx_smk_wake_o,
        @sqx_smk30days_b,
        @sqxo_cig_stat_o,
        @sqx_urinatea_o,
        @sv_coffee_reg_nosug_dhq,
        @sv_coffee_decaf_nosug_dhq,
        @mped_fruit_nojuice_dhq,
        @dt_alc_alc_drinks_dhq,
        @drinker_dhq,
        @g_candy_choc_dhq,
        @g_red5_dhq,
        @g_process_6_dhq,
        @g_fruit_dhq,
        @g_vegetable_dhq,
        @g_fish_total_dhq,
        @g_salty_grain_snack_dhq,
        @g_fruit_citrus_dhq,
        @g_soda_reg_dhq,
        @dt_kcal_dhq,
        @dt_prot_dhq,
        @dt_fat_dhq,
        @dt_carb_dhq,
        @dt_fiber_csfii_dhq,
        @dt_caffeine_dhq,
        @gly_load_dhq,
        @mped_grain_dhq,
        @mped_grain_whole_dhq,
        @mped_veg_dark_green_dhq,
        @mped_dairy_dhq,
        @mped_dairy_milk_dhq,
        @mped_m_soy_dhq,
        @mped_m_nut_seed_dhq,
        @mped_legume_dhq,
        @mped_added_sugar_dhq,
        @pe_fr_protein_dhq,
        @pe_fr_fat_dhq,
        @pe_fr_carb_dhq,
        @pe_fr_alc_dhq,
        @gly_index_dhq,
        @dt_sugar_dhq,
        @age_dhq,
        @dhq_completedvalid,
        @mped_alc_bev_alc_drinks18_dhq,
        @mped_alc_bev_alc_drinks25_dhq,
        @mped_alc_bev_alc_drinks40_dhq,
        @mped_alc_bev_alc_drinks55_dhq,
        @qxn_f_coffee_dhq,
        @whfrden_dhq,
        @grnden_dhq,
        @wgrnden_dhq,
        @dairyden_dhq,
        @hei2005_total_score_dhq,
        @hei2010_total_score_dhq,
        @addsug_perc2015_dhq,
        @hei2015_total_score_dhq,
        @saltsnkden_g_dhq,
        @milkden_dhq,
        @frtden_g_dhq,
        @citfrtden_g_dhq,
        @vegtotden_g_dhq,
        @dkgrvegden_dhq,
        @legumeden_dhq,
        @nutden_dhq,
        @redmtden_g_dhq,
        @procmtden_g_dhq,
        @fishden_g_dhq,
        @soyden_dhq,
        @current_drinker,
        @former_drinker,
        @drinker_status_dhq_o,
        @ph_status,
        @first_psa_level,
        @first_psa_year,
        @first_ca125_level,
        @first_ca125_year,
        @adenoma_stat,
        @adenoma_fup_age,
        @adenoma_dx_age,
        @advanced_adenoma_stat,
        @advanced_adenoma_fup_age,
        @advanced_adenoma_dx_age,
        @non_advanced_adenoma_stat,
        @non_advanced_adenoma_fup_age,
        @non_advanced_adenoma_dx_age
    ) SET
        plco_id = if(@plco_id in('NA', ''), null, @plco_id),
        chf_cat = if(@chf_cat in('NA', ''), null, @chf_cat),
        ischemicheart_cat = if(@ischemicheart_cat in('NA', ''), null, @ischemicheart_cat),
        depression_cat = if(@depression_cat in('NA', ''), null, @depression_cat),
        diabetes_cat = if(@diabetes_cat in('NA', ''), null, @diabetes_cat),
        ra_oa_cat = if(@ra_oa_cat in('NA', ''), null, @ra_oa_cat),
        chronickidney_cat = if(@chronickidney_cat in('NA', ''), null, @chronickidney_cat),
        copd_cat = if(@copd_cat in('NA', ''), null, @copd_cat),
        atrial_fib_cat = if(@atrial_fib_cat in('NA', ''), null, @atrial_fib_cat),
        alzh_cat = if(@alzh_cat in('NA', ''), null, @alzh_cat),
        alzh_demen_cat = if(@alzh_demen_cat in('NA', ''), null, @alzh_demen_cat),
        any_use = if(@any_use in('NA', ''), null, @any_use),
        part_d_mos = if(@part_d_mos in('NA', ''), null, @part_d_mos),
        chronic = if(@chronic in('NA', ''), null, @chronic),
        part_d_yrs = if(@part_d_yrs in('NA', ''), null, @part_d_yrs),
        j_adeno_carcinoma = if(@j_adeno_carcinoma in('NA', ''), null, @j_adeno_carcinoma),
        j_adeno_carcinoma_fup_days = if(@j_adeno_carcinoma_fup_days in('NA', ''), null, @j_adeno_carcinoma_fup_days),
        j_adeno_carcinoma_fup_age = if(@j_adeno_carcinoma_fup_age in('NA', ''), null, @j_adeno_carcinoma_fup_age),
        j_adeno_carcinoma_dx_age = if(@j_adeno_carcinoma_dx_age in('NA', ''), null, @j_adeno_carcinoma_dx_age),
        j_alcohol_related_dx_age = if(@j_alcohol_related_dx_age in('NA', ''), null, @j_alcohol_related_dx_age),
        j_alcohol_related = if(@j_alcohol_related in('NA', ''), null, @j_alcohol_related),
        j_alcohol_related_fup_age = if(@j_alcohol_related_fup_age in('NA', ''), null, @j_alcohol_related_fup_age),
        j_alcohol_related_fup_days = if(@j_alcohol_related_fup_days in('NA', ''), null, @j_alcohol_related_fup_days),
        j_bcell = if(@j_bcell in('NA', ''), null, @j_bcell),
        j_bcell_fup_days = if(@j_bcell_fup_days in('NA', ''), null, @j_bcell_fup_days),
        j_bcell_fup_age = if(@j_bcell_fup_age in('NA', ''), null, @j_bcell_fup_age),
        j_bcell_dx_age = if(@j_bcell_dx_age in('NA', ''), null, @j_bcell_dx_age),
        j_bili_cancer = if(@j_bili_cancer in('NA', ''), null, @j_bili_cancer),
        j_bili_cancer_fup_days = if(@j_bili_cancer_fup_days in('NA', ''), null, @j_bili_cancer_fup_days),
        j_bili_cancer_fup_age = if(@j_bili_cancer_fup_age in('NA', ''), null, @j_bili_cancer_fup_age),
        j_bili_cancer_dx_age = if(@j_bili_cancer_dx_age in('NA', ''), null, @j_bili_cancer_dx_age),
        j_blad_cancer = if(@j_blad_cancer in('NA', ''), null, @j_blad_cancer),
        j_blad_cancer_fup_days = if(@j_blad_cancer_fup_days in('NA', ''), null, @j_blad_cancer_fup_days),
        j_blad_cancer_fup_age = if(@j_blad_cancer_fup_age in('NA', ''), null, @j_blad_cancer_fup_age),
        j_blad_cancer_dx_age = if(@j_blad_cancer_dx_age in('NA', ''), null, @j_blad_cancer_dx_age),
        j_breast_cancer = if(@j_breast_cancer in('NA', ''), null, @j_breast_cancer),
        j_breast_cancer_fup_days = if(@j_breast_cancer_fup_days in('NA', ''), null, @j_breast_cancer_fup_days),
        j_breast_cancer_fup_age = if(@j_breast_cancer_fup_age in('NA', ''), null, @j_breast_cancer_fup_age),
        j_breast_cancer_dx_age = if(@j_breast_cancer_dx_age in('NA', ''), null, @j_breast_cancer_dx_age),
        j_breast_invasive = if(@j_breast_invasive in('NA', ''), null, @j_breast_invasive),
        j_breast_insitu = if(@j_breast_insitu in('NA', ''), null, @j_breast_insitu),
        j_breast_ductal = if(@j_breast_ductal in('NA', ''), null, @j_breast_ductal),
        j_breast_lobular = if(@j_breast_lobular in('NA', ''), null, @j_breast_lobular),
        j_breast_tubular = if(@j_breast_tubular in('NA', ''), null, @j_breast_tubular),
        j_breast_er_pos_or_equiv = if(@j_breast_er_pos_or_equiv in('NA', ''), null, @j_breast_er_pos_or_equiv),
        j_breast_er_neg = if(@j_breast_er_neg in('NA', ''), null, @j_breast_er_neg),
        j_breast_pr_pos_or_equiv = if(@j_breast_pr_pos_or_equiv in('NA', ''), null, @j_breast_pr_pos_or_equiv),
        j_breast_pr_neg = if(@j_breast_pr_neg in('NA', ''), null, @j_breast_pr_neg),
        j_breast_er_or_pr_pos = if(@j_breast_er_or_pr_pos in('NA', ''), null, @j_breast_er_or_pr_pos),
        j_breast_er_and_pr_neg = if(@j_breast_er_and_pr_neg in('NA', ''), null, @j_breast_er_and_pr_neg),
        j_breast_her2_pos_or_equiv = if(@j_breast_her2_pos_or_equiv in('NA', ''), null, @j_breast_her2_pos_or_equiv),
        j_breast_her2_neg = if(@j_breast_her2_neg in('NA', ''), null, @j_breast_her2_neg),
        j_breast_er_pr_and_her2_neg = if(@j_breast_er_pr_and_her2_neg in('NA', ''), null, @j_breast_er_pr_and_her2_neg),
        j_breast_grade34 = if(@j_breast_grade34 in('NA', ''), null, @j_breast_grade34),
        j_breast_grade2 = if(@j_breast_grade2 in('NA', ''), null, @j_breast_grade2),
        j_breast_grade1 = if(@j_breast_grade1 in('NA', ''), null, @j_breast_grade1),
        j_carcinoma = if(@j_carcinoma in('NA', ''), null, @j_carcinoma),
        j_carcinoma_fup_days = if(@j_carcinoma_fup_days in('NA', ''), null, @j_carcinoma_fup_days),
        j_carcinoma_fup_age = if(@j_carcinoma_fup_age in('NA', ''), null, @j_carcinoma_fup_age),
        j_carcinoma_dx_age = if(@j_carcinoma_dx_age in('NA', ''), null, @j_carcinoma_dx_age),
        j_colo_cancer = if(@j_colo_cancer in('NA', ''), null, @j_colo_cancer),
        j_colo_cancer_fup_days = if(@j_colo_cancer_fup_days in('NA', ''), null, @j_colo_cancer_fup_days),
        j_colo_cancer_fup_age = if(@j_colo_cancer_fup_age in('NA', ''), null, @j_colo_cancer_fup_age),
        j_colo_cancer_dx_age = if(@j_colo_cancer_dx_age in('NA', ''), null, @j_colo_cancer_dx_age),
        j_colo_distal = if(@j_colo_distal in('NA', ''), null, @j_colo_distal),
        j_colo_distal_proximal = if(@j_colo_distal_proximal in('NA', ''), null, @j_colo_distal_proximal),
        j_colo_proximal = if(@j_colo_proximal in('NA', ''), null, @j_colo_proximal),
        j_colo_rectal = if(@j_colo_rectal in('NA', ''), null, @j_colo_rectal),
        j_diabetes_related_dx_age = if(@j_diabetes_related_dx_age in('NA', ''), null, @j_diabetes_related_dx_age),
        j_diabetes_related = if(@j_diabetes_related in('NA', ''), null, @j_diabetes_related),
        j_diabetes_related_fup_age = if(@j_diabetes_related_fup_age in('NA', ''), null, @j_diabetes_related_fup_age),
        j_diabetes_related_fup_days = if(@j_diabetes_related_fup_days in('NA', ''), null, @j_diabetes_related_fup_days),
        j_ebv_related_dx_age = if(@j_ebv_related_dx_age in('NA', ''), null, @j_ebv_related_dx_age),
        j_ebv_related = if(@j_ebv_related in('NA', ''), null, @j_ebv_related),
        j_ebv_related_fup_age = if(@j_ebv_related_fup_age in('NA', ''), null, @j_ebv_related_fup_age),
        j_ebv_related_fup_days = if(@j_ebv_related_fup_days in('NA', ''), null, @j_ebv_related_fup_days),
        j_endo_cancer = if(@j_endo_cancer in('NA', ''), null, @j_endo_cancer),
        j_endo_cancer_fup_days = if(@j_endo_cancer_fup_days in('NA', ''), null, @j_endo_cancer_fup_days),
        j_endo_cancer_fup_age = if(@j_endo_cancer_fup_age in('NA', ''), null, @j_endo_cancer_fup_age),
        j_endo_cancer_dx_age = if(@j_endo_cancer_dx_age in('NA', ''), null, @j_endo_cancer_dx_age),
        j_endo_neuro = if(@j_endo_neuro in('NA', ''), null, @j_endo_neuro),
        j_endo_neuro_fup_days = if(@j_endo_neuro_fup_days in('NA', ''), null, @j_endo_neuro_fup_days),
        j_endo_neuro_fup_age = if(@j_endo_neuro_fup_age in('NA', ''), null, @j_endo_neuro_fup_age),
        j_endo_neuro_dx_age = if(@j_endo_neuro_dx_age in('NA', ''), null, @j_endo_neuro_dx_age),
        j_esoph_cancer = if(@j_esoph_cancer in('NA', ''), null, @j_esoph_cancer),
        j_esoph_cancer_fup_days = if(@j_esoph_cancer_fup_days in('NA', ''), null, @j_esoph_cancer_fup_days),
        j_esoph_cancer_fup_age = if(@j_esoph_cancer_fup_age in('NA', ''), null, @j_esoph_cancer_fup_age),
        j_esoph_cancer_dx_age = if(@j_esoph_cancer_dx_age in('NA', ''), null, @j_esoph_cancer_dx_age),
        j_esoph_adeno_carcinoma = if(@j_esoph_adeno_carcinoma in('NA', ''), null, @j_esoph_adeno_carcinoma),
        j_esoph_squamous = if(@j_esoph_squamous in('NA', ''), null, @j_esoph_squamous),
        j_hbv_related_dx_age = if(@j_hbv_related_dx_age in('NA', ''), null, @j_hbv_related_dx_age),
        j_hbv_related = if(@j_hbv_related in('NA', ''), null, @j_hbv_related),
        j_hbv_related_fup_age = if(@j_hbv_related_fup_age in('NA', ''), null, @j_hbv_related_fup_age),
        j_hbv_related_fup_days = if(@j_hbv_related_fup_days in('NA', ''), null, @j_hbv_related_fup_days),
        j_hcv_related_dx_age = if(@j_hcv_related_dx_age in('NA', ''), null, @j_hcv_related_dx_age),
        j_hcv_related = if(@j_hcv_related in('NA', ''), null, @j_hcv_related),
        j_hcv_related_fup_age = if(@j_hcv_related_fup_age in('NA', ''), null, @j_hcv_related_fup_age),
        j_hcv_related_fup_days = if(@j_hcv_related_fup_days in('NA', ''), null, @j_hcv_related_fup_days),
        j_height_related_dx_age = if(@j_height_related_dx_age in('NA', ''), null, @j_height_related_dx_age),
        j_height_related = if(@j_height_related in('NA', ''), null, @j_height_related),
        j_height_related_fup_age = if(@j_height_related_fup_age in('NA', ''), null, @j_height_related_fup_age),
        j_height_related_fup_days = if(@j_height_related_fup_days in('NA', ''), null, @j_height_related_fup_days),
        j_helicobacter_related_dx_age = if(@j_helicobacter_related_dx_age in('NA', ''), null, @j_helicobacter_related_dx_age),
        j_helicobacter_related = if(@j_helicobacter_related in('NA', ''), null, @j_helicobacter_related),
        j_helicobacter_related_fup_age = if(@j_helicobacter_related_fup_age in('NA', ''), null, @j_helicobacter_related_fup_age),
        j_helicobacter_related_fup_days = if(@j_helicobacter_related_fup_days in('NA', ''), null, @j_helicobacter_related_fup_days),
        j_hematologic = if(@j_hematologic in('NA', ''), null, @j_hematologic),
        j_hematologic_fup_days = if(@j_hematologic_fup_days in('NA', ''), null, @j_hematologic_fup_days),
        j_hematologic_fup_age = if(@j_hematologic_fup_age in('NA', ''), null, @j_hematologic_fup_age),
        j_hematologic_dx_age = if(@j_hematologic_dx_age in('NA', ''), null, @j_hematologic_dx_age),
        j_hnc_cancer = if(@j_hnc_cancer in('NA', ''), null, @j_hnc_cancer),
        j_hnc_cancer_fup_days = if(@j_hnc_cancer_fup_days in('NA', ''), null, @j_hnc_cancer_fup_days),
        j_hnc_cancer_fup_age = if(@j_hnc_cancer_fup_age in('NA', ''), null, @j_hnc_cancer_fup_age),
        j_hnc_cancer_dx_age = if(@j_hnc_cancer_dx_age in('NA', ''), null, @j_hnc_cancer_dx_age),
        j_hnc_larynx = if(@j_hnc_larynx in('NA', ''), null, @j_hnc_larynx),
        j_hnc_lip_oral_pharynx = if(@j_hnc_lip_oral_pharynx in('NA', ''), null, @j_hnc_lip_oral_pharynx),
        j_hnc_naso_mid_sinus = if(@j_hnc_naso_mid_sinus in('NA', ''), null, @j_hnc_naso_mid_sinus),
        j_hpv_related_dx_age = if(@j_hpv_related_dx_age in('NA', ''), null, @j_hpv_related_dx_age),
        j_hpv_related = if(@j_hpv_related in('NA', ''), null, @j_hpv_related),
        j_hpv_related_fup_age = if(@j_hpv_related_fup_age in('NA', ''), null, @j_hpv_related_fup_age),
        j_hpv_related_fup_days = if(@j_hpv_related_fup_days in('NA', ''), null, @j_hpv_related_fup_days),
        j_infection_related_dx_age = if(@j_infection_related_dx_age in('NA', ''), null, @j_infection_related_dx_age),
        j_infection_related = if(@j_infection_related in('NA', ''), null, @j_infection_related),
        j_infection_related_fup_age = if(@j_infection_related_fup_age in('NA', ''), null, @j_infection_related_fup_age),
        j_infection_related_fup_days = if(@j_infection_related_fup_days in('NA', ''), null, @j_infection_related_fup_days),
        j_kidney_cancer_fup_days = if(@j_kidney_cancer_fup_days in('NA', ''), null, @j_kidney_cancer_fup_days),
        j_kidney_cancer_fup_age = if(@j_kidney_cancer_fup_age in('NA', ''), null, @j_kidney_cancer_fup_age),
        j_kidney_cancer_dx_age = if(@j_kidney_cancer_dx_age in('NA', ''), null, @j_kidney_cancer_dx_age),
        j_kidney_cancer = if(@j_kidney_cancer in('NA', ''), null, @j_kidney_cancer),
        j_kidney_renalcell_clearcell = if(@j_kidney_renalcell_clearcell in('NA', ''), null, @j_kidney_renalcell_clearcell),
        j_kidney_renalcell_nos = if(@j_kidney_renalcell_nos in('NA', ''), null, @j_kidney_renalcell_nos),
        j_gast_cancer = if(@j_gast_cancer in('NA', ''), null, @j_gast_cancer),
        j_gast_cancer_fup_days = if(@j_gast_cancer_fup_days in('NA', ''), null, @j_gast_cancer_fup_days),
        j_gast_cancer_fup_age = if(@j_gast_cancer_fup_age in('NA', ''), null, @j_gast_cancer_fup_age),
        j_gast_cancer_dx_age = if(@j_gast_cancer_dx_age in('NA', ''), null, @j_gast_cancer_dx_age),
        j_gast_cardia = if(@j_gast_cardia in('NA', ''), null, @j_gast_cardia),
        j_gast_noncardia = if(@j_gast_noncardia in('NA', ''), null, @j_gast_noncardia),
        j_glio_cancer = if(@j_glio_cancer in('NA', ''), null, @j_glio_cancer),
        j_glio_cancer_fup_days = if(@j_glio_cancer_fup_days in('NA', ''), null, @j_glio_cancer_fup_days),
        j_glio_cancer_fup_age = if(@j_glio_cancer_fup_age in('NA', ''), null, @j_glio_cancer_fup_age),
        j_glio_cancer_dx_age = if(@j_glio_cancer_dx_age in('NA', ''), null, @j_glio_cancer_dx_age),
        j_liver_xintra_cancer_fup_days = if(@j_liver_xintra_cancer_fup_days in('NA', ''), null, @j_liver_xintra_cancer_fup_days),
        j_liver_xintra_cancer_fup_age = if(@j_liver_xintra_cancer_fup_age in('NA', ''), null, @j_liver_xintra_cancer_fup_age),
        j_liver_xintra_cancer_dx_age = if(@j_liver_xintra_cancer_dx_age in('NA', ''), null, @j_liver_xintra_cancer_dx_age),
        j_liver_xintra_cancer = if(@j_liver_xintra_cancer in('NA', ''), null, @j_liver_xintra_cancer),
        j_lung_cancer = if(@j_lung_cancer in('NA', ''), null, @j_lung_cancer),
        j_lung_cancer_fup_days = if(@j_lung_cancer_fup_days in('NA', ''), null, @j_lung_cancer_fup_days),
        j_lung_cancer_fup_age = if(@j_lung_cancer_fup_age in('NA', ''), null, @j_lung_cancer_fup_age),
        j_lung_cancer_dx_age = if(@j_lung_cancer_dx_age in('NA', ''), null, @j_lung_cancer_dx_age),
        j_lung_smallcell = if(@j_lung_smallcell in('NA', ''), null, @j_lung_smallcell),
        j_lung_adeno = if(@j_lung_adeno in('NA', ''), null, @j_lung_adeno),
        j_lung_squam = if(@j_lung_squam in('NA', ''), null, @j_lung_squam),
        j_lymphoid = if(@j_lymphoid in('NA', ''), null, @j_lymphoid),
        j_lymphoid_fup_days = if(@j_lymphoid_fup_days in('NA', ''), null, @j_lymphoid_fup_days),
        j_lymphoid_fup_age = if(@j_lymphoid_fup_age in('NA', ''), null, @j_lymphoid_fup_age),
        j_lymphoid_dx_age = if(@j_lymphoid_dx_age in('NA', ''), null, @j_lymphoid_dx_age),
        j_cll = if(@j_cll in('NA', ''), null, @j_cll),
        j_cll_fup_days = if(@j_cll_fup_days in('NA', ''), null, @j_cll_fup_days),
        j_cll_fup_age = if(@j_cll_fup_age in('NA', ''), null, @j_cll_fup_age),
        j_cll_dx_age = if(@j_cll_dx_age in('NA', ''), null, @j_cll_dx_age),
        j_mbreast_cancer = if(@j_mbreast_cancer in('NA', ''), null, @j_mbreast_cancer),
        j_mbreast_cancer_fup_days = if(@j_mbreast_cancer_fup_days in('NA', ''), null, @j_mbreast_cancer_fup_days),
        j_mbreast_cancer_fup_age = if(@j_mbreast_cancer_fup_age in('NA', ''), null, @j_mbreast_cancer_fup_age),
        j_mbreast_cancer_dx_age = if(@j_mbreast_cancer_dx_age in('NA', ''), null, @j_mbreast_cancer_dx_age),
        j_mela_cancer = if(@j_mela_cancer in('NA', ''), null, @j_mela_cancer),
        j_mela_cancer_fup_days = if(@j_mela_cancer_fup_days in('NA', ''), null, @j_mela_cancer_fup_days),
        j_mela_cancer_fup_age = if(@j_mela_cancer_fup_age in('NA', ''), null, @j_mela_cancer_fup_age),
        j_mela_cancer_dx_age = if(@j_mela_cancer_dx_age in('NA', ''), null, @j_mela_cancer_dx_age),
        j_mela_invasive_cancer = if(@j_mela_invasive_cancer in('NA', ''), null, @j_mela_invasive_cancer),
        j_mela_invasive_cancer_fup_age = if(@j_mela_invasive_cancer_fup_age in('NA', ''), null, @j_mela_invasive_cancer_fup_age),
        j_mela_invasive_cancer_dx_age = if(@j_mela_invasive_cancer_dx_age in('NA', ''), null, @j_mela_invasive_cancer_dx_age),
        j_mela_invasive_cancer_fup_days = if(@j_mela_invasive_cancer_fup_days in('NA', ''), null, @j_mela_invasive_cancer_fup_days),
        j_mesoth = if(@j_mesoth in('NA', ''), null, @j_mesoth),
        j_mesoth_fup_days = if(@j_mesoth_fup_days in('NA', ''), null, @j_mesoth_fup_days),
        j_mesoth_fup_age = if(@j_mesoth_fup_age in('NA', ''), null, @j_mesoth_fup_age),
        j_mesoth_dx_age = if(@j_mesoth_dx_age in('NA', ''), null, @j_mesoth_dx_age),
        j_myeloid = if(@j_myeloid in('NA', ''), null, @j_myeloid),
        j_myeloid_fup_days = if(@j_myeloid_fup_days in('NA', ''), null, @j_myeloid_fup_days),
        j_myeloid_fup_age = if(@j_myeloid_fup_age in('NA', ''), null, @j_myeloid_fup_age),
        j_myeloid_dx_age = if(@j_myeloid_dx_age in('NA', ''), null, @j_myeloid_dx_age),
        j_obesity_related_dx_age = if(@j_obesity_related_dx_age in('NA', ''), null, @j_obesity_related_dx_age),
        j_obesity_related = if(@j_obesity_related in('NA', ''), null, @j_obesity_related),
        j_obesity_related_fup_age = if(@j_obesity_related_fup_age in('NA', ''), null, @j_obesity_related_fup_age),
        j_obesity_related_fup_days = if(@j_obesity_related_fup_days in('NA', ''), null, @j_obesity_related_fup_days),
        j_osumm_cancer = if(@j_osumm_cancer in('NA', ''), null, @j_osumm_cancer),
        j_osumm_cancer_fup_days = if(@j_osumm_cancer_fup_days in('NA', ''), null, @j_osumm_cancer_fup_days),
        j_osumm_cancer_fup_age = if(@j_osumm_cancer_fup_age in('NA', ''), null, @j_osumm_cancer_fup_age),
        j_osumm_cancer_dx_age = if(@j_osumm_cancer_dx_age in('NA', ''), null, @j_osumm_cancer_dx_age),
        j_osumm_serous_grade_high = if(@j_osumm_serous_grade_high in('NA', ''), null, @j_osumm_serous_grade_high),
        j_panc_cancer = if(@j_panc_cancer in('NA', ''), null, @j_panc_cancer),
        j_panc_cancer_fup_days = if(@j_panc_cancer_fup_days in('NA', ''), null, @j_panc_cancer_fup_days),
        j_panc_cancer_fup_age = if(@j_panc_cancer_fup_age in('NA', ''), null, @j_panc_cancer_fup_age),
        j_panc_cancer_dx_age = if(@j_panc_cancer_dx_age in('NA', ''), null, @j_panc_cancer_dx_age),
        j_phys_act_related_dx_age = if(@j_phys_act_related_dx_age in('NA', ''), null, @j_phys_act_related_dx_age),
        j_phys_act_related = if(@j_phys_act_related in('NA', ''), null, @j_phys_act_related),
        j_phys_act_related_fup_age = if(@j_phys_act_related_fup_age in('NA', ''), null, @j_phys_act_related_fup_age),
        j_phys_act_related_fup_days = if(@j_phys_act_related_fup_days in('NA', ''), null, @j_phys_act_related_fup_days),
        j_pros_cancer = if(@j_pros_cancer in('NA', ''), null, @j_pros_cancer),
        j_pros_cancer_fup_days = if(@j_pros_cancer_fup_days in('NA', ''), null, @j_pros_cancer_fup_days),
        j_pros_cancer_fup_age = if(@j_pros_cancer_fup_age in('NA', ''), null, @j_pros_cancer_fup_age),
        j_pros_cancer_dx_age = if(@j_pros_cancer_dx_age in('NA', ''), null, @j_pros_cancer_dx_age),
        j_pros_non_advanced = if(@j_pros_non_advanced in('NA', ''), null, @j_pros_non_advanced),
        j_pros_advanced_including7 = if(@j_pros_advanced_including7 in('NA', ''), null, @j_pros_advanced_including7),
        j_pros_advanced_excluding7 = if(@j_pros_advanced_excluding7 in('NA', ''), null, @j_pros_advanced_excluding7),
        j_sarcoma = if(@j_sarcoma in('NA', ''), null, @j_sarcoma),
        j_sarcoma_fup_days = if(@j_sarcoma_fup_days in('NA', ''), null, @j_sarcoma_fup_days),
        j_sarcoma_fup_age = if(@j_sarcoma_fup_age in('NA', ''), null, @j_sarcoma_fup_age),
        j_sarcoma_dx_age = if(@j_sarcoma_dx_age in('NA', ''), null, @j_sarcoma_dx_age),
        j_smoking_related_dx_age = if(@j_smoking_related_dx_age in('NA', ''), null, @j_smoking_related_dx_age),
        j_smoking_related = if(@j_smoking_related in('NA', ''), null, @j_smoking_related),
        j_smoking_related_fup_age = if(@j_smoking_related_fup_age in('NA', ''), null, @j_smoking_related_fup_age),
        j_smoking_related_fup_days = if(@j_smoking_related_fup_days in('NA', ''), null, @j_smoking_related_fup_days),
        j_solid_tumor = if(@j_solid_tumor in('NA', ''), null, @j_solid_tumor),
        j_solid_tumor_fup_days = if(@j_solid_tumor_fup_days in('NA', ''), null, @j_solid_tumor_fup_days),
        j_solid_tumor_fup_age = if(@j_solid_tumor_fup_age in('NA', ''), null, @j_solid_tumor_fup_age),
        j_solid_tumor_dx_age = if(@j_solid_tumor_dx_age in('NA', ''), null, @j_solid_tumor_dx_age),
        j_squamous = if(@j_squamous in('NA', ''), null, @j_squamous),
        j_squamous_fup_days = if(@j_squamous_fup_days in('NA', ''), null, @j_squamous_fup_days),
        j_squamous_fup_age = if(@j_squamous_fup_age in('NA', ''), null, @j_squamous_fup_age),
        j_squamous_dx_age = if(@j_squamous_dx_age in('NA', ''), null, @j_squamous_dx_age),
        j_thyd_cancer = if(@j_thyd_cancer in('NA', ''), null, @j_thyd_cancer),
        j_thyd_cancer_fup_days = if(@j_thyd_cancer_fup_days in('NA', ''), null, @j_thyd_cancer_fup_days),
        j_thyd_cancer_fup_age = if(@j_thyd_cancer_fup_age in('NA', ''), null, @j_thyd_cancer_fup_age),
        j_thyd_cancer_dx_age = if(@j_thyd_cancer_dx_age in('NA', ''), null, @j_thyd_cancer_dx_age),
        j_upgi_cancer = if(@j_upgi_cancer in('NA', ''), null, @j_upgi_cancer),
        j_upgi_cancer_fup_days = if(@j_upgi_cancer_fup_days in('NA', ''), null, @j_upgi_cancer_fup_days),
        j_upgi_cancer_fup_age = if(@j_upgi_cancer_fup_age in('NA', ''), null, @j_upgi_cancer_fup_age),
        j_upgi_cancer_dx_age = if(@j_upgi_cancer_dx_age in('NA', ''), null, @j_upgi_cancer_dx_age),
        j_urothelial = if(@j_urothelial in('NA', ''), null, @j_urothelial),
        j_urothelial_fup_days = if(@j_urothelial_fup_days in('NA', ''), null, @j_urothelial_fup_days),
        j_urothelial_fup_age = if(@j_urothelial_fup_age in('NA', ''), null, @j_urothelial_fup_age),
        j_urothelial_dx_age = if(@j_urothelial_dx_age in('NA', ''), null, @j_urothelial_dx_age),
        is_dead = if(@is_dead in('NA', ''), null, @is_dead),
        mortality_exitage = if(@mortality_exitage in('NA', ''), null, @mortality_exitage),
        dth_days = if(@dth_days in('NA', ''), null, @dth_days),
        mortality_exitdays_unadj = if(@mortality_exitdays_unadj in('NA', ''), null, @mortality_exitdays_unadj),
        f_death_ischemic = if(@f_death_ischemic in('NA', ''), null, @f_death_ischemic),
        f_death_cerebrovascular = if(@f_death_cerebrovascular in('NA', ''), null, @f_death_cerebrovascular),
        f_death_rheumatic = if(@f_death_rheumatic in('NA', ''), null, @f_death_rheumatic),
        f_death_hypertensive = if(@f_death_hypertensive in('NA', ''), null, @f_death_hypertensive),
        f_death_peripheral = if(@f_death_peripheral in('NA', ''), null, @f_death_peripheral),
        f_death_heart = if(@f_death_heart in('NA', ''), null, @f_death_heart),
        f_death_cardiac = if(@f_death_cardiac in('NA', ''), null, @f_death_cardiac),
        f_death_arrhythmia = if(@f_death_arrhythmia in('NA', ''), null, @f_death_arrhythmia),
        f_death_endocarditis = if(@f_death_endocarditis in('NA', ''), null, @f_death_endocarditis),
        f_death_cardiovascular = if(@f_death_cardiovascular in('NA', ''), null, @f_death_cardiovascular),
        f_death_cancer = if(@f_death_cancer in('NA', ''), null, @f_death_cancer),
        f_death_chronicresp = if(@f_death_chronicresp in('NA', ''), null, @f_death_chronicresp),
        f_death_alzheimers = if(@f_death_alzheimers in('NA', ''), null, @f_death_alzheimers),
        f_death_diabetes = if(@f_death_diabetes in('NA', ''), null, @f_death_diabetes),
        f_death_nephritis = if(@f_death_nephritis in('NA', ''), null, @f_death_nephritis),
        f_death_chronicliver = if(@f_death_chronicliver in('NA', ''), null, @f_death_chronicliver),
        f_death_parkinsons = if(@f_death_parkinsons in('NA', ''), null, @f_death_parkinsons),
        bq_educat_o = if(@bq_educat_o in('NA', ''), null, @bq_educat_o),
        bq_marital_co = if(@bq_marital_co in('NA', ''), null, @bq_marital_co),
        bq_fmenstr_o = if(@bq_fmenstr_o in('NA', ''), null, @bq_fmenstr_o),
        bq_tubal_o = if(@bq_tubal_o in('NA', ''), null, @bq_tubal_o),
        bq_bbd_b = if(@bq_bbd_b in('NA', ''), null, @bq_bbd_b),
        bq_benign_ovcyst_b = if(@bq_benign_ovcyst_b in('NA', ''), null, @bq_benign_ovcyst_b),
        bq_endometriosis_b = if(@bq_endometriosis_b in('NA', ''), null, @bq_endometriosis_b),
        bq_uterine_fib_b = if(@bq_uterine_fib_b in('NA', ''), null, @bq_uterine_fib_b),
        bq_trypreg_b = if(@bq_trypreg_b in('NA', ''), null, @bq_trypreg_b),
        bq_urinatea_o = if(@bq_urinatea_o in('NA', ''), null, @bq_urinatea_o),
        bq_infprosa_o = if(@bq_infprosa_o in('NA', ''), null, @bq_infprosa_o),
        bq_hearta_f_b = if(@bq_hearta_f_b in('NA', ''), null, @bq_hearta_f_b),
        bq_bronchit_f_b = if(@bq_bronchit_f_b in('NA', ''), null, @bq_bronchit_f_b),
        bq_polyps_f_b = if(@bq_polyps_f_b in('NA', ''), null, @bq_polyps_f_b),
        bq_ulcerative_colitits_b = if(@bq_ulcerative_colitits_b in('NA', ''), null, @bq_ulcerative_colitits_b),
        bq_crohns_disease_b = if(@bq_crohns_disease_b in('NA', ''), null, @bq_crohns_disease_b),
        bq_familial_polyposis_b = if(@bq_familial_polyposis_b in('NA', ''), null, @bq_familial_polyposis_b),
        bq_hepatitis_b = if(@bq_hepatitis_b in('NA', ''), null, @bq_hepatitis_b),
        bq_cirrhosis_b = if(@bq_cirrhosis_b in('NA', ''), null, @bq_cirrhosis_b),
        bq_divertic_f_b = if(@bq_divertic_f_b in('NA', ''), null, @bq_divertic_f_b),
        bq_gallblad_f_b = if(@bq_gallblad_f_b in('NA', ''), null, @bq_gallblad_f_b),
        bq_age_co = if(@bq_age_co in('NA', ''), null, @bq_age_co),
        bq_race7_ca = if(@bq_race7_ca in('NA', ''), null, @bq_race7_ca),
        bq_hispanic_f_b = if(@bq_hispanic_f_b in('NA', ''), null, @bq_hispanic_f_b),
        bq_surg_resection_b = if(@bq_surg_resection_b in('NA', ''), null, @bq_surg_resection_b),
        bq_surg_prostatectomy_b = if(@bq_surg_prostatectomy_b in('NA', ''), null, @bq_surg_prostatectomy_b),
        bq_hyster_f_b = if(@bq_hyster_f_b in('NA', ''), null, @bq_hyster_f_b),
        bq_ovariesr_f_ca = if(@bq_ovariesr_f_ca in('NA', ''), null, @bq_ovariesr_f_ca),
        bq_infpros_f_b = if(@bq_infpros_f_b in('NA', ''), null, @bq_infpros_f_b),
        bq_urinate_f_o = if(@bq_urinate_f_o in('NA', ''), null, @bq_urinate_f_o),
        bq_smoked_f_b = if(@bq_smoked_f_b in('NA', ''), null, @bq_smoked_f_b),
        bq_smokea_f_co = if(@bq_smokea_f_co in('NA', ''), null, @bq_smokea_f_co),
        bq_ssmokea_f_co = if(@bq_ssmokea_f_co in('NA', ''), null, @bq_ssmokea_f_co),
        bq_cig_stop_co = if(@bq_cig_stop_co in('NA', ''), null, @bq_cig_stop_co),
        bq_bmi_20_co = if(@bq_bmi_20_co in('NA', ''), null, @bq_bmi_20_co),
        bq_bmi_50_co = if(@bq_bmi_50_co in('NA', ''), null, @bq_bmi_50_co),
        bq_bmi_curr_co = if(@bq_bmi_curr_co in('NA', ''), null, @bq_bmi_curr_co),
        bq_weight_f_co = if(@bq_weight_f_co in('NA', ''), null, @bq_weight_f_co),
        bq_weight20_f_co = if(@bq_weight20_f_co in('NA', ''), null, @bq_weight20_f_co),
        bq_weight50_f_co = if(@bq_weight50_f_co in('NA', ''), null, @bq_weight50_f_co),
        bq_height_f_co = if(@bq_height_f_co in('NA', ''), null, @bq_height_f_co),
        bq_fh_cancer_b = if(@bq_fh_cancer_b in('NA', ''), null, @bq_fh_cancer_b),
        center = if(@center in('NA', ''), null, @center),
        arm = if(@arm in('NA', ''), null, @arm),
        sex = if(@sex in('NA', ''), null, @sex),
        dqx_age_co = if(@dqx_age_co in('NA', ''), null, @dqx_age_co),
        dqx_qxn_physicact_40_o = if(@dqx_qxn_physicact_40_o in('NA', ''), null, @dqx_qxn_physicact_40_o),
        dqx_qxn_physicact_now_o = if(@dqx_qxn_physicact_now_o in('NA', ''), null, @dqx_qxn_physicact_now_o),
        sqx_age_co = if(@sqx_age_co in('NA', ''), null, @sqx_age_co),
        sqx_sit_ht_o = if(@sqx_sit_ht_o in('NA', ''), null, @sqx_sit_ht_o),
        sqx_waist_hip_o = if(@sqx_waist_hip_o in('NA', ''), null, @sqx_waist_hip_o),
        sqx_height_co = if(@sqx_height_co in('NA', ''), null, @sqx_height_co),
        sqx_wt30s_co = if(@sqx_wt30s_co in('NA', ''), null, @sqx_wt30s_co),
        sqx_wt40s_co = if(@sqx_wt40s_co in('NA', ''), null, @sqx_wt40s_co),
        sqx_wt50s_co = if(@sqx_wt50s_co in('NA', ''), null, @sqx_wt50s_co),
        sqx_wt60s_co = if(@sqx_wt60s_co in('NA', ''), null, @sqx_wt60s_co),
        sqx_wt70s_co = if(@sqx_wt70s_co in('NA', ''), null, @sqx_wt70s_co),
        sqx_wt_curr_co = if(@sqx_wt_curr_co in('NA', ''), null, @sqx_wt_curr_co),
        sqx_bmi30s_co = if(@sqx_bmi30s_co in('NA', ''), null, @sqx_bmi30s_co),
        sqx_bmi40s_co = if(@sqx_bmi40s_co in('NA', ''), null, @sqx_bmi40s_co),
        sqx_bmi50s_co = if(@sqx_bmi50s_co in('NA', ''), null, @sqx_bmi50s_co),
        sqx_bmi60s_co = if(@sqx_bmi60s_co in('NA', ''), null, @sqx_bmi60s_co),
        sqx_bmi70s_co = if(@sqx_bmi70s_co in('NA', ''), null, @sqx_bmi70s_co),
        sqx_bmi_curr_co = if(@sqx_bmi_curr_co in('NA', ''), null, @sqx_bmi_curr_co),
        sqx_cholesterol_b = if(@sqx_cholesterol_b in('NA', ''), null, @sqx_cholesterol_b),
        sqx_asthma_b = if(@sqx_asthma_b in('NA', ''), null, @sqx_asthma_b),
        sqxbq_hearta_b = if(@sqxbq_hearta_b in('NA', ''), null, @sqxbq_hearta_b),
        sqxbq_stroke_b = if(@sqxbq_stroke_b in('NA', ''), null, @sqxbq_stroke_b),
        sqxbq_hyperten_b = if(@sqxbq_hyperten_b in('NA', ''), null, @sqxbq_hyperten_b),
        sqxbq_diabetes_b = if(@sqxbq_diabetes_b in('NA', ''), null, @sqxbq_diabetes_b),
        sqxbq_osteopor_b = if(@sqxbq_osteopor_b in('NA', ''), null, @sqxbq_osteopor_b),
        sqxbq_emphysema_b = if(@sqxbq_emphysema_b in('NA', ''), null, @sqxbq_emphysema_b),
        sqxbq_arthritis_b = if(@sqxbq_arthritis_b in('NA', ''), null, @sqxbq_arthritis_b),
        sqx_broke_hip_b = if(@sqx_broke_hip_b in('NA', ''), null, @sqx_broke_hip_b),
        sqx_broke_arm_b = if(@sqx_broke_arm_b in('NA', ''), null, @sqx_broke_arm_b),
        sqx_broke_vertebra_b = if(@sqx_broke_vertebra_b in('NA', ''), null, @sqx_broke_vertebra_b),
        sqx_broke_none_b = if(@sqx_broke_none_b in('NA', ''), null, @sqx_broke_none_b),
        sqx_balding_trend_o = if(@sqx_balding_trend_o in('NA', ''), null, @sqx_balding_trend_o),
        sqx_urinate_o = if(@sqx_urinate_o in('NA', ''), null, @sqx_urinate_o),
        sqxbq_bpha_o = if(@sqxbq_bpha_o in('NA', ''), null, @sqxbq_bpha_o),
        sqxbq_bph_b = if(@sqxbq_bph_b in('NA', ''), null, @sqxbq_bph_b),
        sqx_lift_weights_b = if(@sqx_lift_weights_b in('NA', ''), null, @sqx_lift_weights_b),
        sqx_lift_weights_lev_o = if(@sqx_lift_weights_lev_o in('NA', ''), null, @sqx_lift_weights_lev_o),
        sqx_active_b = if(@sqx_active_b in('NA', ''), null, @sqx_active_b),
        sqx_fh_blad_b = if(@sqx_fh_blad_b in('NA', ''), null, @sqx_fh_blad_b),
        sqx_fh_breast_b = if(@sqx_fh_breast_b in('NA', ''), null, @sqx_fh_breast_b),
        sqx_fh_colo_b = if(@sqx_fh_colo_b in('NA', ''), null, @sqx_fh_colo_b),
        sqx_fh_endo_b = if(@sqx_fh_endo_b in('NA', ''), null, @sqx_fh_endo_b),
        sqx_fh_leuk_b = if(@sqx_fh_leuk_b in('NA', ''), null, @sqx_fh_leuk_b),
        sqx_fh_lung_b = if(@sqx_fh_lung_b in('NA', ''), null, @sqx_fh_lung_b),
        sqx_fh_lymph_b = if(@sqx_fh_lymph_b in('NA', ''), null, @sqx_fh_lymph_b),
        sqx_fh_ovar_b = if(@sqx_fh_ovar_b in('NA', ''), null, @sqx_fh_ovar_b),
        sqx_fh_pros_b = if(@sqx_fh_pros_b in('NA', ''), null, @sqx_fh_pros_b),
        sqx_fh_cancer_f_b = if(@sqx_fh_cancer_f_b in('NA', ''), null, @sqx_fh_cancer_f_b),
        sqx_twins_b = if(@sqx_twins_b in('NA', ''), null, @sqx_twins_b),
        sqx_smk100_b = if(@sqx_smk100_b in('NA', ''), null, @sqx_smk100_b),
        sqx_amt_smk_o = if(@sqx_amt_smk_o in('NA', ''), null, @sqx_amt_smk_o),
        sqx_smk_crave1_b = if(@sqx_smk_crave1_b in('NA', ''), null, @sqx_smk_crave1_b),
        sqx_smk_crave2_b = if(@sqx_smk_crave2_b in('NA', ''), null, @sqx_smk_crave2_b),
        sqx_smk_crave3_b = if(@sqx_smk_crave3_b in('NA', ''), null, @sqx_smk_crave3_b),
        sqx_smk_crave4_b = if(@sqx_smk_crave4_b in('NA', ''), null, @sqx_smk_crave4_b),
        sqx_smk_try_quit_b = if(@sqx_smk_try_quit_b in('NA', ''), null, @sqx_smk_try_quit_b),
        sqx_smk_age_quit_co = if(@sqx_smk_age_quit_co in('NA', ''), null, @sqx_smk_age_quit_co),
        sqx_worry_lungca_o = if(@sqx_worry_lungca_o in('NA', ''), null, @sqx_worry_lungca_o),
        sqx_risk_lungca_o = if(@sqx_risk_lungca_o in('NA', ''), null, @sqx_risk_lungca_o),
        sqx_smk_his_co = if(@sqx_smk_his_co in('NA', ''), null, @sqx_smk_his_co),
        sqx_smk_behv_co = if(@sqx_smk_behv_co in('NA', ''), null, @sqx_smk_behv_co),
        sqx_smk_ftnd_co = if(@sqx_smk_ftnd_co in('NA', ''), null, @sqx_smk_ftnd_co),
        sqx_years_quit_co = if(@sqx_years_quit_co in('NA', ''), null, @sqx_years_quit_co),
        sqx_cig_years_co = if(@sqx_cig_years_co in('NA', ''), null, @sqx_cig_years_co),
        sqx_gain_chest_shoulders_b = if(@sqx_gain_chest_shoulders_b in('NA', ''), null, @sqx_gain_chest_shoulders_b),
        sqx_gain_waist_stomach_b = if(@sqx_gain_waist_stomach_b in('NA', ''), null, @sqx_gain_waist_stomach_b),
        sqx_gain_hips_thighs_b = if(@sqx_gain_hips_thighs_b in('NA', ''), null, @sqx_gain_hips_thighs_b),
        sqx_gain_equally_over_b = if(@sqx_gain_equally_over_b in('NA', ''), null, @sqx_gain_equally_over_b),
        sqx_lose_chest_shoulders_b = if(@sqx_lose_chest_shoulders_b in('NA', ''), null, @sqx_lose_chest_shoulders_b),
        sqx_lose_waist_stomach_b = if(@sqx_lose_waist_stomach_b in('NA', ''), null, @sqx_lose_waist_stomach_b),
        sqx_lose_hips_thighs_b = if(@sqx_lose_hips_thighs_b in('NA', ''), null, @sqx_lose_hips_thighs_b),
        sqx_lose_equally_over_b = if(@sqx_lose_equally_over_b in('NA', ''), null, @sqx_lose_equally_over_b),
        sqxbq_rheumatoid_arthritis_b = if(@sqxbq_rheumatoid_arthritis_b in('NA', ''), null, @sqxbq_rheumatoid_arthritis_b),
        sqxbq_osteoarthritis_b = if(@sqxbq_osteoarthritis_b in('NA', ''), null, @sqxbq_osteoarthritis_b),
        sqx_moderate_week_co = if(@sqx_moderate_week_co in('NA', ''), null, @sqx_moderate_week_co),
        sqx_strenuous_week_co = if(@sqx_strenuous_week_co in('NA', ''), null, @sqx_strenuous_week_co),
        sqx_ever_balding_b = if(@sqx_ever_balding_b in('NA', ''), null, @sqx_ever_balding_b),
        sqx_top_bald_b = if(@sqx_top_bald_b in('NA', ''), null, @sqx_top_bald_b),
        bq_menstr_natural_o = if(@bq_menstr_natural_o in('NA', ''), null, @bq_menstr_natural_o),
        sqx_current_cigarette_b = if(@sqx_current_cigarette_b in('NA', ''), null, @sqx_current_cigarette_b),
        sqxbq_relapse_b = if(@sqxbq_relapse_b in('NA', ''), null, @sqxbq_relapse_b),
        bq_current_cigarette_b = if(@bq_current_cigarette_b in('NA', ''), null, @bq_current_cigarette_b),
        bq_cig_stat_o = if(@bq_cig_stat_o in('NA', ''), null, @bq_cig_stat_o),
        bq_cig_years_co = if(@bq_cig_years_co in('NA', ''), null, @bq_cig_years_co),
        bq_cigar_o = if(@bq_cigar_o in('NA', ''), null, @bq_cigar_o),
        bq_cigpd_f_o = if(@bq_cigpd_f_o in('NA', ''), null, @bq_cigpd_f_o),
        bq_filtered_f_b = if(@bq_filtered_f_b in('NA', ''), null, @bq_filtered_f_b),
        bq_pack_years_co = if(@bq_pack_years_co in('NA', ''), null, @bq_pack_years_co),
        bq_pipe_o = if(@bq_pipe_o in('NA', ''), null, @bq_pipe_o),
        sqx_pace_o = if(@sqx_pace_o in('NA', ''), null, @sqx_pace_o),
        sqx_stairs_o = if(@sqx_stairs_o in('NA', ''), null, @sqx_stairs_o),
        sqx_walk_mi_o = if(@sqx_walk_mi_o in('NA', ''), null, @sqx_walk_mi_o),
        pack_years_bqelsesqx_co = if(@pack_years_bqelsesqx_co in('NA', ''), null, @pack_years_bqelsesqx_co),
        sqx_smk_exp_adult_o = if(@sqx_smk_exp_adult_o in('NA', ''), null, @sqx_smk_exp_adult_o),
        sqx_smk_lgt_ca = if(@sqx_smk_lgt_ca in('NA', ''), null, @sqx_smk_lgt_ca),
        sqx_smk_menthol_b = if(@sqx_smk_menthol_b in('NA', ''), null, @sqx_smk_menthol_b),
        sqx_smk_plan_quit_o = if(@sqx_smk_plan_quit_o in('NA', ''), null, @sqx_smk_plan_quit_o),
        sqx_smk_wake_o = if(@sqx_smk_wake_o in('NA', ''), null, @sqx_smk_wake_o),
        sqx_smk30days_b = if(@sqx_smk30days_b in('NA', ''), null, @sqx_smk30days_b),
        sqxo_cig_stat_o = if(@sqxo_cig_stat_o in('NA', ''), null, @sqxo_cig_stat_o),
        sqx_urinatea_o = if(@sqx_urinatea_o in('NA', ''), null, @sqx_urinatea_o),
        sv_coffee_reg_nosug_dhq = if(@sv_coffee_reg_nosug_dhq in('NA', ''), null, @sv_coffee_reg_nosug_dhq),
        sv_coffee_decaf_nosug_dhq = if(@sv_coffee_decaf_nosug_dhq in('NA', ''), null, @sv_coffee_decaf_nosug_dhq),
        mped_fruit_nojuice_dhq = if(@mped_fruit_nojuice_dhq in('NA', ''), null, @mped_fruit_nojuice_dhq),
        dt_alc_alc_drinks_dhq = if(@dt_alc_alc_drinks_dhq in('NA', ''), null, @dt_alc_alc_drinks_dhq),
        drinker_dhq = if(@drinker_dhq in('NA', ''), null, @drinker_dhq),
        g_candy_choc_dhq = if(@g_candy_choc_dhq in('NA', ''), null, @g_candy_choc_dhq),
        g_red5_dhq = if(@g_red5_dhq in('NA', ''), null, @g_red5_dhq),
        g_process_6_dhq = if(@g_process_6_dhq in('NA', ''), null, @g_process_6_dhq),
        g_fruit_dhq = if(@g_fruit_dhq in('NA', ''), null, @g_fruit_dhq),
        g_vegetable_dhq = if(@g_vegetable_dhq in('NA', ''), null, @g_vegetable_dhq),
        g_fish_total_dhq = if(@g_fish_total_dhq in('NA', ''), null, @g_fish_total_dhq),
        g_salty_grain_snack_dhq = if(@g_salty_grain_snack_dhq in('NA', ''), null, @g_salty_grain_snack_dhq),
        g_fruit_citrus_dhq = if(@g_fruit_citrus_dhq in('NA', ''), null, @g_fruit_citrus_dhq),
        g_soda_reg_dhq = if(@g_soda_reg_dhq in('NA', ''), null, @g_soda_reg_dhq),
        dt_kcal_dhq = if(@dt_kcal_dhq in('NA', ''), null, @dt_kcal_dhq),
        dt_prot_dhq = if(@dt_prot_dhq in('NA', ''), null, @dt_prot_dhq),
        dt_fat_dhq = if(@dt_fat_dhq in('NA', ''), null, @dt_fat_dhq),
        dt_carb_dhq = if(@dt_carb_dhq in('NA', ''), null, @dt_carb_dhq),
        dt_fiber_csfii_dhq = if(@dt_fiber_csfii_dhq in('NA', ''), null, @dt_fiber_csfii_dhq),
        dt_caffeine_dhq = if(@dt_caffeine_dhq in('NA', ''), null, @dt_caffeine_dhq),
        gly_load_dhq = if(@gly_load_dhq in('NA', ''), null, @gly_load_dhq),
        mped_grain_dhq = if(@mped_grain_dhq in('NA', ''), null, @mped_grain_dhq),
        mped_grain_whole_dhq = if(@mped_grain_whole_dhq in('NA', ''), null, @mped_grain_whole_dhq),
        mped_veg_dark_green_dhq = if(@mped_veg_dark_green_dhq in('NA', ''), null, @mped_veg_dark_green_dhq),
        mped_dairy_dhq = if(@mped_dairy_dhq in('NA', ''), null, @mped_dairy_dhq),
        mped_dairy_milk_dhq = if(@mped_dairy_milk_dhq in('NA', ''), null, @mped_dairy_milk_dhq),
        mped_m_soy_dhq = if(@mped_m_soy_dhq in('NA', ''), null, @mped_m_soy_dhq),
        mped_m_nut_seed_dhq = if(@mped_m_nut_seed_dhq in('NA', ''), null, @mped_m_nut_seed_dhq),
        mped_legume_dhq = if(@mped_legume_dhq in('NA', ''), null, @mped_legume_dhq),
        mped_added_sugar_dhq = if(@mped_added_sugar_dhq in('NA', ''), null, @mped_added_sugar_dhq),
        pe_fr_protein_dhq = if(@pe_fr_protein_dhq in('NA', ''), null, @pe_fr_protein_dhq),
        pe_fr_fat_dhq = if(@pe_fr_fat_dhq in('NA', ''), null, @pe_fr_fat_dhq),
        pe_fr_carb_dhq = if(@pe_fr_carb_dhq in('NA', ''), null, @pe_fr_carb_dhq),
        pe_fr_alc_dhq = if(@pe_fr_alc_dhq in('NA', ''), null, @pe_fr_alc_dhq),
        gly_index_dhq = if(@gly_index_dhq in('NA', ''), null, @gly_index_dhq),
        dt_sugar_dhq = if(@dt_sugar_dhq in('NA', ''), null, @dt_sugar_dhq),
        age_dhq = if(@age_dhq in('NA', ''), null, @age_dhq),
        dhq_completedvalid = if(@dhq_completedvalid in('NA', ''), null, @dhq_completedvalid),
        mped_alc_bev_alc_drinks18_dhq = if(@mped_alc_bev_alc_drinks18_dhq in('NA', ''), null, @mped_alc_bev_alc_drinks18_dhq),
        mped_alc_bev_alc_drinks25_dhq = if(@mped_alc_bev_alc_drinks25_dhq in('NA', ''), null, @mped_alc_bev_alc_drinks25_dhq),
        mped_alc_bev_alc_drinks40_dhq = if(@mped_alc_bev_alc_drinks40_dhq in('NA', ''), null, @mped_alc_bev_alc_drinks40_dhq),
        mped_alc_bev_alc_drinks55_dhq = if(@mped_alc_bev_alc_drinks55_dhq in('NA', ''), null, @mped_alc_bev_alc_drinks55_dhq),
        qxn_f_coffee_dhq = if(@qxn_f_coffee_dhq in('NA', ''), null, @qxn_f_coffee_dhq),
        whfrden_dhq = if(@whfrden_dhq in('NA', ''), null, @whfrden_dhq),
        grnden_dhq = if(@grnden_dhq in('NA', ''), null, @grnden_dhq),
        wgrnden_dhq = if(@wgrnden_dhq in('NA', ''), null, @wgrnden_dhq),
        dairyden_dhq = if(@dairyden_dhq in('NA', ''), null, @dairyden_dhq),
        hei2005_total_score_dhq = if(@hei2005_total_score_dhq in('NA', ''), null, @hei2005_total_score_dhq),
        hei2010_total_score_dhq = if(@hei2010_total_score_dhq in('NA', ''), null, @hei2010_total_score_dhq),
        addsug_perc2015_dhq = if(@addsug_perc2015_dhq in('NA', ''), null, @addsug_perc2015_dhq),
        hei2015_total_score_dhq = if(@hei2015_total_score_dhq in('NA', ''), null, @hei2015_total_score_dhq),
        saltsnkden_g_dhq = if(@saltsnkden_g_dhq in('NA', ''), null, @saltsnkden_g_dhq),
        milkden_dhq = if(@milkden_dhq in('NA', ''), null, @milkden_dhq),
        frtden_g_dhq = if(@frtden_g_dhq in('NA', ''), null, @frtden_g_dhq),
        citfrtden_g_dhq = if(@citfrtden_g_dhq in('NA', ''), null, @citfrtden_g_dhq),
        vegtotden_g_dhq = if(@vegtotden_g_dhq in('NA', ''), null, @vegtotden_g_dhq),
        dkgrvegden_dhq = if(@dkgrvegden_dhq in('NA', ''), null, @dkgrvegden_dhq),
        legumeden_dhq = if(@legumeden_dhq in('NA', ''), null, @legumeden_dhq),
        nutden_dhq = if(@nutden_dhq in('NA', ''), null, @nutden_dhq),
        redmtden_g_dhq = if(@redmtden_g_dhq in('NA', ''), null, @redmtden_g_dhq),
        procmtden_g_dhq = if(@procmtden_g_dhq in('NA', ''), null, @procmtden_g_dhq),
        fishden_g_dhq = if(@fishden_g_dhq in('NA', ''), null, @fishden_g_dhq),
        soyden_dhq = if(@soyden_dhq in('NA', ''), null, @soyden_dhq),
        current_drinker = if(@current_drinker in('NA', ''), null, @current_drinker),
        former_drinker = if(@former_drinker in('NA', ''), null, @former_drinker),
        drinker_status_dhq_o = if(@drinker_status_dhq_o in('NA', ''), null, @drinker_status_dhq_o),
        ph_status = if(@ph_status in('NA', ''), null, @ph_status),
        first_psa_level = if(@first_psa_level in('NA', ''), null, @first_psa_level),
        first_psa_year = if(@first_psa_year in('NA', ''), null, @first_psa_year),
        first_ca125_level = if(@first_ca125_level in('NA', ''), null, @first_ca125_level),
        first_ca125_year = if(@first_ca125_year in('NA', ''), null, @first_ca125_year),
        adenoma_stat = if(@adenoma_stat in('NA', ''), null, @adenoma_stat),
        adenoma_fup_age = if(@adenoma_fup_age in('NA', ''), null, @adenoma_fup_age),
        adenoma_dx_age = if(@adenoma_dx_age in('NA', ''), null, @adenoma_dx_age),
        advanced_adenoma_stat = if(@advanced_adenoma_stat in('NA', ''), null, @advanced_adenoma_stat),
        advanced_adenoma_fup_age = if(@advanced_adenoma_fup_age in('NA', ''), null, @advanced_adenoma_fup_age),
        advanced_adenoma_dx_age = if(@advanced_adenoma_dx_age in('NA', ''), null, @advanced_adenoma_dx_age),
        non_advanced_adenoma_stat = if(@non_advanced_adenoma_stat in('NA', ''), null, @non_advanced_adenoma_stat),
        non_advanced_adenoma_fup_age = if(@non_advanced_adenoma_fup_age in('NA', ''), null, @non_advanced_adenoma_fup_age),
        non_advanced_adenoma_dx_age = if(@non_advanced_adenoma_dx_age in('NA', ''), null, @non_advanced_adenoma_dx_age);

-- import phenotype_sample values
INSERT INTO participant (id, ancestry, sex)
SELECT
    id,
    CASE bq_race7_ca
        WHEN 1 THEN 'white'
        WHEN 2 THEN 'black'
        WHEN 3 THEN 'hispanic'
        WHEN 4 THEN 'asian'
        WHEN 5 THEN 'pacific_islander'
        WHEN 6 THEN 'american_indian'
        ELSE NULL
    END AS ancestry,
    CASE sex
      WHEN 1 THEN 'male'
      WHEN 2 THEN 'female'
      ELSE NULL
    END AS sex
FROM participant_data_stage;

-- remove invalid age_name values 
-- (non-numeric values which are not columns in the participant data stage table)
UPDATE phenotype p 
    SET age_name = NULL
    WHERE 0 = (
    SELECT COUNT(*) FROM information_schema.columns
      WHERE
        table_name = 'participant_data_stage' AND 
        column_name = p.age_name)
    AND age_name NOT REGEXP '^[0-9]+$';


-- import participant_data values
CALL insert_participant_data();

-- create indexes on tables
ALTER TABLE participant_data
    ADD INDEX idx_participant_data__phenotype_id  (phenotype_id);

-- insert average and standard deviation metadata
INSERT INTO phenotype_metadata (phenotype_id, sex, ancestry, chromosome, average_value, standard_deviation)
SELECT
    phenotype_id,
    "all" as sex,
    "all" as ancestry,
    "all" as chromosome,
    avg(value) as average_value,
    std(value) as standard_deviation
FROM participant_data
GROUP BY phenotype_id
ON DUPLICATE KEY UPDATE
    average_value = VALUES(average_value),
    standard_deviation = VALUES(standard_deviation);

COMMIT;