---
- name: Deploy {{ app }}.
  hosts: all
  become: yes
  become_method: sudo
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  vars:
    - app: plco-atlas
    - code_folder: "{{ app_root }}/app"
    - config_folder: "{{ app_root }}/config"
    - logs_folder: "{{ app_root }}/logs"
    - backup_folder: "{{ app_root}}/backup"

  tasks:
    - name: Check if {{ web_service }} service exists
      stat:
        path: /etc/systemd/system/{{ web_service }}.service
      register: service_stat

    - name: Stop {{ web_service }} service
      service:
        name: "{{ web_service }}"
        state: stopped
      when: service_stat.stat.exists

    - name: Setup {{ web_service }} service files
      include_role:
        name: setup-service-files
      vars:
        service_name: "{{ web_service }}"
        command: "/bin/npm start"

    - name: Create folders for {{ app }}
      file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ ncianalysis_user }}"
        group: apache
      with_items:
        - "{{ code_folder }}"
        - "{{ config_folder }}"
        - "{{ logs_folder }}"

    - name: Backup {{ app }}
      shell: >
        rm -rf {{ backup_folder }};
        mv {{ code_folder }} {{ backup_folder }};
      args:
        warn: no

    - name: Copy {{ app }}
      synchronize:
        src: "{{ workspace_folder }}/{{ app }}/"
        dest: "{{ code_folder }}"
        delete: yes
        rsync_opts:
          - "--exclude=.git"

    # the file module is slow with large numbers of files (eg: node_modules)
    - name: Set permissions on {{ app_root }}
      shell: chown -R {{ ncianalysis_user }}:apache {{ app_root }}
      args:
        warn: no

    - name: Build {{ app }} backend
      shell: npm install
      args:
        chdir: "{{ code_folder }}"
      async: 1800
      poll: 5

    - name: Build {{ app }} frontend
      become_user: "{{ ncianalysis_user }}"
      shell: >
        if [ -d {{ backup_folder }}/client/node_modules ]; then
          cp -r {{ backup_folder }}/client/node_modules .
        fi;
        npm install;
        npm run build;
      args:
        chdir: "{{ code_folder }}/client"
      async: 1800
      poll: 5

    - name: Copy configuration file from config/ to app/
      copy:
        src: "{{ config_folder }}/config.json"
        dest: "{{ code_folder }}/server"
        remote_src: yes
        owner: "{{ ncianalysis_user }}"

    - name: Start {{ web_service }} service
      service:
        name: "{{ web_service }}"
        state: started

    - name: reinitialize redis cache
      shell: node scripts/reinitialize-cache.js
      args:
        chdir: "{{ code_folder }}"
      when: "reinitialize_redis_cache is defined and reinitialize_redis_cache | bool"
